const RegFieldName = {
    //Main
    HKID: 'hkid',
    HKID_NUM: 'hkidNum',
    EHRPATIENTID: 'ehrPatientId',
    ENGLISH_SURNAME: 'engSurname',
    ENGLISH_GIVENNAME: 'engGivename',
    DOCUMENT_NUMBER: 'otherDocNo',
    DOCUMENT_TYPE: 'docTypeCd',
    CHINESE_NAME: 'nameChi',
    EXACT_DATE_OF_BIRTH: 'dob',
    EXACT_DATE_OF_BIRTH_FORMAT: 'exactDobCd',
    BIRTH_PLACE: 'birthPlaceCd',
    CHINESE_CODE1: 'ccCode1',
    CHINESE_CODE2: 'ccCode2',
    CHINESE_CODE3: 'ccCode3',
    CHINESE_CODE4: 'ccCode4',
    CHINESE_CODE5: 'ccCode5',
    CHINESE_CODE6: 'ccCode6',
    OTHER_NAME: 'otherName',
    GENDER: 'genderCd',
    PRIMARY_DOC_TYPE: 'primaryDocTypeCd',
    PRIMARY_DOC_NO: 'primaryDocNo',
    PRIMARY_ISSUE_COUNTRY_CD: 'priIssueCountryCd',
    ADDITIONAL_DOC_TYPE: 'additionalDocTypeCd',
    ADDITIONAL_DOC_NO: 'additionalDocNo',
    ADDITIONAL_ISSUE_COUNTRY_CD: 'addlIssueCountryCd',
    WITH_PROVEN_DOC: 'idSts',
    PATIENT_STATUS: 'patientSts',
    ELIGIBLE_FOR_NTKFMTC: 'isFm',
    PENSIONER: 'isPnsn',
    JOINED_PCFB: 'tbcPcfbDate',
    ALLOW_SINGLE_NAME: 'allowSingleNameInput',
    DTS_SPECIALNEEDS_CATEGORY: 'dtsSpecNeedCatgryId',
    DTS_SPECIALNEEDS_SUBCATEGORY: 'dtsSpecNeedScatgryId',

    //Contact
    CONTACT_PHONE_COUNTRY: 'countryCd',
    CONTACT_PHONE_AREA: 'areaCd',
    CONTACT_PHONE_NO: 'phoneNo',
    CONTACT_PHONE_PRIORITY: 'phonePriority',
    CONTACT_PHONE_SMS: 'smsPhoneInd',
    CONTACT_EMAIL: 'emailAddress',
    CONTACT_ROOM: 'room',
    CONTACT_FLOOR: 'floor',
    CONTACT_BLOCK: 'block',
    CONTACT_BUILDING: 'building',
    CONTACT_ESTATELOT: 'estate',
    CONTACT_STREET_NO: 'streetNo',
    CONTACT_STREET: 'streetName',
    CONTACT_POSTOFFICE_BOXNO: 'postOfficeBoxNo',
    CONTACT_POSTOFFICE_NAME: 'postOfficeName',
    CONTACT_POSTOFFICE_REGION: 'postOfficeRegion',
    CONTACT_REGION: 'region',
    CONTACT_DISTRICT: 'districtCd',
    CONTACT_SUB_DISTRICT: 'subDistrictCd',
    CONTACT_CORRESPONDENCE_REGION: 'region',
    CONTACT_CORRESPONDENCE_DISTRICT: 'districtCd',
    CONTACT_CORRESPONDENCE_SUB_DISTRICT: 'subDistrictCd',
    CONTACT_RESIDENTIAL_REGION: 'region',
    CONTACT_RESIDENTIAL_DISTRICT: 'districtCd',
    CONTACT_RESIDENTIAL_SUB_DISTRICT: 'subDistrictCd',
    CONTACT_ADDRESS_FORMAT: 'addressFormat',
    CONTACT_ADDRESS_LANGUAGE_CD: 'addressLanguageCd',

    //Contact Person
    CONTACT_PERSON_ENGLISH_SURNAME: 'engSurname',
    CONTACT_PERSON_ENGLISH_GIVENNAME: 'engGivename',
    CONTACT_PERSON_CHINESE_NAME: 'nameChi',
    CONTACT_PERSON_EMAIL: 'emailAddress',
    CONTACT_PERSON_ROOM: 'room',
    CONTACT_PERSON_FLOOR: 'floor',
    CONTACT_PERSON_BLOCK: 'block',
    CONTACT_PERSON_BUILDING: 'building',
    CONTACT_PERSON_RELATIONSHIP: 'relationshipCd',
    CONTACT_PERSON_DISTRICT: 'districtCd',
    CONTACT_PERSON_SUB_DISTRICT: 'subDistrictCd',
    CONTACT_PERSON_ESTATELOT: 'estate',
    CONTACT_PERSON_STREET_NO: 'streetNo',
    CONTACT_PERSON_STREET: 'streetName',
    CONTACT_PERSON_REGION: 'region',
    CONTACT_PERSON_PHONE_COUNTRY: 'countryCd',
    CONTACT_PERSON_PHONE_AREA: 'areaCd',
    CONTACT_PERSON_PHONE_NO: 'phoneNo',
    CONTACT_PERSON_ADDRESS_FORMAT: 'addressFormat',
    CONTACT_PERSON_LANGUAGE_CD: 'addressLanguageCd',

    //Social Data
    SOCIAL_DATA_ETHNICITY: 'ethnicityCd',
    SOCIAL_DATA_MARITAL_STATUS: 'maritalStatusCd',
    SOCIAL_DATA_Religion: 'religionCd',
    SOCIAL_DATA_OCCUPATION: 'occupationCd',
    SOCIAL_DATA_TRANSLATION_LANGUAGE: 'translationLangCd',
    SOCIAL_DATA_EDUCATION_LEVEL: 'eduLevelCd',
    SOCIAL_DATA_GOVERNMENT_DEPARTMENT: 'govDptCd',
    SOCIAL_DATA_RANK: 'rank',
    SOCIAL_DATA_REMARKS: 'remarks',

    //additional field name
    CHANGE_ADDRESS_FORMAT: 'changeAddressFormat'
};

export default RegFieldName;