const DTS_DATE_DISPLAY_FORMAT = 'DD/MM/YYYY';
const DTS_DATE_WEEKDAY_DISPLAY_FORMAT = 'DD/MM/YYYY(ddd)';
const DTS_TIME_TO_SECONDS_DISPLAY_FORMAT = 'HH:mm:ss';

export {
    DTS_DATE_DISPLAY_FORMAT,
    DTS_DATE_WEEKDAY_DISPLAY_FORMAT,
    DTS_TIME_TO_SECONDS_DISPLAY_FORMAT
};