const PREFFIX = 'JOS_PROCEDURETEMPLATE_VIEW';
export const PROCEDURE_REQUEST_DATA=`${PREFFIX}_PROCEDURE_REQUEST_DATA`;
export const PROCEDURE_LIST_DATA=`${PREFFIX}_PROCEDURE_LIST_DATA`;

export const SAVE_PROCEDURE_DATA=`${PREFFIX}_SAVE_PROCEDURE_DATA`;
export const SAVE_PROCEDURE_RESULT=`${PREFFIX}_SAVE_PROCEDURE_RESULT`;
export const SAVE_PROCEDURE_TEMPLATE_DATA=`${PREFFIX}_SAVE_PROCEDURE_TEMPLATE_DATA`;

export const GET_EDITTEMPLATELIST_DATA=`${PREFFIX}_GET_EDITTEMPLATELIST_DATA`;

export const GET_INPUT_PROCEDURE_LIST = `${PREFFIX}_GET_INPUT_PROCEDURE_LIST`;
export const INPUT_PROCEDURE_LIST = `${PREFFIX}_INPUT_PROCEDURE_LIST`;
export const GET_PROCEDURE_STATUS = `${PREFFIX}_GET_PROCEDURE_STATUS`;
export const UPDATE_PATIENT_PROCEDURE = `${PREFFIX}_UPDATE_PATIENT_PROCEDURE`;
export const DELETE_PATIENT_PROCEDURE = `${PREFFIX}_DELETE_PATIENT_PROCEDURE`;
export const GET_PROCEDURE_SEARCH_LIST = `${PREFFIX}_GET_PROCEDURE_SEARCH_LIST`;

export const QUERY_PROCEDURE_LIST= `${PREFFIX}_QUERY_PROCEDURE_LIST`;