const PREFFIX = 'REPORT_TEMPLATE';
export const RESET_ALL=`${PREFFIX}_RESET_ALL`;
// export const DESTROY_PAGE=`${PREFFIX}_INITAL_PAGE`;
export const UPDATE_FIELD=`${PREFFIX}_UPDATE_FIELD`;
export const REQUEST_DATA=`${PREFFIX}_REQUEST_DATA`;
export const POST_DATA=`${PREFFIX}_POST_DATA`;
export const PUT_DATA=`${PREFFIX}_PUT_DATA`;
export const DELETE_DATA=`${PREFFIX}_DELETE_DATA`;
export const FILLING_DATA=`${PREFFIX}_FILLING_DATA`;
// export const RESET_INFO_ALL=`${PREFFIX}_RESET_INFO_ALL`;
export const GET_ENCOUNTER_TYPE_LIST=`${PREFFIX}_GET_ENCOUNTER_TYPE_LIST`;
export const GET_CLINIC_LIST=`${PREFFIX}_GET_CLINIC_LIST`;

//saga put
export const PUT_ENCOUNTER_TYPE_LIST=`${PREFFIX}_PUT_ENCOUNTER_TYPE_LIST`;

//print appointment list
export const OPEN_PREVIEW_WINDOW=`${PREFFIX}_OPEN_PREVIEW_WINDOW`;
export const PUT_REPORT_TEMPLATE_DATA=`${PREFFIX}_PUT_REPORT_TEMPLATE_DATA`;

// Dynamic Form API
export const GET_DYNAMIC_FORM_PARAMETER_API=`${PREFFIX}_GET_DYNAMIC_FORM_PARAMETER_API`;
export const PUT_TEMPLATE_DYNAMIC_FORM_PARAMETER=`${PREFFIX}_PUT_TEMPLATE_DYNAMIC_FORM_PARAMETER`;
export const PUT_CONFIGS_DYNAMIC_FORM_PARAMETER=`${PREFFIX}_PUT_CONFIGS_DYNAMIC_FORM_PARAMETER`;
//long polling report job
export const JOB_LONG_POLLING=`${PREFFIX}_JOB_LONG_POLLING`;

