const CLINICAL_NOTE_TEMPLATE_TYPE = {
  SERVICE_FAVOURITE: 'S',
  MY_FAVOURITE: 'M',
  CLINIC_FAVOURITE:'C'
};

const ACTION_TYPE = {
  DELETE: 'D',
  UPDATE: 'U',
  INSERT: 'I'
};

const NEW_STATUS_TYPE = {
  YES: 'Y',
  NO: 'N'
};

const INSERT_LOG_STATUS ={
  Save:'Save',
  Click:'Click',
  Select:'Select'
};

const OPERATION_ALLOWED_TYPE = {
  YES: 'Y',
  NO: 'N'
};

const OPERATION_TIME_OUT = {
  TIME: 60000
};

const CLINICAL_NOTE_TYPE_ID = {
  DOCTOR: 1,
  NURSE: 2,
  VACCINATION: 11
};

const CLINICAL_NOTE_FAIL_CONNECT = {
  VACCINATION: 'FAIL_TO_CONNECT_VACCINATION_SERVICE'
};

export {
  CLINICAL_NOTE_TEMPLATE_TYPE,
  ACTION_TYPE,
  NEW_STATUS_TYPE,
  OPERATION_ALLOWED_TYPE,
  INSERT_LOG_STATUS,
  OPERATION_TIME_OUT,
  CLINICAL_NOTE_TYPE_ID,
  CLINICAL_NOTE_FAIL_CONNECT
};
