const PRE = 'ASSESSMENT';

// Assessment Setting
export const ASSESSMENT_SETTING_ITEM_LIST = `${PRE}_SETTING_ITEM_LIST`;
export const ASSESSMENT_SETTING_CHECKED_ITEM_LIST = `${PRE}_SETTING_CHECKED_ITEM_LIST`;
export const GET_ASSESSMENT_SETTING_ITEM_LIST = `${PRE}_GET_SETTING_ITEM_LIST`;
export const UPDATE_ASSESSMENT_SETTING_ITEM_LIST = `${PRE}_UPDATE_SETTING_ITEM_LIST`;
export const GET_ASSESSMENT_CHECKED_ITEM_LIST = `${PRE}_GET_CHECKED_ITEM_LIST`;
export const ASSESSMENT_CHECKED_ITEM_LIST = `${PRE}_CHECKED_ITEM_LIST`;
export const GET_ASSESSMENT_FIELD_MAPPING_LIST = `${PRE}_GET_ASSESSMENT_FIELD_MAPPING_LIST`;

// General Assessment
export const GET_PATIENT_ASSESSMENT_LIST = `${PRE}_GET_PATIENT_ASSESSMENT_LIST`;
export const PATIENT_ASSESSMENT_LIST = `${PRE}_PATIENT_ASSESSMENT_LIST`;
export const GET_PATIENT_ASSESSMENT_VAL = `${PRE}_GET_PATIENT_ASSESSMENT_VAL`;
export const PATIENT_ASSESSMENT_VAL = `${PRE}_PATIENT_ASSESSMENT_VAL`;
export const GET_FIELD_DROP_LIST = `${PRE}_GET_FIELD_DROP_LIST`;
export const FIELD_DROP_LIST = `${PRE}_FIELD_DROP_LIST`;
export const GET_FIELD_NORMAL_RANGE_MAP = `${PRE}_GET_FIELD_NORMAL_RANGE_MAP`;
export const FIELD_NORMAL_RANGE_MAP = `${PRE}_FIELD_NORMAL_RANGE_MAP`;
export const UPDATE_PATIENT_ASSESSMENT = `${PRE}_UPDATE_PATIENT_ASSESSMENT`;

//ordering  Assessment
export const GET_ORDERING_ASSESSMENT_LIST = `${PRE}_GET_ORDERING_ASSESSMENT_LIST`;
export const SAVE_ORDERING_ASSESSMENT_LIST = `${PRE}_SAVE_ORDERING_ASSESSMENT_LIST`;

//Assessment History
export const GET_ASSESSMENT_HISTORY_TABLEHEAD_LIST=`${PRE}_GET_ASSESSMENT_HISTORY_TABLEHEAD_LIST`;
export const GET_ASSESSMENT_HISTORY_TABLEBODY_LIST=`${PRE}_GET_ASSESSMENT_HISTORY_TABLEBODY_LIST`;

export const INSERT_ASSESSMENT_LOG = `${PRE}_INSERT_ASSESSMENT_LOG`;
