const PREFFIX = 'JOS_MRAM_BACKGROUNDINFOMATION_VIEW';
export const INIT_MRAM_BACKGROUND_INFORMATION_FIELD_VALUE = `${PREFFIX}_MRAM__BACKGROUND_INFORMATION_FIELD_VALUE`;
export const SAVE_BACKGROUND_INFO_DATA=`${PREFFIX}_SAVE_BACKGROUND_INFO_DATA`;
export const SAVE_BACKGROUND_INFO_RESULT=`${PREFFIX}_SAVE_BACKGROUND_INFO_RESULT`;
export const SAVE_CAREPLAN_INFO_DATA=`${PREFFIX}_SAVE_CAREPLAN_INFO_DATA`;
export const SAVE_CAREPLAN_INFO_RESULT=`${PREFFIX}_SAVE_CAREPLAN_INFO_RESULT`;
