const PRE = 'SERVICE_PROFILE';

export const SERVICE_PROFILE_FRAMEWORK_LIST = `${PRE}_SERVICE_PROFILE_FRAMEWORK_LIST`;
export const GET_SERVICE_PROFILE_FRAMEWORK_LIST = `${PRE}_GET_SERVICE_PROFILE_FRAMEWORK_LIST`;
export const SERVICE_PROFILE_DROPDOWN_LIST = `${PRE}_SERVICE_PROFILE_DROPDOWN_LIST`;
export const GET_SERVICE_PROFILE_DROPDOWN_LIST = `${PRE}_GET_SERVICE_PROFILE_DROPDOWN_LIST`;
export const SAVE_SERVICE_PROFILE = `${PRE}_SAVE_SERVICE_PROFILE`;
export const GET_SERVICE_PROFILE_TEMPLATE = `${PRE}_GET_SERVICE_PROFILE_TEMPLATE`;
export const SERVICE_PROFILE_TEMPLATE = `${PRE}_SERVICE_PROFILE_TEMPLATE`;
export const GET_TEMPLATE_ALL_ITEMS_FOR_SEARCH = `${PRE}_GET_TEMPLATE_ALL_ITEMS_FOR_SEARCH`;
export const TEMPLATE_ALL_ITEMS_FOR_SEARCH = `${PRE}_TEMPLATE_ALL_ITEMS_FOR_SEARCH`;

export const SET_SERVICE_PROFILE_LIST = `${PRE}_SET_SERVICE_PROFILE_LIST`;
export const GET_SERVICE_PROFILE_LIST = `${PRE}_GET_SERVICE_PROFILE_LIST`;
export const SAVE_SERVICE_PROFILE_LIST = `${PRE}_SAVE_SERVICE_PROFILE_LIST`;

export const CHECKTEMPLATENAMEREPEAT_DATA = `${PRE}_CHECKTEMPLATENAMEREPEAT_DATA`;

