const REDIRECT_ACTION_TYPE = {
    ENCOUNTER_HISTORY: 'Encounter History',
    PRINT_DH65_LABEL: 'Print DH65 label',
    PRINT_ADDRESS_LABEL: 'Print Address label',
    PRINT_CHANGE_FORM: 'Print Change Form',
    PRINT_PMI_BARCODE: 'Print Pmi Barcode',
    PRINT_APPOINTMENT_LABEL: 'Print Appt Label',
    PRINT_APPOINTMENT_SLIP: 'Print Appt Slip',
    REASSIGN_URGENT_APPOINTMENT: 'Reassign Urgent Appt',
    GP_URGENT_APPOINTMENT: 'GP Urgent Appt',
    URGENT_APPOINTMENT: 'Urgent Appt',
    EDIT_APPOINTMENT: 'Edit Appt',
    MAKE_APPOINTMENT: 'New Appt',
    ATTEND_APPOINTMENT:'Attend',
    REVOKE_APPOINTMENT:'Revoke',
    PRINT_RESERVE_LIST:'Print Reserve List'
};

const CLINIC_CONFIGNAME = {
    PMI_BARCODE_LABEL_PRINT_QUEUE: 'PMI_BARCODE_LABEL_PRINT_QUEUE',
    PMI_BARCODE_LABEL_PRINT_ORIENTATION: 'PMI_BARCODE_LABEL_PRINT_ORIENTATION',
    PMI_BARCODE_LABEL_PRINT_TRAY: 'PMI_BARCODE_LABEL_PRINT_TRAY',
    PMI_BARCODE_LABEL_PRINT_PAPER_SIZE: 'PMI_BARCODE_LABEL_PRINT_PAPER_SIZE',

    DH65_LABEL_PRINT_QUEUE: 'DH65_LABEL_PRINT_QUEUE',
    DH65_LABEL_PRINT_ORIENTATION: 'DH65_LABEL_PRINT_ORIENTATION',
    DH65_LABEL_PRINT_TRAY: 'DH65_LABEL_PRINT_TRAY',
    DH65_LABEL_PRINT_PAPER_SIZE: 'DH65_LABEL_PRINT_PAPER_SIZE',

    PMI_ADDRESS_LABEL_PRINT_QUEUE: 'PMI_ADDRESS_LABEL_PRINT_QUEUE',
    PMI_ADDRESS_LABEL_PRINT_ORIENTATION: 'PMI_ADDRESS_LABEL_PRINT_ORIENTATION',
    PMI_ADDRESS_LABEL_PRINT_TRAY: 'PMI_ADDRESS_LABEL_PRINT_TRAY',
    PMI_ADDRESS_LABEL_PRINT_PAPER_SIZE: 'PMI_ADDRESS_LABEL_PRINT_PAPER_SIZE',

    PMI_APPOINTMENT_LABEL_PRINT_QUEUE: 'PMI_APPOINTMENT_LABEL_PRINT_QUEUE',
    PMI_APPOINTMENT_LABEL_PRINT_ORIENTATION: 'PMI_APPOINTMENT_LABEL_PRINT_ORIENTATION',
    PMI_APPOINTMENT_LABEL_PRINT_TRAY: 'PMI_APPOINTMENT_LABEL_PRINT_TRAY',
    PMI_APPOINTMENT_LABEL_PRINT_PAPER_SIZE: 'PMI_APPOINTMENT_LABEL_PRINT_PAPER_SIZE',

    PRINT_CHANGE_FORM_PRINT_QUEUE:'PRINT_CHANGE_FORM_PRINT_QUEUE',
    PRINT_CHANGE_FORM_PRINT_ORIENTATION: 'PRINT_CHANGE_FORM_PRINT_ORIENTATION',
    PRINT_CHANGE_FORM_PRINT_TRAY: 'PRINT_CHANGE_FORM_PRINT_TRAY',
    PRINT_CHANGE_FORM_PRINT_PAPER_SIZE: 'PRINT_CHANGE_FORM_PRINT_PAPER_SIZE',

    APPOINTMENT_SLIP_PRINT_QUEUE:'APPOINTMENT_SLIP_PRINT_QUEUE',
    APPOINTMENT_SLIP_PRINT_ORIENTATION: 'APPOINTMENT_SLIP_PRINT_ORIENTATION',
    APPOINTMENT_SLIP_PRINT_TRAY: 'APPOINTMENT_SLIP_PRINT_TRAY',
    APPOINTMENT_SLIP_PRINT_PAPER_SIZE: 'APPOINTMENT_SLIP_PRINT_PAPER_SIZE',

    RESERVE_LIST_PRINT_QUEUE:'RESERVE_LIST_PRINT_QUEUE',
    RESERVE_LIST_PRINT_ORIENTATION: 'RESERVE_LIST_PRINT_ORIENTATION',
    RESERVE_LIST_PRINT_TRAY: 'RESERVE_LIST_PRINT_TRAY',
    RESERVE_LIST_PRINT_PAPER_SIZE: 'RESERVE_LIST_PRINT_PAPER_SIZE',

    REMIND_APPOINTMENT_LIST_PRINT_QUEUE:'REMIND_APPOINTMENT_LIST_PRINT_QUEUE',
    REMIND_APPOINTMENT_LIST_PRINT_ORIENTATION: 'REMIND_APPOINTMENT_LIST_PRINT_ORIENTATION',
    REMIND_APPOINTMENT_LIST_PRINT_TRAY: 'REMIND_APPOINTMENT_LIST_PRINT_TRAY',
    REMIND_APPOINTMENT_LIST_PRINT_PAPER_SIZE: 'REMIND_APPOINTMENT_LIST_PAPER_SIZE'
};

export { REDIRECT_ACTION_TYPE, CLINIC_CONFIGNAME };
