const PRE='CARE_AND_TREATMENT_PLAN';

export const RESET_ALL=`${PRE}_RESET_ALL`;
export const CTRL_CREATE_AND_UPDATE_DIALOG=`${PRE}_CTRL_CREATE_AND_UPDATE_DIALOG`;
export const CTP_SUMAMRY=`${PRE}_CTP_SUMMARY`;
export const LIST_REFERRAL_LETTER=`${PRE}_LIST_REFERRAL_LETTER`;
export const LIST_FOLLOW_UP=`${PRE}_LIST_FOLLOW_UP`;
export const LIST_HLTH_EDU_RCMD=`${PRE}_LIST_HLTH_EDU_RCMD`;
export const LOAD_REFERRAL_LETTER=`${PRE}_LOAD_REFERRAL_LETTER`;
export const LOAD_FOLLOW_UP=`${PRE}_LOAD_FOLLOW_UP`;
export const LOAD_HLTH_EDU_RCMD=`${PRE}_LOAD_HLTH_EDU_RCMD`;
export const PREVIE_RFR_LETTER=`${PRE}_PREVIE_RFR_LETTER`;
export const LOAD_RFR_LETTER_64=`${PRE}_LOAD_RFR_LETTER_64`;
export const UPDATE_FIELD=`${PRE}_UPDATE_FIELD`;
export const GET_CTP_BY_TODAY_ENCNTR=`${PRE}_GET_CTP_BY_TODAY_ENCNTR`;
export const LOAD_FLW_UP_FORM_ENCNTR=`${PRE}_LOAD_FLW_UP_FORM_ENCNTR`;
export const LOAD_TODAY_EDU_RCMD=`${PRE}_LOAD_TODAY_EDU_RCMD`;
export const SUBMIT_TODAY_CTP_DATA=`${PRE}_SUBMIT_TODAY_CTP_DATA`;