const PRE = 'IX_REQUEST';

export const GET_IX_REQUEST_FRAMEWORK_LIST = `${PRE}_GET_IX_REQUEST_FRAMEWORK_LIST`;
export const IX_REQUEST_FRAMEWORK_LIST = `${PRE}_IX_REQUEST_FRAMEWORK_LIST`;
export const GET_IX_REQUEST_ITEM_DROPDOWN_LIST = `${PRE}_GET_IX_REQUEST_ITEM_DROPDOWN_LIST`;
export const IX_REQUEST_ITEM_DROPDOWN_LIST = `${PRE}_IX_REQUEST_ITEM_DROPDOWN_LIST`;
export const GET_IX_REQUEST_ORDER_LIST = `${PRE}_GET_IX_REQUEST_ORDER_LIST`;
export const IX_REQUEST_ORDER_LIST = `${PRE}_IX_REQUEST_ORDER_LIST`;
export const GET_IX_REQUEST_SPECIFIC_ITEM_MAPPING = `${PRE}_GET_IX_REQUEST_SPECIFIC_ITEM_MAPPING`;
export const IX_REQUEST_SPECIFIC_ITEM_MAPPING = `${PRE}_IX_REQUEST_SPECIFIC_ITEM_MAPPING`;
export const GET_IX_ALL_ITEMS_FOR_SEARCH = `${PRE}_GET_IX_ALL_ITEMS_FOR_SEARCH`;
export const IX_ALL_ITEMS_FOR_SEARCH = `${PRE}_IX_ALL_ITEMS_FOR_SEARCH`;

export const GET_ALL_IX_PROFILE_TEMPLATE = `${PRE}_GET_ALL_IX_PROFILE_TEMPLATE`;
export const ALL_IX_PROFILE_TEMPLATE = `${PRE}_ALL_IX_PROFILE_TEMPLATE`;

export const SAVE_IX_REQUEST_ORDER = `${PRE}_SAVE_IX_REQUEST_ORDER`;
export const DO_ALL_OPERATION = `${PRE}_DO_ALL_OPERATION`;
export const DO_ALL_OPERATION_SUBMIT = `${PRE}_DO_ALL_OPERATION_SUBMIT`;
export const DO_ALL_OPERATION_SAVE = `${PRE}_DO_ALL_OPERATION_SAVE`;

export const GET_SERVICE_SPECIFIC_FUNCTION_INFO = `${PRE}_GET_SERVICE_SPECIFIC_FUNCTION_INFO`;

export const GET_CODE_IOE_FORM_PANEL_MAPPING = `${PRE}_GET_CODE_IOE_FORM_PANEL_MAPPING`;
export const CODE_IOE_FORM_PANEL_MAPPING = `${PRE}_CODE_IOE_FORM_PANEL_MAPPING`;
export const GET_ANTENATAL_SERVICE_ID = `${PRE}_GET_ANTENATAL_SERVICE_ID`;

export const GET_LIST_EXPRESS_IOE = `${PRE}_GET_LIST_EXPRESS_IOE`;

export const PUT_LIST_EXPRESS_IOE = `${PRE}_PUT_LIST_EXPRESS_IOE`;

