const PREFFIX = 'JOS_TAG_A_NOTE_VIEW';
export const REQUEST_DATA=`${PREFFIX}_REQUEST_DATA`;
export const FILLING_DATA=`${PREFFIX}_FILLING_DATA`;
export const TEMPLATE_DATA=`${PREFFIX}_TEMPLATE_DATA`;
export const PUTTEMPLATELIST_DATA=`${PREFFIX}_PUTTEMPLATELIST_DATA`;
export const DELETETEMPLATE_DATA=`${PREFFIX}_DELETETEMPLATE_DATA`;
export const DELETETEMPLATE_RESULT=`${PREFFIX}_DELETETEMPLATE_RESULT`;
export const RECORDLIST_DATA=`${PREFFIX}_RECORDLIST_DATA`;
export const RECORDLIST_RESULT=`${PREFFIX}_RECORDLIST_RESULT`;

export const ADDTEMPLATE_DATA=`${PREFFIX}_ADDTEMPLATE_DATA`;
export const ADDTEMPLATE_RESULT=`${PREFFIX}_ADDTEMPLATE_RESULT`;

export const EDITTEMPLATE_DATA=`${PREFFIX}_EDITTEMPLATE_DATA`;
export const EDITTEMPLATE_RESULT=`${PREFFIX}_EDITTEMPLATE_RESULT`;

export const GET_TEMPLATE_DATA_LIST=`${PREFFIX}_GET_TEMPLATE_DATA_LIST`;

export const CHECKTEMPLATENAMEREPEAT_DATA=`${PREFFIX}_CHECKTEMPLATENAMEREPEAT_DATA`;

export const FETCH_TAGANOTE_TYPE_LIST = `${PREFFIX}_FETCH_TAGANOTE_TYPE_LIST`;
export const SET_TAGANOTE_TYPE_LIST = `${PREFFIX}_SET_TEMPLATE_NOTE_TYPE_LIST`;