const MRAM_FEET_NEUROLOGY_EXAMINATION_PREFIX = 'fane';
const MRAM_FEET_FOOT_PATHOLOGY_PREFIX = 'fafp';
const MRAM_FEET_VASCULAR_ASSESSMENT_PREFIX = 'fava';
const MRAM_FEET_OTHER_INFORMATION_PREFIX = 'faoi';

const MRAM_FEET_NEUROLOGY_EXAMINATION_ID = {
  RIGHT_MONOFILAMENT_TEST:'102',
  LEFT_MONOFILAMENT_TEST:'103',
  RIGHT_FOOT_128HZ_TUNING_FORK:'104',
  LEFT_FOOT_128HZ_TUNING_FORK:'105',
  RIGHT_FOOT_GRADUATED_TUNING_FORK:'106',
  LEFT_FOOT_GRADUATED_TUNING_FORK:'107',
  RIGHT_FOOT_VPT:'108',
  LEFT_FOOT_VPT:'109',
  RIGHT_FOOT_ABNORMAL_VIBRATION_SENSE:'110',
  LEFT_FOOT_ABNORMAL_VIBRATION_SENSE:'111',
  RIGHT_FOOT_ACHILLES_REFLEXES:'112',
  LEFT_FOOT_ACHILLES_REFLEXES:'113',
  RIGHT_FOOT_ABNORMAL_PINPRICK_SENSATION:'209',
  LEFT_FOOT_ABNORMAL_PINPRICK_SENSATION:'210',
  RIGHT_FOOT_ABNORMAL_TEMPERATURE_SENSATION:'114',
  LEFT_FOOT_ABNORMAL_TEMPERATURE_SENSATION:'115'
};

const MRAM_FEET_FOOT_PATHOLOGY_ID = {
  RIGHT_FOOT_NAIL_PATHOLOGY:'116',
  LEFT_FOOT_NAIL_PATHOLOGY:'117',
  RIGHT_FOOT_DEFORMITY:'118',
  LEFT_FOOT_DEFORMITY:'119',
  RIGHT_FOOT_DRY_SKINCALLUS:'120',
  LEFT_FOOT_DRY_SKINCALLUS:'121',
  RIGHT_FOOT_INFECTION:'122',
  LEFT_FOOT_INFECTION:'123',
  RIGHT_FOOT_FISSURE:'124',
  LEFT_FOOT_FISSURE:'125',
  RIGHT_FOOT_ISCHAEMIC_CHANGE:'126',
  LEFT_FOOT_ISCHAEMIC_CHANGE:'127',
  RIGHT_FOOT_HX_OF_ULCER:'128',
  LEFT_FOOT_HX_OF_ULCER:'129',
  RIGHT_FOOT_ACTIVE_ULCER:'130',
  LEFT_FOOT_ACTIVE_ULCER:'131'
};

const MRAM_FEET_VASCULAR_ASSESSMENT_ID = {
  RIGHT_FOOT_REVASCULARIZATION:'132',
  LEFT_FOOT_REVASCULARIZATION:'133',
  RIGHT_FOOT_CALUDICATION:'134',
  LEFT_FOOT_CALUDICATION:'135',
  RIGHT_FOOT_REST_PAIN:'136',
  LEFT_FOOT_REST_PAIN:'137',
  RIGHT_FOOT_DORSALIS_PEDIS_FOOT_PULSE:'138',
  LEFT_FOOT_DORSALIS_PEDIS_FOOT_PULSE:'139',
  RIGHT_FOOT_POSTERIOR_TIBIA_FOOT_PULSE:'140',
  LEFT_FOOT_POSTERIOR_TIBIA_FOOT_PULSE:'141',
  RIGHT_FOOT_ANKLE_SYSTOLIC_BP:'142',
  LEFT_FOOT_ANKLE_SYSTOLIC_BP:'143',
  RIGHT_FOOT_BRACHIAL_SYSTOLIC_BP:'144',
  LEFT_FOOT_BRACHIAL_SYSTOLIC_BP:'145',
  RIGHT_FOOT_ABI:'211',
  LEFT_FOOT_ABI: '212',
  RIGHT_FOOT_ABNORMAL_FOOT_PULSE: '215',
  LEFT_FOOT_ABNORMAL_FOOT_PULSE: '216'
};

const MRAM_FEET_OTHER_INFORMATION_ID = {
  RIGHT_FOOT_FOOTWEAR_PROBLEM:'146',
  LEFT_FOOT_FOOTWEAR_PROBLEM:'147',
  REMARKS:'148',
  FEET_ASSESSED_BY:'149',
  FEET_ASSESSMENT_DATE:'150'
};

const DL_MONOFILAMENT_TEST = [
  {
    label:'[Blank]',
    value:'[Blank]'
  },{
    label:'Normal',
    value:'Normal'
  },{
    label:'Abnormal',
    value:'Abnormal'
  }
];

const DL_128HZ_TUNING_FORK = [
  {
    label:'[Blank]',
    value:' '
  },{
    label:'Normal',
    value:'Normal'
  },{
    label:'Diminished',
    value:'Diminished'
  },{
    label:'Absent',
    value:'Absent'
  }
];

const DL_ACHILLES_REFLEXES = [
  {
    label:'[Blank]',
    value:'[Blank]'
  },{
    label:'Present',
    value:'Present'
  },{
    label:'Present with reinforcement',
    value:'Present with reinforcement'
  },{
    label:'Absent',
    value:'Absent'
  }
];

const MRAM_FEET_ID_MAP = new Map([
  [MRAM_FEET_NEUROLOGY_EXAMINATION_PREFIX,MRAM_FEET_NEUROLOGY_EXAMINATION_ID],
  [MRAM_FEET_FOOT_PATHOLOGY_PREFIX,MRAM_FEET_FOOT_PATHOLOGY_ID],
  [MRAM_FEET_VASCULAR_ASSESSMENT_PREFIX,MRAM_FEET_VASCULAR_ASSESSMENT_ID],
  [MRAM_FEET_OTHER_INFORMATION_PREFIX,MRAM_FEET_OTHER_INFORMATION_ID]
]);

const RANGE_GRADUATED_TUNING_FORK = {
  minVal: 0,
  maxVal: 8
};

const RANGE_VPT = {
  minVal: 0,
  maxVal: 50
};

const RANGE_ANKLE_SYSTOLIC_BP = {
  minVal: 30,
  maxVal: 300
};

const RANGE_BRACHIAL_SYSTOLIC_BP = {
  minVal: 10,
  maxVal: 300
};

const RANGE_ABI = {
  minVal: 0.9,
  maxVal: 9999
};

const LEFT_ABNORMAL_VIBRATION_SENSE_FACTOR_ID_SET = new Set([
  MRAM_FEET_NEUROLOGY_EXAMINATION_ID.LEFT_FOOT_128HZ_TUNING_FORK,
  MRAM_FEET_NEUROLOGY_EXAMINATION_ID.LEFT_FOOT_GRADUATED_TUNING_FORK,
  MRAM_FEET_NEUROLOGY_EXAMINATION_ID.LEFT_FOOT_VPT
]);

const RIGHT_ABNORMAL_VIBRATION_SENSE_FACTOR_ID_SET = new Set([
  MRAM_FEET_NEUROLOGY_EXAMINATION_ID.RIGHT_FOOT_128HZ_TUNING_FORK,
  MRAM_FEET_NEUROLOGY_EXAMINATION_ID.RIGHT_FOOT_GRADUATED_TUNING_FORK,
  MRAM_FEET_NEUROLOGY_EXAMINATION_ID.RIGHT_FOOT_VPT
]);

export {
  MRAM_FEET_NEUROLOGY_EXAMINATION_PREFIX,
  MRAM_FEET_FOOT_PATHOLOGY_PREFIX,
  MRAM_FEET_VASCULAR_ASSESSMENT_PREFIX,
  MRAM_FEET_OTHER_INFORMATION_PREFIX,
  MRAM_FEET_NEUROLOGY_EXAMINATION_ID,
  MRAM_FEET_FOOT_PATHOLOGY_ID,
  MRAM_FEET_VASCULAR_ASSESSMENT_ID,
  MRAM_FEET_OTHER_INFORMATION_ID,
  MRAM_FEET_ID_MAP,
  DL_MONOFILAMENT_TEST,
  DL_128HZ_TUNING_FORK,
  DL_ACHILLES_REFLEXES,
  RANGE_GRADUATED_TUNING_FORK,
  RANGE_VPT,
  RANGE_ANKLE_SYSTOLIC_BP,
  RANGE_BRACHIAL_SYSTOLIC_BP,
  RANGE_ABI,
  LEFT_ABNORMAL_VIBRATION_SENSE_FACTOR_ID_SET,
  RIGHT_ABNORMAL_VIBRATION_SENSE_FACTOR_ID_SET
};