const PRE = 'ATTENDANCE_CERTIFICATE';

export const GET_ATTENDANCE_CERT = `${PRE}_GET_ATTENDANCE_CERT`;

export const PUT_ATTENDANCE_CERT = `${PRE}_PUT_ATTENDANCE_CERT`;

export const UPDATE_FIELD = `${PRE}_UPDATE_FIELD`;

export const RESET_ALL = `${PRE}_RESET_ALL`;

export const LIST_ATTENDANCE_CERTIFICATES = `${PRE}_LIST_ATTENDANCE_CERTIFICATES`;
export const PUT_LIST_ATTENDANCE_CERTIFICATES = `${PRE}_PUT_LIST_ATTENDANCE_CERTIFICATES`;

export const UPDATE_ATTENDANCE_CERTIFICATE = `${PRE}_UPDATE_ATTENDANCE_CERTIFICATE`;

export const DELETE_ATTENDANCE_CERTIFICATE = `${PRE}_DELETE_ATTENDANCE_CERTIFICATE`;