const PREFFIX = 'DTS_ASSESSMENT';

//get
export const GET_ASSESSMENT_SAGA = `${PREFFIX}_GET_ASSESSMENT_SAGA`;

//set
export const ASSESSMENT_DATA = `${PREFFIX}_ASSESSMENT_DATA`;

//get
export const GET_ASSESSMENT_ENCNTR_SAGA = `${PREFFIX}_GET_ASSESSMENT_ENCNTR_SAGA`;

//set
export const ASSESSMENT_ENCNTR_DATA = `${PREFFIX}_ASSESSMENT_ENCNTR_DATA`;

//update
export const UPDATE_ASSESSMENT_SAGA = `${PREFFIX}_UPDATE_ASSESSMENT_SAGA`;

//set
export const UPDATE_ASSESSMENT_SAGA_RESULT = `${PREFFIX}_UPDATE_ASSESSMENT_SAGA_RESULT`;