const PREFFIX = 'DTS_ENCOUNTER';

//SET
export const SET_REDIRECT = `${PREFFIX}_SET_REDIRECT`;
export const SET_SELECTED_ENCOUNTER_TYPE = `${PREFFIX}_SET_SELECTED_ENCOUNTER_TYPE`;


//UPDATE
export const UPDATE_ENCOUNTER = `${PREFFIX}_UPDATE_ENCOUNTER`;
export const UPDATE_PRACTITIONER = `${PREFFIX}_UPDATE_PRACTITIONER`;
export const UPDATE_MEDICIAL_HISTORY_SNAPSHOT = `${PREFFIX}_UPDATE_MEDICIAL_HISTORY_SNAPSHOT`;


//get
export const GET_ENCOUNTER = `${PREFFIX}_GET_ENCOUNTER`;
export const GET_PRACTITIONER = `${PREFFIX}_GET_PRACTITIONER`;
export const GET_LATEST_ENCOUNTER = `${PREFFIX}_GET_LATEST_ENCOUNTER`;
export const GET_ROOM_LIST = `${PREFFIX}_GET_ROOM_LIST`;
export const GET_ENCOUNTER_TYPE_LIST = `${PREFFIX}_GET_ENCOUNTER_TYPE_LIST`;
export const GET_PATIENT_APPOINTMENT = `${PREFFIX}_GET_PATIENT_APPOINTMENT`;
export const GET_PROBLEM_AND_QUALIFER = `${PREFFIX}_GET_PROBLEM_AND_QUALIFER`;
export const GET_PROCEDURES_AND_QUALIFERS = `${PREFFIX}_GET_PROCEDURES_AND_QUALIFERS`;
export const GET_MEDICIAL_HISTORY_SNAPSHOT_BY_ENCOUNTER = `${PREFFIX}_GET_MEDICIAL_HISTORY_SNAPSHOT_BY_ENCOUNTER`;
export const GET_CARRY_FORWARD_DATA = `${PREFFIX}_GET_CARRY_FORWARD_DATA`;
export const GET_MEDICIAL_HISTORY_RFI = `${PREFFIX}_GET_MEDICIAL_HISTORY_RFI`;
export const GET_NOTES_AND_PROCEDURES = `${PREFFIX}_GET_NOTES_AND_PROCEDURES`;
export const GET_DOSEINSTRUCTION = `${PREFFIX}_GET_DOSEINSTRUCTION`;
export const GET_LOGIN_USERINFO = `${PREFFIX}GET_LOGIN_USERINFO`;

//get SAGA
export const GET_ENCOUNTER_SAGA = `${PREFFIX}_GET_ENCOUNTER_SAGA`;
export const GET_PRACTITIONER_SAGA = `${PREFFIX}_GET_PRACTITIONER_SAGA`;
export const GET_LATEST_ENCOUNTER_SAGA = `${PREFFIX}_GET_LATEST_ENCOUNTER_SAGA`;
export const GET_ROOM_LIST_SAGA = `${PREFFIX}_GET_ROOM_LIST_SAGA`;
export const GET_ENCOUNTER_TYPE_LIST_SAGA = `${PREFFIX}_GET_ENCOUNTER_TYPE_LIST_SAGA`;
export const GET_PATIENT_APPOINTMENT_SAGA = `${PREFFIX}_GET_PATIENT_APPOINTMENT_SAGA`;
export const GET_PROBLEM_AND_QUALIFER_SAGA = `${PREFFIX}_GET_PROBLEM_AND_QUALIFER_SAGA`;
export const GET_PROCEDURES_AND_QUALIFERS_SAGA = `${PREFFIX}_GET_PROCEDURES_AND_QUALIFERS_SAGA`;
export const GET_CARRY_FORWARD_DATA_SAGA = `${PREFFIX}_GET_CARRY_FORWARD_DATA_SAGA`;
export const GET_NOTES_AND_PROCEDURES_SAGA = `${PREFFIX}_GET_NOTES_AND_PROCEDURES_SAGA`;
export const GET_LOGIN_USERINFO_SAGA = `${PREFFIX}_GET_LOGIN_USERINFO_SAGA`;
//reset
export const RESET_ALL = `${PREFFIX}_RESET_ALL`;
export const RESET_DIRECT_ENCOUNTER_DIALOG = `${PREFFIX}RESET_DIRECT_ENCOUNTER_DIALOG`;


//INSERT
export const INSERT_ENCOUNTER = `${PREFFIX}_INSERT_ENCOUNTER`;
export const CREATE_MEDICIAL_HISTORY_SNAPSHOT = `${PREFFIX}_CREATE_MEDICIAL_HISTORY_SNAPSHOT`;
export const CREATE_MEDICIAL_HISTORY_RFI = `${PREFFIX}_CREATE_MEDICIAL_HISTORY_RFI`;