const PREFFIX = 'DTS_PERIO_CHART';

//set
export const SET_PERIOCHART_CALLBACK = `${PREFFIX}_SET_PERIOCHART_CALLBACK`;

//reset
export const RESET_PERIOCHART_CALLBACK = `${PREFFIX}_RESET_PERIOCHART_CALLBACK`;

//update
export const UPDATE_PERIOCHART_DATA_SAGA = `${PREFFIX}_UPDATE_PERIOCHART_DATA_SAGA`;

//data
export const PERIOCHART_DATA_COLLECTION = `${PREFFIX}_PERIOCHART_DATA_COLLECTION`;

//get
export const GET_PERIOCHART_DATA_COLLECTION_SAGA = `${PREFFIX}_GET_PERIOCHART_DATA_COLLECTION_SAGA`;

//set
export const SET_PERIOCHART_DATA_COLLECTION = `${PREFFIX}_SET_PERIOCHART_DATA_COLLECTION`;

//reset
export const RESET_PERIOCHART_DATA_COLLECTION = `${PREFFIX}_RESET_PERIOCHART_DATA_COLLECTION`;
