const PREFFIX = 'CLINICAL_CONTENT_PROBLEM_PROCEDURE';

export const GET_COMMON_USED_PROB_PROC = `${PREFFIX}_GET_COMMON_USED_PROB_PROC`;
export const GET_QUALIFER = `${PREFFIX}_GET_QUALIFER`;
export const GET_PROB_PROC_ADD_DETAILS = `${PREFFIX}_GET_PROB_PROC_ADD_DETAILS`;
export const UPDATE_STATE = `${PREFFIX}_UPDATE_STATE`;
export const UPDATE_QUALIFIER_STATE = `${PREFFIX}_UPDATE_QUALIFIER_STATE`;
export const UPDATE_PROB_PROC_ADD_DETAILS_STATE = `${PREFFIX}_UPDATE_PROB_PROC_ADD_DETAILS_STATE`;
export const UPDATE_SAVE_STATE = `${PREFFIX}_UPDATE_SAVE_STATE`;
export const RESET_SELECTED_VAL = `${PREFFIX}_RESET_SELECTED_VAL`;
export const RESET_ALL = `${PREFFIX}_RESET_ALL`;
export const SAVE_PROB_PROC = `${PREFFIX}_SAVE_PROB_PROC`;
export const DELETE_PROB_PROC = `${PREFFIX}_DELETE_PROB_PROC`;