const PREFFIX = 'DTS_PROCEDURE_SET';

//get
export const GET_PROCEDURE_COMMON_SET_SAGA = `${PREFFIX}_GET_PROCEDURE_COMMON_SET_SAGA`;

//set
export const PROCEDURE_COMMON_SET = `${PREFFIX}_PROCEDURE_COMMON_SET`;

//get
export const GET_PROCEDURE_SET_GROUP_SAGA = `${PREFFIX}_GET_PROCEDURE_SET_GROUP_SAGA`;

//set
export const PROCEDURE_SET_GROUP = `${PREFFIX}_PROCEDURE_SET_GROUP`;

//get
export const GET_PROCEDURE_QUALIFIER_SAGA = `${PREFFIX}_GET_PROCEDURE_QUALIFIER_SAGA`;

//set
export const PROCEDURE_QUALIFIER = `${PREFFIX}_PROCEDURE_QUALIFIER`;

//update
export const UPDATE_PROCEDURE_QUALIFIER_SAGA = `${PREFFIX}_UPDATE_PROCEDURE_QUALIFIER_SAGA`;

//set
export const UPDATE_PROCEDURE_QUALIFIER_RESULT = `${PREFFIX}_UPDATE_PROCEDURE_QUALIFIER_RESULT`;