const PREFFIX='changePasscode';

export const UPDATE_FIELD=`${PREFFIX}_UPDATE_FIELD`;
export const RESET_ALL=`${PREFFIX}_RESET_ALL`;
export const UPDATE_CANCEL=`${PREFFIX}_UPDATE_CANCEL`;
export const UPDATE_PASSCODE=`${PREFFIX}_UPDATE_PASSCODE`;
export const UPDATE_PASSCODE_SUCCESS=`${PREFFIX}_UPDATE_PASSCODE_SUCCESS`;
export const UPDATE_PASSCODE_ERROR=`${PREFFIX}_UPDATE_PASSCODE_ERROR`;