const MRAM_OTHERCOMPLICATIONS_PREFIX = 'otcp';

const MRAM_OTHERCOMPLICATIONS_ID = {
  CORONARY_HEART_DISEASE : '151',
  CONGESTIVE_HEART_FAILURE : '152',
  HX_OF_TUBERCULOSIS :'153',
  DIALYSIS :'154',
  RENAL_TRANSPLANT :'155',
  HX_OF_STROKE :'156',
  HX_OF_STROKE_HAEMORRHAGIC :'157',
  HX_OF_STROKE_ISCHAEMIC :'158',
  HX_OF_STROKE_UNKNOWN_TYPE :'159',
  MALIGNANCY :'160',
  MALIGNANCY_ACTIVE :'161',
  MALIGNANCY_PALLIATIVE :'162',
  MALIGNANCY_PAST_HX :'163',
  ERECTILE_DYSFUNCTION :'205',
  REMARKS :'207'
};

const MRAM_OTHERCOMPLICATIONS_ID_MAP = new Map([
  [MRAM_OTHERCOMPLICATIONS_PREFIX,MRAM_OTHERCOMPLICATIONS_ID]
]);

const RANGE_BEST_VISUAL_ACUITY = {
  minVal: 30,
  maxVal: 100
};


const RADIO_OPTION_1 = [
  {
    label:'Yes',
    value:'Yes'
  },{
    label:'No',
    value:'No'
  },{
    label:'Not known',
    value:'Not known'
  }
];

export {
  MRAM_OTHERCOMPLICATIONS_ID_MAP,
  MRAM_OTHERCOMPLICATIONS_PREFIX,
  MRAM_OTHERCOMPLICATIONS_ID,
  RANGE_BEST_VISUAL_ACUITY,
  RADIO_OPTION_1
};