export const PAGE_STATUS = {
    VIEWING: 'VIEWING',
    NONEDITABLE: 'NONEDITABLE',
    SEARCHING: 'SEARCHING',
    EDITING: 'EDITING',
    ADDING: 'ADDING'
};

export const USER_ROLE_TYLE={
    AVAILABLE:'AVAILABLE',
    SELECTED:'SELECTED'
};