const PRE = 'REFERRAL_LETTER_CERTIFICATE';

export const RESET_ALL = `${PRE}_RESET_ALL`;
export const UPDATE_FIELD = `${PRE}_UPDATE_FIELD`;
export const GET_REFERRAL_LETTER_CERT = `${PRE}_GET_REFERRAL_LETTERT_CERT`;

export const UPDATE_REFERRAL_LETTER = `${PRE}_UPDATE_REFERRAL_LETTER`;
export const DELETE_REFERRAL_LETTER = `${PRE}_DELETE_REFERRAL_LETTER`;

export const LIST_REFERRAL_LETTERS = `${PRE}_LIST_REFERRAL_LETTERS`;
export const PUT_LIST_REFERRAL_LETTERS = `${PRE}_PUT_LIST_REFERRAL_LETTERS`;

export const GET_PROBLEM_TEXT = `${PRE}_GET_PROBLEM_TEXT`;
export const GET_CLINICALNOTE_TEXT = `${PRE}_GET_CLINICALNOTE_TEXT`;
export const GET_DOSEINSTRUCTION = `${PRE}_GET_DOSEINSTRUCTION`;
export const GET_SAAM_PATIENT_SUMMARY = `${PRE}_GET_SAAM_PATIENT_SUMMARY`;