const PRE = 'TIMESLOT_MANAGEMENT_V2';

export const RESET = `${PRE}_RESET`;
export const UPDATE_STATE = `${PRE}_UPDATE_STATE`;
export const GET_TIMESLOT_PLAN_HDRS_V2 = `${PRE}_GET_TIMESLOT_PLAN_HDRS_V2`;
export const CREATE_TIMESLOT_PLAN_HDR_V2 = `${PRE}_CREATE_TIMESLOT_PLAN_HDR_V2`;
export const UPDATE_TIMESLOT_PLAN_HDR_V2 = `${PRE}_UPDATE_TIMESLOT_PLAN_HDR_V2`;
export const DELETE_TIMELSOT_PLAN_HDR_V2 = `${PRE}_DELETE_TIMELSOT_PLAN_HDR_V2`;

export const GET_TIMESLOT_PLANS_V2 = `${PRE}_GET_TIMESLOT_PLANS_V2`;
export const CREATE_TIMESLOT_PLAN_V2 = `${PRE}_CREATE_TIMESLOT_PLAN_V2`;

export const MULTIPLE_UPDATE_TIMESLOT_V2 = `${PRE}_MULTIPLE_UPDATE_TIMESLOT_V2`;

export const GET_PREDEFINED_TIMESLOTS = `${PRE}_GET_PREDEFINED_TIMESLOTS`;

export const GET_TIMESLOTS = `${PRE}_GET_TIMESLOTS`;