const ENCOUNNTER_STATUS = {
  SAVE: 'I',
  PENDING: 'P',
  COMPLETE: 'C'
};

const MS_CODE_ENCOUNTER_RFI = {
  SMOKING: '1',
  PAST_MEDICAL_HISTORY: '4',
  ADVERSE_REACTION_ALLERGY_ALERT:'6'
};

const CLINICAL_NOTE_TYPE = {
  DOCTOR_NOTE: 1,
  ADDITIONAL_NOTE: 12
};

export {ENCOUNNTER_STATUS, MS_CODE_ENCOUNTER_RFI, CLINICAL_NOTE_TYPE};

