const PRE = 'MEDICAL_HISTORIES';

// Occupational History
export const GET_OCCUPATIONAL_HISTORY_LIST = `${PRE}_GET_OCCUPATIONAL_HISTORY_LIST`;
export const GET_OCCUPATIONAL_LOG_LIST = `${PRE}_GET_OCCUPATIONAL_LOG_LIST`;
export const GET_OCCUPATIONAL_OTHERS_LOG_LIST = `${PRE}_GET_OCCUPATIONAL_OTHERS_LOG_LIST`;

// Social History
export const GET_SOCIAL_DROPDOWN_LSIT = `${PRE}_GET_SOCIAL_DROPDOWN_LSIT`;
export const SET_SOCIAL_DROPDOWN_LSIT = `${PRE}_SET_SOCIAL_DROPDOWN_LSIT`;
export const GET_SOCIAL_HISTORY_LIST = `${PRE}_GET_SOCIAL_HISTORY_LIST`;
export const GET_SOCIAL_HISTORY_COMMON_LOG_LIST = `${PRE}_GET_SOCIAL_HISTORY_COMMON_LOG_LIST`;
export const GET_SOCIAL_HISTORY_PASSIVE_SMOKING_INFORMATION_LOG_LIST = `${PRE}_GET_SOCIAL_HISTORY_PASSIVE_SMOKING_INFORMATION_LOG_LIST`;

// export const GET_SOCIAL_HISTORY_SMOKING_LOG_LIST = `${PRE}_GET_SOCIAL_HISTORY_SMOKING_LOG_LIST`;
// export const GET_SOCIAL_HISTORY_DRINKING_LOG_LIST = `${PRE}_GET_SOCIAL_HISTORY_DRINKING_LOG_LIST`;
// export const GET_SOCIAL_HISTORY_SUBSTANCE_ABUSE_LOG_LIST = `${PRE}_GET_SOCIAL_HISTORY_SUBSTANCE_ABUSE_LOG_LIST`;
export const GET_SOCIAL_HISTORY_OTHERS_LOG_LIST = `${PRE}_GET_SOCIAL_HISTORY_OTHERS_LOG_LIST`;

// Past Medical History
export const GET_PAST_TERMINOLOGY_SERVICE_LIST = `${PRE}_GET_PAST_TERMINOLOGY_SERVICE_LIST`;
export const FUZZY_QUERY_PROBLEM_LIST = `${PRE}_FUZZY_QUERY_PROBLEM_LIST`;
export const GET_PAST_HISTORY_PROBLEM_DETAIL_LOG_LIST = `${PRE}_GET_PAST_HISTORY_PROBLEM_DETAIL_LOG_LIST`;
export const GET_PAST_HISTORY_LIST = `${PRE}_GET_PAST_HISTORY_LIST`;

// Family History
export const GET_FAMILY_HISTORY_LIST = `${PRE}_GET_FAMILY_HISTORY_LIST`;
export const GET_FAMILY_TERMINOLOGY_SERVICE_LIST = `${PRE}_GET_FAMILY_TERMINOLOGY_SERVICE_LIST`;
export const GET_FAMILY_RELATIONSHIP_LIST = `${PRE}_GET_FAMILY_RELATIONSHIP_LIST`;
export const GET_FAMILY_HISTORY_PROBLEM_DETAIL_LOG_LIST = `${PRE}_GET_FAMILY_HISTORY_PROBLEM_DETAIL_LOG_LIST`;
export const GET_FAMILY_HISTORY_OTHERS_LOG_LIST = `${PRE}_GET_FAMILY_HISTORY_OTHERS_LOG_LIST`;

// Common
export const SAVE_MEDICAL_HISTORY = `${PRE}_SAVE_MEDICAL_HISTORY`;
export const SAVE_FAMILY_HISTORY = `${PRE}_SAVE_FAMILY_HISTORY`;
export const SAVE_SOCIAL_HISTORY = `${PRE}_SAVE_SOCIAL_HISTORY`;
export const SAVE_PAST_MEDICAL_HISTORY = `${PRE}_SAVE_PAST_MEDICAL_HISTORY`;
export const SAVE_MEDICAL_HISTORY_ACTIVE_TAB = `${PRE}_SAVE_MEDICAL_HISTORY_ACTIVE_TAB`;