const PREFFIX = 'IOE_FORM_NAME';

export const IOE_FORM_NAME_LIST = `${PREFFIX}_IOE_FORM_NAME_LIST`;
export const FILLING_FORM_NAME_LIST=`${PREFFIX}_FILLING_FORM_NAME_LIST`;

export const IOE_REQUESTED_BY = `${PREFFIX}_IOE_REQUESTED_BY`;
export const FILLING_REQUESTED_BY=`${PREFFIX}_FILLING_REQUESTED_BY`;