const PREFFIX = 'JOS_PROBLEMTEMPLATE_VIEW';
export const PROBLEM_REQUEST_DATA=`${PREFFIX}_PROBLEM_REQUEST_DATA`;
export const PROBLEM_LIST_DATA=`${PREFFIX}_PROBLEM_LIST_DATA`;

export const SAVE_PROBLE_DATA=`${PREFFIX}_SAVE_PROBLE_DATA`;
export const SAVE_PROBLEM_RESULT=`${PREFFIX}_SAVE_PROBLEM_RESULT`;
export const SAVE_PROBLEM_TEMPLATE_DATA=`${PREFFIX}_SAVE_PROBLEM_TEMPLATE_DATA`;

export const GET_EDITTEMPLATELIST_DATA=`${PREFFIX}_GET_EDITTEMPLATELIST_DATA`;

export const GET_INPUT_PROBLEM_LIST = `${PREFFIX}_GET_INPUT_PROBBLEM_LIST`;
export const INPUT_PROBLEM_LIST = `${PREFFIX}_INPUT_PROBBLEM_LIST`;
export const GET_PROBLEM_STATUS= `${PREFFIX}_GET_PROBLEM_STATUS`;

export const UPDATE_PATIENT_PROBLEM= `${PREFFIX}_UPDATE_PATIENT_PROBLEM`;
export const DELETE_PATIENT_PROBLEM= `${PREFFIX}_DELETE_PATIENT_PROBLEM`;

export const PROBLEM_SEARCH_LIST_RESULT= `${PREFFIX}_PROBLEM_SEARCH_LIST_RESULT`;
export const GET_DIAGNOSIS_RECORD_TYPE= `${PREFFIX}_GET_DIAGNOSIS_RECORD_TYPE`;
export const PUT_DIAGNOSIS_RECORD_TYPE= `${PREFFIX}_PUT_DIAGNOSIS_RECORD_TYPE`;

export const GET_PROBLEM_SEARCH_LIST_NO_PAGINATION= `${PREFFIX}_GET_PROBLEM_SEARCH_LIST_NO_PAGINATION`;
export const PROBLEM_SEARCH_LIST_NO_PAGINATION_RESULT= `${PREFFIX}_PROBLEM_SEARCH_LIST_NO_PAGINATION_RESULT`;

export const QUERY_PROBLEM_LIST= `${PREFFIX}_QUERY_PROBLEM_LIST`;
export const GET_HISTORICAL_RECORD_LIST= `${PREFFIX}_GET_HISTORICAL_RECORD_LIST`;
export const PUT_HISTORICAL_RECORD_LIST= `${PREFFIX}_PUT_HISTORICAL_RECORD_LIST`;
export const SAVE_PATIENT_INFORMATION=`${PREFFIX}_SAVE_PATIENT_INFORMATION`;

export const GET_CHRONIC_PROBLEM_LIST= `${PREFFIX}_GET_CHRONIC_PROBLEM_LIST`;
export const CHRONIC_PROBLEM_LIST= `${PREFFIX}_CHRONIC_PROBLEM_LIST`;

export const GET_CODE_LOCAL_TERM_STATUS= `${PREFFIX}GET_CODE_LOCAL_TERM_STATUS`;
export const GET_ALL_DXPX_LIST = `${PREFFIX}_GET_ALL_DXPX_LIST`;

export const ADD_PSORIASIS = `${PREFFIX}_ADD_PSORIASIS`;
export const GET_CURRENT_DATE = `${PREFFIX}_GET_CURRENT_DATE`;
