const PRE = 'IOE_SPECIMEN_COLLECTION';

export const GET_IOE_SPECIMEN_COLLECTION_LIST = `${PRE}_GET_IOE_SPECIMEN_COLLECTION_LIST`;
export const IOE_SPECIMEN_COLLECTION_LIST = `${PRE}_IOE_SPECIMEN_COLLECTION_LIST`;
export const SAVE_IOE_SPECIMEN_COLLECTION_LIST=`${PRE}_SAVE_IOE_SPECIMEN_COLLECTION_LIST`;
export const GET_IOE_SPECIMEN_COLLECTION_TEMPLS_FOR_REPORT=`${PRE}_GET_IOE_SPECIMEN_COLLECTION_TEMPLS_FOR_REPORT`;
export const PRINT_IOE_SPECIMEN_COLLECTION_REMINDER_REPORT=`${PRE}_PRINT_IOE_SPECIMEN_COLLECTION_REMINDER_REPORT`;
