const PREFFIX = 'APPOINTMENT_EDITTIMESLOT';
export const RESET_ALL = `${PREFFIX}_RESET_ALL`;
export const UPDATE_STATE = `${PREFFIX}_UPDATE_STATE`;
export const LIST_TIME_SLOT = `${PREFFIX}_LIST_TIME_SLOT`;
export const INSERT_TIME_SLOT = `${PREFFIX}_INSERT_TIME_SLOT`;
export const UPDATE_TIME_SLOT = `${PREFFIX}_UPDATE_TIME_SLOT`;
export const DELETE_TIME_SLOT = `${PREFFIX}_DELETE_TIME_SLOT`;
export const MULTIPLE_UPDATE = `${PREFFIX}_MULTIPLE_UPDATE`;

//saga put
export const INIT_CODE_LIST = `${PREFFIX}_INIT_CODE_LIST`;
export const PUT_LIST_TIME_SLOT = `${PREFFIX}_PUT_LIST_TIME_SLOT`;
export const PUT_MULTIPLE_UPDATE = `${PREFFIX}_PUT_MULTIPLE_UPDATE`;