const PRE = 'APPOINTMENT_BOOKING_ANONYMOUS';
export const RESET_INFO_ALL = `${PRE}_RESET_INFO_ALL`;
export const APPOINTMENT_BOOK = `${PRE}_APPOINTMENT_BOOK`;
export const LIST_TIMESLOT = `${PRE}_LIST_TIMESLOT`;
export const INIT_ANON_BOOKING_DATA = `${PRE}_INIT_ANON_BOOKING_DATA`;
export const BOOK_CONFIRM = `${PRE}_BOOK_CONFIRM`;
export const BOOK_CONFIRM_WAITING = `${PRE}_BOOK_CONFIRM_WAITING`;
export const UPDATE_STATE = `${PRE}_UPDATE_STATE`;
export const GET_APPOINTMENT_REPORT = `${PRE}_GET_APPOINTMENT_REPORT`;
export const UPDATE_ANONYMOUS_APPOINTMENT = `${PRE}_UPDATE_ANONYMOUS_APPOINTMENT`;
export const CANCEL_CONFIRM_ANONYMOUS_APPOINTMENT = `${PRE}_CANCEL_CONFIRM_ANONYMOUS_APPOINTMENT`;
// This Check the some rule (e.g : Same Day, Duplicate Booking)
export const CHECK_BOOKING_RULE = `${PRE}_CHECK_BOOKING_RULE`;
// Open the Replace Appointment
export const OPEN_REPLACE_APPOINTMENT = `${PRE}_OPEN_REPLACE_APPOINTMENT`;
export const RESET_REPLACE_APPOINTMENT = `${PRE}_RESET_REPLACE_APPOINTMENT`;
export const STILL_APPOINTMENTS_BOOK_CONFIRM = `${PRE}_STILL_APPOINTMENTS_BOOK_CONFIRM`;
export const REPLACE_OLD_APPOINTMNET_BOOK_CONFIRM = `${PRE}_REPLACE_OLD_APPOINTMNET_BOOK_CONFIRM`;
export const REDESIGN_PUT_BOOK_SUCCESS = `${PRE}_REDESIGN_PUT_BOOK_SUCCESS`;

//saga put
export const PUT_LIST_TIMESLOT_DATA = `${PRE}_PUT_LIST_TIMESLOT_DATA`;
export const PUT_TIMESLOT_DATA = `${PRE}_PUT_TIMESLOT_DATA`;
export const PUT_BOOK_SUCCESS = `${PRE}_PUT_BOOK_SUCCESS`;
export const PUT_GET_CODE_LIST = `${PRE}_PUT_GET_CODE_LIST`;

export const PUT_URG_SQUEEZE = `${PRE}_PUT_URG_SQUEEZE`;
export const PUT_SQUEEZE = `${PRE}_PUT_SQUEEZE`;
export const RESET_SQUEEZE = `${PRE}_RESET_SQUEEZE`;

//remark code list
export const LIST_REMARK_CODE = `${PRE}_LIST_REMARK_CODE`;
export const PUT_LIST_REMARK_CODE = `${PRE}_PUT_LIST_REMARK_CODE`;

export const SEARCH_PATIENT_LIST = `${PRE}_SEARCH_PATIENT_LIST`;
export const PUT_SEARCH_PATIENT_LIST=`${PRE}_PUT_SEARCH_PATIENT_LIST`;
export const UPDATE_FIELD=`${PRE}_UPDATE_FIELD`;

//re anonymous appointment
export const RE_ANONYMOUS_APPOINTMNET=`${PRE}_RE_ANONYMOUS_APPOINTMNET`;

//delete anonymous appointment
export const DELETE_ANONYMOUS_APPOINTMENT = `${PRE}_DELETE_ANONYMOUS_APPOINTMENT`;

//update site
export const GET_ENCOUNTER_TYPE_LIST_BY_SITE = `${PRE}_GET_ENCOUNTER_TYPE_LIST_BY_SITE`;
export const PUT_ENCOUNTER_TYPE_LIST_BY_SITE = `${PRE}_PUT_ENCOUNTER_TYPE_LIST_BY_SITE`;

//get anonymous sessions list
export const GET_ANONYMOUS_SESSIONSLIST  = `${PRE}_GET_ANONYMOUS_SESSIONSLIST`;