const PREFFIX = 'REDESIGN_APPOINTMENT_BOOKING_CALENDAR_VIEW';

export const RESET_INFO_ALL = `${PREFFIX}_RESET_INFO_ALL`;

export const REDESIGN_LIST_APPOINTMENT = `${PREFFIX}_REDESIGN_LIST_APPOINTMENT`;
export const REDESIGN_PUT_LIST_APPOINTMENT_DATA = `${PREFFIX}_REDESIGN_PUT_LIST_APPOINTMENT_DATA`;

export const REDESIGN_BOOK_CONFIRM = `${PREFFIX}_BOOK_CONFIRM`;

export const REDESIGN_LIST_REMARK_CODE = `${PREFFIX}_LIST_REMARK_CODE`;
export const REDESIGN_PUT_LIST_REMARK_CODE = `${PREFFIX}_PUT_LIST_REMARK_CODE`;


export const REDESIGN_PUT_BOOKING_DATA = `${PREFFIX}_REDESIGN_PUT_BOOKING_DATA`;

export const REDESIGN_PUT_BOOK_SUCCESS = `${PREFFIX}_REDESIGN_PUT_BOOK_SUCCESS`;



