const PRE = 'GSC';
export const GET_GSC_ENQUIRY = `${PRE}_GET_GSC_ENQUIRY`;
export const SAVE_GSC_ENQUIRY = `${PRE}_SAVE_GSC_ENQUIRY`;
export const GET_GSC_ENQUIRY_REPORT = `${PRE}_GET_GSC_ENQUIRY_REPORT`;
export const SAVE_GSC_ENQUIRY_REPORT = `${PRE}_SAVE_GSC_ENQUIRY_REPORT`;
export const GET_GSC_ENQUIRY_SELECT = `${PRE}_GET_GSC_ENQUIRY_SELECT`;
export const PRINT_CHT_GSPD_REPORT = `${PRE}_PRINT_CHT_GSPD_REPORT`;
export const SAVE_GSC_CLINICAL_DOC = `${PRE}_SAVE_GSC_CLINICAL_DOC`;
export const GET_CLINICAL_DOC_LOAD = `${PRE}_GET_CLINICAL_DOC_LOAD`;
export const GET_GSC_LAB_REPORT_PDF = `${PRE}_GET_GSC_LAB_REPORT_PDF`;
export const GET_GSC_LAB_REPORT_PATIENTKEY = `${PRE}_GET_GSC_LAB_REPORT_PATIENTKEY`;
export const SAVE_GSC_LAB_REPORT = `${PRE}_SAVE_GSC_LAB_REPORT`;
export const SAVE_GSC_LAB_REPORT_CREATE = `${PRE}_SAVE_GSC_LAB_REPORT_CREATE`;
export const GSC_ENQUIRY_SAVE_VIEW_LOG=`${PRE}_SAVE_VIEW_LOG`;
export const GET_GSC_REFERRAL_LETTER=`${PRE}_GET_GSC_REFERRAL_LETTER`;
export const SAVE_GSC_REFERRAL_LETTER=`${PRE}_SAVE_GSC_REFERRAL_LETTER`;
export const GET_GSC_HOSPITAL_LIST = `${PRE}_GET_GSC_HOSPITAL_LIST`;

// get print data
export const GET_GSC_REFERRAL_LETTER_PRINT_DATA = `${PRE}_GET_GSC_REFERRAL_LETTER_PRINT_DATA`;