const PRE = 'UNAVAILABLE_PERIOD_MANAGEMENT';

export const RESET_ALL = `${PRE}_RESET_ALL`;
export const UPDATE_STATE = `${PRE}_UPDATE_STATE`;
export const GET_UPMLIST = `${PRE}_GET_UPMLIST`;
export const PUT_UPMLIST = `${PRE}_PUT_UPMLIST`;
export const INSERT_UPM = `${PRE}_INSERT_UPM`;
export const UPDATE_UPM = `${PRE}_UPDATE_UPM`;
export const RESET_DIALOGINFO =`${PRE}_RESET_DIALOGINFO`;
export const DELETE_UPM = `${PRE}_DELETE_UPM`;
export const GET_UNAVAILABLEREASONS = `${PRE}_GET_UNAVAILABLEREASONS`;
export const PUT_UNAVAILABLEREASONS = `${PRE}_PUT_UNAVAILABLEREASONS`;