const PREFFIX='changePassword';

export const UPDATE_FIELD=`${PREFFIX}_UPDATE_FIELD`;
export const RESET_ALL=`${PREFFIX}_RESET_ALL`;
export const UPDATE_CANCEL=`${PREFFIX}_UPDATE_CANCEL`;
export const UPDATE_PASSWORD=`${PREFFIX}_UPDATE_PASSWORD`;
export const UPDATE_PASSWORD_SUCCESS=`${PREFFIX}_UPDATE_PASSWORD_SUCCESS`;
export const UPDATE_PASSWORD_ERROR=`${PREFFIX}_UPDATE_PASSWORD_ERROR`;
export const CHECK_CURRENT_PASSWORD=`${PREFFIX}_CHECK_CURRENT_PASSWORD`;