const PRE='WAITING_LIST';

export const INITI_PAGE=`${PRE}_INITI_PAGE`;
export const SEARCH_WAITING_LIST=`${PRE}_SEARCH_WAITING_LIST`;
export const GET_WAITING=`${PRE}_GET_WAITING`;
export const UPDATE_FIELD=`${PRE}_UPDATE_FIELD`;
export const CANCEL_SEARCH=`${PRE}_CANCEL_SEARCH`;
export const ADD_WAITING=`${PRE}_ADD_WAITING`;
export const EDIT_WAITING=`${PRE}_EDIT_WAITING`;
export const CANCEL_EDIT_WAITING=`${PRE}_CANCEL_EDIT_WAITING`;
export const UPDATE_WAITING_FIELD=`${PRE}_UPDATE_WAITING_FIELD`;
export const SEARCH_PATIENT_LIST=`${PRE}_SEARCH_PATIENT_LIST`;
export const PUT_SEARCH_PATIENT_LIST=`${PRE}_PUT_SEARCH_PATIENT_LIST`;
export const GET_PATIENT_BY_ID=`${PRE}_GET_PATIENT_BY_ID`;
export const SAVE_WAITING = `${PRE}_SAVE_WAITING`;
export const SAVE_SUCCESS = `${PRE}_SAVE_SUCCESS`;
export const DELETE_WAITING = `${PRE}_DELETE_WAITING`;
export const DELETE_SUCCESS = `${PRE}_DELETE_SUCCESS`;
export const RESET_WAIT_DETAIL=`${PRE}_RESET_WAIT_DETAIL`;
export const WAITINGLIST_ALLROLE_LISTCONFIG = `${PRE}_WAITINGLIST_ALLROLE_LISTCONFIG`;

export const RESET_ALL=`${PRE}_RESET_ALL`;

