const PREFFIX='prescription';
export const  SEARCH_DRUG=`${PREFFIX}_SEARCH_DRUG`;
export const SEARCH_DRUG_LIST=`${PREFFIX}_SEARCH_DRUG_LIST`;
export const SEARCH_ITEM_COLLAPSE=`${PREFFIX}_SEARCH_ITEM_COLLAPSE`;
export const GET_DRUG=`${PREFFIX}_GET_DRUG`;
export const GRUG_RESPONSE=`${PREFFIX}_GRUG_RESPONSE`;
export const GET_CODE_LIST=`${PREFFIX}_GET_CODE_LIST`;
export const CODE_LIST=`${PREFFIX}_CODE_LIST`;
export const DELETE_DRUG=`${PREFFIX}_DELETE_DRUG`;
export const RESET_DRUG_LIST=`${PREFFIX}_RESET_DRUG_LIST`;
export const UPDATE_FIELD=`${PREFFIX}_UPDATE_FIELD`;

