const PREFFIX = 'JOS_TAGANOTE_VIEW';

export const GET_TAG_A_NOTE_TYPES=`${PREFFIX}_GET_TAG_A_NOTE_TYPES`;
export const GET_TAG_A_NOTE_HISTORY_LIST=`${PREFFIX}_GET_TAG_A_NOTE_HISTORY_LIST`;

export const GET_TAG_A_NOTE_BY_ID=`${PREFFIX}_GET_TAG_A_NOTE_BY_ID`;
export const SAVE_A_NEW_TAG_NOTE=`${PREFFIX}_SAVE_A_NEW_TAG_NOTE`;
export const SAVE_A_TAG_NOTE_AGAIN=`${PREFFIX}_SAVE_A_TAG_NOTE_AGAIN`;

export const GET_NOTE_LOG_BY_TAG_A_NOTE_ID=`${PREFFIX}_GET_NOTE_LOG_BY_TAG_A_NOTE_ID`;

export const GET_TEMPLATE_DATA_LIST=`${PREFFIX}_GET_TEMPLATE_DATA_LIST`;

 export const SAVE_AND_PRINT_TAG_A_NOTE = `${PREFFIX}_SAVE_AND_PRINT_TAG_A_NOTE`;

 export const PRINT_TAG_A_NOTE = `${PREFFIX}_PRINT_TAG_A_NOTE`;

// export const SYS_CONFIG = `${PREFFIX}_SYS_CONFIG`;
// export const GET_COPY_DATA=`${PREFFIX}_GET_COPY_DATA`;
// export const GET_NOTE_HISTORY_LIST=`${PREFFIX}_GET_NOTE_HISTORY_LIST`;
// export const GET_NOTE_BY_ENCOUNTER=`${PREFFIX}_GET_NOTE_BY_ENCOUNTER`;
// export const PUT_CURRENT_NOTE_INFO=`${PREFFIX}_PUT_CURRENT_NOTE_INFO`;
// export const PUT_PAST_NOTE_INFO=`${PREFFIX}_PUT_PAST_NOTE_INFO`;
// export const GET_NOTE_LOG_BY_CLINICAL_NOTE_ID=`${PREFFIX}_GET_NOTE_LOG_BY_CLINICAL_NOTE_ID`;
// export const SAVE_TAGA_NOTE=`${PREFFIX}_SAVE_TAGA_NOTE`;