export const codeList = {
    gender: 'gender',
    exact_date_of_birth: 'exact_dob',
    service: 'service',
    clinic: 'clinic',
    district: 'district',
    sub_district: 'sub_district',
    document_type: 'doc_type',
    edu_level: 'edu_level',
    ethnicity: 'ethnicity',
    gov_department: 'gov_dpt',
    marital_status: 'marital_status',
    occupation: 'occupation',
    country_code: 'country',
    relationship: 'relationship',
    religion: 'religion',
    translation_lang: 'translation_lang',
    birth_place: 'birth_place',
    patient_status: 'patient_status',
    waiver:'waiver',
    edu_catgry:'edu_catgry',
    hlth_edu_type:'hlth_edu_type',
    puc_reason: 'puc_reason',
    default_trace_reason:'default_trace_reason',
    spp_dflt_trc_cntct_detl:'spp_dflt_trc_cntct_detl',
    cgs_rfr_inst: 'cgs_rfr_inst',
    cgs_rfr_dept: 'cgs_rfr_dept',
    cgs_rfr_title: 'cgs_rfr_title',
    cgs_inpatient_cnslt_loc_cd: 'cgs_inpatient_cnslt_loc_cd',   //CGS - Inpatient Consultation Location

    //moe
    freq_code: 'freq_code',
    route: 'route',
    duration_unit: 'duration_unit',
    duration_unit_map: 'duration_unit_map',
    base_unit: 'base_unit',
    action_status: 'action_status',
    site: 'site',
    regimen_type: 'regimen_type',
    system_setting: 'system_setting',
    form_route_map: 'form_route_map',

    //ehs
    ehs_waiver_catgry: 'ehs_waiver_catgry'
};