const doCloseFuncSrc = {
    CLOSE_BY_MAIN_TAB_CLOSE_BUTTON: '01',
    CLOSE_BY_PATIENT_SPEC_TAB_CLOSE_BUTTON: '02',
    CLOSE_BY_LOGOUT: '03',
    CLOSE_BY_CLOSE_BATCH_CLOSE: '99',
    CLOSE_BY_NEXT_PATIENT_BUTTON: 'NP',
    CLOSE_ALL_PATIENT_RELATE_TABS: '04',
    CLOSE_BY_CALENDAR_VIEW_CHANGE_PATIENT: '05',
    CLOSE_BY_HANDLE_BEFORE_OPEN_PATIENT_PANEL: '06',
    CLOSE_BY_EHS_WAITING_LIST: '07'
};

export default doCloseFuncSrc;
