const PROCEDURE_MODE = 'procedure';
const DEFAULT_PROCEDURE_SAVE_STATUS = 'C';
const PROCEDURE_SEARCH_LIST_TYPE = '2';
const PROCEDURE_SEARCH_PROBLEM='Service Favourite';
const PROCEDURE__SEARCH_PLACEHOLDER='Search procedure by type';
const ACTION_TYPE = {
  INSERT: 'I',
  UPDATE: 'U',
  DELETE: 'D'
};
const NEW_STATUS = {
  YES: 'Y',
  NO: 'N'
};

export { PROCEDURE_MODE, DEFAULT_PROCEDURE_SAVE_STATUS,PROCEDURE_SEARCH_LIST_TYPE,PROCEDURE_SEARCH_PROBLEM,PROCEDURE__SEARCH_PLACEHOLDER,ACTION_TYPE,NEW_STATUS};
