const COMMON_SYS_CONFIG_KEY = {
  PAGE_SIZE:'PAGE_SIZE',
  TMPL_NAME_LEN:'TMPL_NAME_LEN',
  TMPL_TIPS_SIZE:'TMPL_TIPS_SIZE'
};

const DEFAULT_OFFLINE_PAGE_SIZE = 30;

const COMMON_OPERATION = {
  ADD: 'Add',
  EDIT: 'Edit',
  DELETE: 'Delete',
  UP: 'Move up',
  DOWN: 'Move down'
};

const COMMON_ACTION_TYPE = {
  INSERT: 'I',
  UPDATE: 'U',
  DELETE: 'D'
};

const COMMON_CHECKBOX_TYPE = {
  CHECKED: 1,
  UNCHECKED: 0
};

const MAX_DATE = '2100-01-01';
const MIN_DATE = '1900-01-01';

const INSERT_LOG_STATUS ={
  Save:'Save',
  Click:'Click',
  Select:'Select',
  Unselect:'Unselect',
  Load:'Load',
  Up:'Up',
  Down:'Down',
  Delete:'Delete',
  Copy:'Copy',
  Drop:'Drop',
  Cancel:'Cancel',
  Open:'Open',
  Clear:'Clear',
  Search:'Search'
};

const INSERT_LOG_ACTION = {
  Action: 'Action: '
};

const NULLABLE_STATUS = {
  ALLOW_NULL: 'Y',
  NOT_ALLOW_NULL: 'N'
};

const COMMON_MESSAGE = {
  CONCURRENT_CODE: '100107',
  CONCURRENT_DELETE_CODE: '100111',
  SAVE_REPEAT_DATE_TIME_CODE: '101425'
};

const COMMON_DECRIPTION = {
  TMPLATE_REPEAT: 'This template name already exists. Please use another one.'
};

const COMMON_CODE = {
  SPECIMEN_COLLECTION_OUTPUT_FORM_FUNCTION_CODE: 'DCOFSC',
  SPECIMEN_COLLECTION_REMINDER_FUNCTION_CODE: 'DCRSC',
  SPECIMEN_COLLECTION_LABEL_FUNCTION_CODE: 'DCLSC',
  SPECIMEN_COLLECTION_DATE_CHECKBOX_CODE: 'DUCSCDTSC',
  _OUTPUT_FORM_FUNCTION_CODE: 'DCOFIE',
  IX_ENQUIRY_REMINDER_FUNCTION_CODE: 'DCRIE',
  IX_ENQUIRY_LABEL_FUNCTION_CODE: 'DCLIE',
  IX_ENQUIRY_DATE_CHECKBOX_CODE: 'DUCSCDTIE',
  IX_REQUEST_OUTPUT_FORM_FUNCTION_CODE: 'DCOFIX',
  IX_REQUEST_REMINDER_FUNCTION_CODE: 'DCRIX',
  IX_REQUEST_LABEL_FUNCTION_CODE: 'DCLIX',
  IX_REQUEST_DISABLE_SUBMIT_FUNCTION_CODE: 'DDSIX',
  IX_REQUEST_FOP_TEMPLATE_IS_ACTIVE_FUNCTION_CODE: 'ANTFOP',
  IX_REQUEST_FOP_TEMPLATE_NAME: 'FOP',
  IX_REQUEST_DATE_CHECKBOX_CODE: 'DUCSCDTIX',
  ANT_SERVICE_ID_CODE:'ANTANSVCID',
  ANT_GBS_CODE:'ANTGBS',
  ANT_GBS_NAME:'GBS',
  ANT_ZIKA_CODE:'ANTZIKA',
  ANT_ZIKA__NAME:'ZIKA',
  ANT_LFT_CODE:'ANTLFT',
  ANT_LFT_NAME:'LFT',
  SHS_EXPRESS_IOE_CHECKED:'EXIOE',
  SPECIFIC_REMARK_POP_UP_FOR_IOE_ENQUIRY:'SRPUIE',
  DEFAULT_NSL_AS_LANDING_PAGE_OF_IX_REQUEST_CODE:'DNSLLPIX'
};


export {
  MAX_DATE,
  MIN_DATE,
  COMMON_SYS_CONFIG_KEY,
  DEFAULT_OFFLINE_PAGE_SIZE,
  COMMON_ACTION_TYPE,
  COMMON_OPERATION,
  COMMON_CHECKBOX_TYPE,
  INSERT_LOG_STATUS,
  NULLABLE_STATUS,
  COMMON_MESSAGE,
  COMMON_DECRIPTION,
  INSERT_LOG_ACTION,
  COMMON_CODE
};