const abbreviations =
  [{ 'abb' : 'Abn','desc' : 'Abnormal'},
  { 'abb' : 'AP','desc' : 'Angina Pectoris'},
  { 'abb' : 'ASA','desc' : 'Anti-Smoking Advice'},
  { 'abb' : 'BPE','desc' : 'Basic Periodontal Examination'},
  { 'abb' : 'CHX','desc' : 'Chlorhexidine'},
  { 'abb' : 'Chemo','desc' : 'Chemotherapy'},
  { 'abb' : 'c/o F/ M/ S','desc' : 'care of Father/ Mother/ Spouse'},
  { 'abb' : 'CRHD','desc' : 'Chronic Rheumatic Heart Disease'},
  { 'abb' : 'DA dv','desc' : 'Dietary Advice'},
  { 'abb' : 'DI','desc' : 'Disease Information'},
  { 'abb' : 'DM','desc' : 'Diabetes Mellitus'},
  { 'abb' : 'DMFT','desc' : 'Decayed Missing Filled Permanent Teeth Due to Caries'},
  { 'abb' : 'F','desc' : 'Fluoride or Filling'},
  { 'abb' : 'FLS','desc' : 'Floss'},
  { 'abb' : 'FS','desc' : 'Fissure Sealant'},
  { 'abb' : 'Hx','desc' : 'History'},
  { 'abb' : 'ID','desc' : 'Inter-dental'},
  { 'abb' : 'ID B','desc' : 'Inter-dental Brush'},
  { 'abb' : 'IE','desc' : 'Infective Endocarditis'},
  { 'abb' : 'IHD','desc' : 'Ischemic Heart Disease'},
  { 'abb' : 'MI','desc' : 'Myocardial Infarction'},
  { 'abb' : 'NC','desc' : 'New Consultation'},
  { 'abb' : 'Pros HV','desc' : 'Prosthetic Heart Valve'},
  { 'abb' : 'RT','desc' : 'Radiotherapy'},
  { 'abb' : 'STD','desc' : 'Sexually Transmitted Disease'},
  { 'abb' : 'TB','desc' : 'Tuberculosis'},
  { 'abb' : 'Tx','desc' : 'Treatment'}];

export {  abbreviations };
