const probProcMap = [
  {
    pname: 'Endo',
    probDetail: [
      'Irreversible pulpitis',
      'Necrotic pulp',
      'Previous RCT',
      'Previous pulp therapy',
      'A. apical periodontitis',
      'C. apical periodontitis',
      'A. apical abscess',
      'C. apical abscess',
      'Radicular cysts',
      'Blocked canals',
      'Root perforation',
      'Ext. root resorption',
      'Open apex',
      'Cracked tooth',
      'Crown #',
      'Crown-root #',
      'Root#'
    ],
    procDetail: [
      'Endo cons',
      'Endo review',
      'Endo case discharge',
      'EPT',
      'Pulpo 1st visit (Perm)',
      'RCT 1st visit',
      'RCT subseq visit',
      'RCT obturation',
      'RC Retx 1st visit',
      'RC Retx subseq visit',
      'RC Retx obturation',
      'Single visit RCT',
      'Apicoectomy-Retrograde F',
      'Temp Restoration (TD)',
      'Prefab SS post',
      'Prefab Non-metal post',
      'Non-vital bleaching'

    ]
  },
  { pname: 'FD', probDetail: [], procDetail: [
    'FD Cons (Endo)',
    'FD Cons (Pros) ',
    'FD Cons (Implant)',
    'Discharge from FD'] },
  { pname: 'GD', probDetail: [
    'Missing tooth',
    'Missing Primary Teeth',
    'Impacted tooth',
    'Unerupted tooth',
    'Retained root',
    'Existing filling',
    'Existing fissure sealant',
    'Existing crown',
    'Existing bridge',
    'Existing implant',
    'Previous RCT',
    'Caries',
    'Defective filling',
    'Abrasion (by tooth)',
    'Erosion (by tooth)',
    'Attrition (by tooth)',
    'Crown fracture',
    'Crown-root fracture',
    'Root fracture'
  ],
    procDetail: [
      'New Cons',
      'Recall',
      'Old Cons',
      'Urgent',
      'BW',
      'PA',
      'Scaling',
      'Fit',
      'Filling (Amalgam)',
      'Filling (GIC Light Cure)',
      'Filling (Composite)',
      'Pulpectomy',
      'Caries Prevention Advice',
      'Tooth Wear Management',
      'TB practice',
      'IDB practice',
      'Floss practice',
      'OHI (advice only)'

    ]
  },
  { pname: 'GP', probDetail: [
    'Crown fracture',
    'Crown-root fracture',
    'Retained root',
    'Cracked tooth',
    'Generalised toothwear',
    'Caries',
    'Dental abscess',
    'Periodontal abscess',
    'A. apical periodontitis',
    'Pulpitis',
    'Chronic periodontitis',
    'Impacted tooth',
    'Ectopic eruption',
    'Retained deciduous tooth',
    'Non-functional tooth'
  ], procDetail: [
    'Urgent',
    'PA',
    'TTP',
    'LA(infiltration)',
    'LA(ID block)',
    'LA(intraligamental)',
    'Extraction of tooth',
    'Extraction of root',
    'Surgical extraction of root',
    'Control of bleeding',
    'Suturing of wound',
    'Removal of suture',
    'Manage post-op complication',
    'Informed consent',
    'Referral to OMS'

  ]  },
  { pname: 'OMS', probDetail: [
    'Teeth impaction',
    'Supernumerary tooth',
    'Facial cellulitis',
    'Dental abscess',
    'Periodontal abscess',
    'Orofacial abscess',
    'Radicular cyst',
    'Dentigerous cyst',
    '# zygomatic complex',
    '# mandible angle',
    '# mandible condyle',
    'Dental luxation',
    'Dental avulsion',
    'Radiation caries',
    'TMJ dislocation',
    'TMJ int. derangement',
    'Trigeminal neuralgia'

  ] , procDetail: [
    'New OMS consultation',
    'Review / Follow-up',
    'Ext of tooth',
    'Surg ext. (impaction)',
    'Oral suturing',
    'Oral sutures removal',
    'Oral biopsy',
    'Orofacial abscess I & D',
    'Control of bleeding',
    'Dental trauma - Splinting',
    'Enucleation of jaw cyst',
    'Odont. Tumour excision',
    'Implant fixture placement',
    'Heal. Abutment placement',
    'Orthognathic work-up',
    'TMD conservative Tx',
    'OMS applicance delivery'

  ]},
  { pname: 'Ortho', probDetail: [
    'Class I malocclusion',
    'Class II / 1 malocclusion',
    'Class II / 2 malocclusion',
    'Class III malocclusion',
    'Skeletal I relationship',
    'Skeletal II relationship',
    'Skeletal III relationship',
    'Increased overjet',
    'Reverse overjet',
    'Increased overbite',
    'Anterior open bite (AOB)',
    'Dental midline shifted',
    'Anterior crossbite',
    'Posterior crossbite',
    'Proclined incisor',
    'Retroclined incisor',
    'Crowding of dental arch',
    'Spacing of dental arch'
  ] , procDetail: [
    'Ortho referral consult',
    'Ortho pretreat consult',
    'Ortho record taking',
    'OPG',
    'Lat Ceph',
    'Treatment planning',
    'Fit separator',
    'Banding',
    'Bonding',
    'Fit multiband app',
    'Adjust multiband app',
    'Remove multiband app',
    'Working impression- Ortho',
    'Fit removable retainer',
    'Adjust removable retainer',
    'Fit removable FN app',
    'Adjust removable FN app',
    'Fit palatal arch'

  ]},
  { pname: 'Perio', probDetail: [
    'OH good',
    'OH fair',
    'OH poor',
    'Plaque induced ging dis',
    'Drug inflen ging enlarg',
    'Trauma ging lesion',
    'Local mod C.periodontitis',
    'Local sev C.periodontitis',
    'Gen mod C.periodontitis',
    'Gen sev C.periodontitis',
    'Local aggre periodontitis',
    'Gen aggre periodontitis',
    'NUG',
    'Den resto ging dis perio',
    'Rt # ging dis perio',
    'Ging recession',
    'Peri-implant mucositis',
    'Peri-implantitis'
  ], procDetail: [
    'Review',
    'Perio cons',
    'Perio case discharge',
    'OHI',
    'Scaling',
    'Root debride FM',
    'Root debride Q',
    'Root debride (tooth)',
    'Implant debride',
    'Adjunct nonsurg tx-sys',
    'Adjunct nonsurg tx-local',
    'Support perio therapy',
    'Open flap X osteop',
    'Open flap w osteop',
    'Open flap deb implant',
    'Tooth root resect',
    'Tooth hemisect'

  ] },
  { pname: 'Pros', probDetail: [
    'Complete edentulism',
    'Missing tooth',
    'Existing Crown',
    'Existing Bridge Pontic',
    'Resin-bonded Retainer',
    'Bridge extension (red line)',
    'Existing implant',
    'Horiz Ridge Resorption',
    'Vert Ridge Resorption',
    'Denture retention inadequate',
    'Denture fracture',
    'Fix Pros - Loss of Retention',
    'Fix Pros - Deficient margin'
  ], procDetail: [
    'Comp Dent - 1st Imp',
    'Comp Dent - Wking Imp',
    'Comp Dent - Bite',
    'Comp Dent - Tryin',
    'Comp Dent - Iss (acrylic)',
    'Comp Dent - Adjust',
    'Parital Dent - 1st Imp',
    'Partial Dent - Tooth prep',
    'Partial Dent - Wking Imp',
    'Partial Dent - MF',
    'Partial Dent - Bite',
    'Partial Dent - Tryin',
    'Partial Dent - Iss (acrylic)',
    'Partial Dent - Adjust',
    'Crown/Onlay Tooth Prep',
    'Issue Crown/Onlay'

  ] },
  { pname: 'RD', probDetail: [

    'Bridge extension (red line)',
    'Crown/Onlay',
    'Bridge retainer',
    'Bridge pontic',
    'Loss of retention (Fixed)',
    'Porcelain # (Fixed)',
    'Framework # (Fixed)',
    'Crown # (tooth)',
    'Root # (tooth)',
    'Crown-root # (tooth)',
    'Defective restoration',
    'Discoloured margin',
    'Discoloured restoration',
    'Overhang margin'
  ] , procDetail: [
    'Crown/ Onlay Prep.',
    'Crown/ Onlay Issue',
    'Crown/ Onlay (Temp C.)',
    'Crown/ Onlay (Temp Lab)',
    'Crown/ Onlay Re-cement',
    'Bridge Prep.',
    'Bridge Issue',
    'Bridge (Temp C.)',
    'RBB Prep.',
    'RBB Try-in',
    'RBB Issue',
    'RBB Recementation',
    'Cast Post & Core Prep.',
    'Cast Post & Core Issue',
    'Removal of Crown/ Onlay',
    'Removal of Bridge',
    'Removal of Bridge (Part.)',
    'Removal of RBB'

  ]},
  { pname: 'RESET', probDetail: [

    'Sound Tooth',
    'Clear Birdge'
  ] , procDetail: []},
  // , procDetail: []},
  { pname: 'SET', probDetail: []
  , procDetail: [
    'GP',
    'Recall',
    'N Cons'
  ]},
  { pname: 'PREVENT' , probDetail: []
  , procDetail: [
    'Caries Prevention',
    'Perio Prevention'
  ]}
];


export {  probProcMap };
