const PREFFIX = 'ADMINISTRATION_SESSION_MANAGEMENT';

export const UPDATE_STATE = `${PREFFIX}_UPDATE_STATE`;

export const GET_SESSIONS_OF_SERVICE = `${PREFFIX}_PUT_LIST_SESSIONS_OF_SERVICE`;
export const GET_SESSIONS_OF_SITE = `${PREFFIX}_PUT_LIST_SESSIONS_OF_SITE`;
export const GET_SINGLE_SESSIONS_BY_ID = `${PREFFIX}_GET_SINGLE_SESSIONS_BY_ID`;

export const LIST_SESSION_OF_SERVICE = `${PREFFIX}_LIST_SESSION_OF_SERVICE`;
export const LIST_SESSION_OF_SITE = `${PREFFIX}_LIST_SESSION_OF_SITE`;
export const LIST_SESSION_OF_SINGLE_SESSION = `${PREFFIX}_LIST_SESSION_OF_SINGLE_SESSION`;

export const CREATE_SESSION = `${PREFFIX}_CREATE_SESSION`;
export const UPDATE_SESSION = `${PREFFIX}_UPDATE_SESSION`;
export const DELETE_SESSION = `${PREFFIX}_DELETE_SESSION`;

export const PUSH_SESSION_OF_SERVICE = `${PREFFIX}_PUSH_SESSION_OF_SERVICE`;
export const PUSH_SESSION_OF_SITE = `${PREFFIX}_PUSH_SESSION_OF_SITE`;
export const PUSH_SINGLE_SESSIONS_TO_UPDATING_SESSION = `${PREFFIX}_PUSH_SINGLE_SESSIONS_TO_UPDATING_SESSION`;

export const CLOSE_SESSION_MANAGEMENT_DIALOG = `${PREFFIX}_CLOSE_SESSION_MANAGEMENT_DIALOG`;

export const UPDATE_SESSION_CONFIG = `${PREFFIX}_UPDATE_SESSION_CONFIG`;
