const PRE = 'MRAM';

export const INIT_MRAM_FIELD_VALUE_LIST = `${PRE}_INIT_MRAM_FIELD_VALUE_LIST`;
export const GET_MRAM_FIELD_VALUE_LIST = `${PRE}_GET_MRAM_FIELD_VALUE_LIST`;
export const MRAM_FIELD_VALUE_LIST = `${PRE}_MRAM_FIELD_VALUE_LIST`;
export const SAVE_MRAM_FIELD_VALUE_LIST = `${PRE}_SAVE_MRAM_FIELD_VALUE_LIST`;
export const GET_PREVIEW_REPORT_PATIENT_DATA = `${PRE}_GET_PREVIEW_REPORT_PATIENT_DATA`;
export const GET_PREVIEW_REPORT_DOCTOR_DATA = `${PRE}_GET_PREVIEW_REPORT_DOCTOR_DATA`;
export const CHECK_DUPLICATED_MRAM_RECORD_ON_SAME_DAY = `${PRE}_CHECK_DUPLICATED_MRAM_RECORD_ON_SAME_DAY`;
export const CHECK_MRAM_RECORD_CREATED_WITHIN_6_MONTHS = `${PRE}_CHECK_MRAM_RECORD_CREATED_WITHIN_6_MONTHS`;
export const CHECK_MRAM_RECORD_EXISTED = `${PRE}_CHECK_MRAM_RECORD_EXISTED`;