const PRE = 'SAAM_PATIENT';

export const GET_PATIENT_SUMMARY = `${PRE}_GET_PATIENT_SUMMARY`;
export const PUT_PATIENT_SUMMARY = `${PRE}_PUT_PATIENT_SUMMARY`;
export const CLEAR_PATIENT_SUMMARY = `${PRE}_CLEAR_PATIENT_SUMMARY`;