const MEDICAL_SUMMARY_TYPE = {
  PAST_MEDICAL_HISTORY:'P',
  SOCIAL_HISTORY_SMOKING:'S',
  SOCIAL_HISTORY_DRINKING:'D',
  SOCIAL_HISTORY_SUBSTANCE_ABUSE:'A',
  OCCUPATIONAL_HISTORY:'O',
  FAMILY_HISTORY:'F',
  REMARK:'R'
};

const MEDICAL_SUMMARY_STATUS_NEVER_MAP = new Map([
  ['1','7'],
  ['8','20'],
  ['26','29']
]);

const MEDICAL_SUMMARY_DROP_OPTION_SIGN = {
  STATUS: '1',
  TYPE: '2'
};

const DELETED_STATUS = {
  YES: 'Y',
  NO: 'N'
};

const MEDICAL_TYPE = {
  OCCUPATIONAL_HISTORY:'O',
  OTHERS:'others'
};

export {
  MEDICAL_TYPE,
  DELETED_STATUS,
  MEDICAL_SUMMARY_TYPE,
  MEDICAL_SUMMARY_STATUS_NEVER_MAP,
  MEDICAL_SUMMARY_DROP_OPTION_SIGN
};