const PRE = 'TOKEN_TEMPLATE_MANAGEMENT';

export const TOKEN_TMPL_LIST = `${PRE}_TOKEN_TMPL_LIST`;
export const GET_TOKEN_TMPL_LIST = `${PRE}_GET_TOKEN_TMPL_LIST`;
export const SAVE_TOKEN_TMPL_LIST = `${PRE}_SAVE_TOKEN_TMPL_LIST`;

export const GET_INSTRUCTION_LIST = `${PRE}_GET_INSTRUCTION_LIST`;
export const INSTRUCTION_LIST_RESULT = `${PRE}_INSTRUCTION_LIST_RESULT`;
export const SAVE_INSTRUCTION_LIST = `${PRE}_SAVE_INSTRUCTION_LIST`;
export const SAVE_INSTRUCTION_LIST_RESULT = `${PRE}_SAVE_INSTRUCTION_LIST_RESULT`;

export const GET_TOKEN_TMPL_OBJECT = `${PRE}_GET_TOKEN_TMPL_OBJECT`;
export const GET_TOKEN_INSTRUCT_LIST = `${PRE}_GET_TOKEN_INSTRUCT_LIST`;
export const SAVE_TOKEN_TEMPLAT = `${PRE}_SAVE_TOKEN_TEMPLAT`;
export const GET_TOKEN_FORM_ITEMS = `${PRE}_GET_TOKEN_FORM_ITEMS`;

export const GET_TOKEN_PRINTVIEW_LIST=`${PRE}_GET_TOKEN_PRINTVIEW_LIST`;

