const PREFFIX = 'REGISTRATION';
export const RESET_ALL = `${PREFFIX}_RESET_ALL`;
export const RESPONSE_RESET_ALL = `${PREFFIX}_RESPONSE_RESET_ALL`;
export const UPDATE_PATIENT_OPERATE_STATUS = `${PREFFIX}_UPDATE_PATIENT_OPERATE_STATUS`;
export const UPDATE_PATIENT = `${PREFFIX}_UPDATE_PATIENT`;
export const REGISTER_PATIENT = `${PREFFIX}_REGISTER_PATIENT`;
export const UPDATE_STATE = `${PREFFIX}_UPDATE_STATE`;
export const GET_PATINET_BY_ID = `${PREFFIX}_GET_PATINET_BY_ID`;
export const SELECTED_PATIENT_BY_ID = `${PREFFIX}_SELECTED_PATIENT_BY_ID`;
export const GET_PREFERRED_LANGUAGE = `${PREFFIX}_GET_PREFERRED_LANGUAGE`;
// export const UPDATE_PATIENT_FIELD=`${PREFFIX}_UPDATE_PATIENT_FIELD`;
export const INIT_PATIENT_BY_ID = `${PREFFIX}_INIT_PATIENT_BY_ID`;
export const RESPONSE_INIT_PATIENT = `${PREFFIX}_PUT_PATIENT_BY_ID`;
export const PUT_GET_CODE_LIST = `${PREFFIX}_PUT_GET_CODE_LIST`;
export const MAP_PMI_WITH_PROVEN_VALUE = `${PREFFIX}_MAP_PMI_WITH_PROVEN_VALUE`;
export const RESPONSE_MAP_PMI_WITH_PROVEN_VALUE = `${PREFFIX}_RESPONSE_MAP_PMI_WITH_PROVEN_VALUE`;

//search patient by pin
export const SEARCH_PATIENT = `${PREFFIX}_SEARCH_PATIENT`;
export const PUT_PATIENT = `${PREFFIX}_PUT_PATIENT`;
export const SEARCH_PATIENT_BY_DOC_TYPE = `${PREFFIX}_SEARCH_PATIENT_BY_DOC_TYPE`;

//cccCode
export const FIND_CHAR_BY_CC_CODE = `${PREFFIX}_FIND_CHAR_BY_CC_CODE`;
//update Chinese name
export const UPDATE_CHI_CHAR = `${PREFFIX}_UPDATE_CHI_CHAR`;

//babyInfo calculator
export const UPDATE_BABYINFO_CHI_CHAR = `${PREFFIX}_UPDATE_BABYINFO_CHI_CHAR`;

export const RESET_BABYINFO = `${PREFFIX}_RESET_BABYINFO`;
export const GET_BABYINFO = `${PREFFIX}_GET_BABYINFO`;


//list problem pmi record
export const LIST_VALID_FOR_PROBLEM_PMI = `${PREFFIX}_LIST_VALID_FOR_PROBLEM_PMI`;
export const PUT_VALID_FOR_PROBLEM_PMI = `${PREFFIX}_PUT_VALID_FOR_PROBLEM_PMI`;

//confirm problem patient
export const CONFIRM_PROBLEM_PATIENT = `${PREFFIX}_CONFIRM_PROBLEM_PATIENT`;

//update patient related flag
export const LOAD_PATIENT_RELATED_FLAG = `${PREFFIX}_LOAD_PATIENT_RELATED_FLAG`;

//check accessRight
export const CHECK_ACCESS_RIGHT = `${PREFFIX}_CHECK_ACCESS_RIGHT`;
export const CHECK_ACCESS_RIGHT_BY_STAFFID = `${PREFFIX}_CHECK_ACCESS_RIGHT_BY_STAFFID`;

//init miscellaneous data
export const INIT_MISCELLANEOUS = `${PREFFIX}_INIT_MISCELLANEOUS`;
export const RESPONSE_INIT_MISCELLANEOUS = `${PREFFIX}_RESPONSE_INIT_MISCELLANEOUS`;

//check document pair is exist valid pmi
export const CHECK_VALID_PMI_EXIST = `${PREFFIX}_CHECK_VALID_PMI_EXIST`;
export const POP_UP_SEARCH_DIALOG = `${PREFFIX}_POP_UP_SEARCH_DIALOG`;
export const CREATE_NEW_PMI = `${PREFFIX}_CREATE_NEW_PMI`;

export const RESPONSE_CREATE_NEW_PMI = `${PREFFIX}_RESPONSE_CREATE_NEW_PMI`;
export const RESPONSE_SELECTED_PMI = `${PREFFIX}_RESPONSE_SELECTED_PMI`;


//patient list do 'Create New'
export const PATIENT_LIST_CREATE_NEW = `${PREFFIX}_PATIENT_LIST_CREATE_NEW`;

//patient summary skip to registration
export const PATIENT_SUMMARY_EDIT_PATIENT = `${PREFFIX}_PATIENT_SUMMARY_EDIT_PATIENT`;

//for anonymous patient phone no
export const REGISTRATION_BLOCK_FIRST_UPDATE_PHONE_LIST_AND_RESTORE = `${PREFFIX}_BLOCK_FIRST_UPDATE_PHONE_LIST`;

/**search associated person hkid and fill input */
export const SEARCH_ASSOCIATED_PERSON_WITH_HKID = `${PREFFIX}_SEARCH_ASSOCIATED_PERSON_WITH_HKID`;
export const OPEN_ASSOCIATED_SEARCH_RESULT = `${PREFFIX}_OPEN_ASSOCIATED_SEARCH_RESULT`;

/**open mode: open by <view patient details> or <registration> */
export const OPEN_MODE = `${PREFFIX}_OPEN_MODE`;

export const GET_EXIST_CLINICAL_DATA = `${PREFFIX}_GET_EXIST_CLINICAL_DATA`;

// EHS Specific -- by Kk Lam
export const UPDATE_PATIENT_EHS_DTO = `${PREFFIX}_UPDATE_PATEINT_EHS_DTO`;
export const ENROLL_EHS_MEMBER = `${PREFFIX}_ENROLL_EHS_MEMBER`;

export const UPDATE_PATIENT_BASE_INFO = `${PREFFIX}_UPDATE_PATIENT_BASE_INFO`;

export const CHECK_FAMILY_NO = `${PREFFIX}_CHECK_FAMILY_NO`;

export const CHIEF_PARENT_CHECKBOX_HANDLER = `${PREFFIX}_CHIEF_PARENT_CHECKBOX_HANDLER`;

export const VALID_FAMILY_NO = `${PREFFIX}_VALID_FAMILY_NO`;

export const INVALID_FAMILY_NO = `${PREFFIX}_INVALID_FAMILY_NO`;

export const RESET_FAMILY_NO_CHECKING = `${PREFFIX}_RESET_FAMILY_NO_CHECKING`;

export const UPDATE_CGS_SPEC = `${PREFFIX}_UPDATE_CGS_SPEC`;

export const UPDATE_SERVICE_SPECIFIC_FORM_VALIDATION = `${PREFFIX}_UPDATE_SERVICE_SPECIFIC_FORM_VALIDATION`;

export const PRINT_REG_SUMMARY = `${PREFFIX}_PRINT_REG_SUMMARY`;

export const PRINT_GUM_LABEL = `${PREFFIX}_PRINT_GUM_LABEL`;

export const GET_PATIENT_KEY = `${PREFFIX}_GET_PATIENT_KEY`;

export const PMI_SMS_CHECKING_LOG = `${PREFFIX}_PMI_SMS_CHECKING_LOG`;

// screening info
export const FETCH_SCREENING_INFO = `${PREFFIX}_FETCH_SCREENING_INFO`;
export const UPDATE_SCREENING_INFO = `${PREFFIX}_UPDATE_SCREENING_INFO`;
export const SAVE_SCREENING_INFO = `${PREFFIX}_SAVE_SCREENING_INFO`;
export const UPDATE_DOCUMENT_ID = `${PREFFIX}_UPDATE_DOCUMENT_ID`;