const mockDate = [
    {
        key: 1,
        name: 'G037',
        active: true,
        details: [
            {
                key: 1,
                category: 'Acupuncture',
                treatment: 'APT 2',
                documentation: 'APT 2',
                barcodeNo: 8880001,
                active: true,
            },
            {
                key: 2,
                category: 'Chest Physiotherapy',
                treatment: 'Power Trainer',
                documentation: 'Power Trainer',
                barcodeNo: 8880002,
                active: true,
            },
            {
                key: 3,
                category: 'Electrotherapy / Traction',
                treatment: 'Shoulder Board',
                documentation: 'Shoulder Board',
                barcodeNo: 8880003,
                active: true,
            },
            {
                key: 4,
                category: 'Functional Capacity Evaluation',
                treatment: 'Cycle',
                documentation: 'Cycle',
                barcodeNo: 8880004,
                active: true,
            },
            {
                key: 5,
                category: 'Functional Training',
                treatment: 'Double Prostretch',
                documentation: 'Double Prostretch',
                barcodeNo: 8880005,
                active: true,
            },
            {
                key: 6,
                category: 'Hydrotherapy',
                treatment: 'Balance Trainer',
                documentation: 'Balance Trainer',
                barcodeNo: 8880006,
                active: false,
            },
        ],
    },

    {
        key: 2,
        name: 'G038',
        active: false,
        details: [
            {
                key: 1,
                category: 'Acupuncture',
                treatment: 'APT 2',
                documentation: 'APT 2',
                barcodeNo: 8880001,
                active: false,
            },
            {
                key: 2,
                category: 'Chest Physiotherapy',
                treatment: 'Power Trainer',
                documentation: 'Power Trainer',
                barcodeNo: 8880002,
                active: false,
            },
            {
                key: 3,
                category: 'Electrotherapy / Traction',
                treatment: 'Shoulder Board',
                documentation: 'Shoulder Board',
                barcodeNo: 8880003,
                active: false,
            },
            {
                key: 4,
                category: 'Functional Capacity Evaluation',
                treatment: 'Cycle',
                documentation: 'Cycle',
                barcodeNo: 8880004,
                active: false,
            },
            {
                key: 5,
                category: 'Functional Training',
                treatment: 'Double Prostretch',
                documentation: 'Double Prostretch',
                barcodeNo: 8880005,
                active: false,
            },
            {
                key: 6,
                category: 'Hydrotherapy',
                treatment: 'Balance Trainer',
                documentation: 'Balance Trainer',
                barcodeNo: 8880006,
                active: false,
            },
        ],
    },
    {
        key: 3,
        name: 'G039',
        active: true,
        details: [
            {
                key: 1,
                category: 'Acupuncture',
                treatment: 'APT 2',
                documentation: 'APT 2',
                barcodeNo: 8880001,
                active: true,
            },
            {
                key: 2,
                category: 'Chest Physiotherapy',
                treatment: 'Power Trainer',
                documentation: 'Power Trainer',
                barcodeNo: 8880002,
                active: true,
            },
            {
                key: 3,
                category: 'Electrotherapy / Traction',
                treatment: 'Shoulder Board',
                documentation: 'Shoulder Board',
                barcodeNo: 8880003,
                active: true,
            },
            {
                key: 4,
                category: 'Functional Capacity Evaluation',
                treatment: 'Cycle',
                documentation: 'Cycle',
                barcodeNo: 8880004,
                active: true,
            },
            {
                key: 5,
                category: 'Functional Training',
                treatment: 'Double Prostretch',
                documentation: 'Double Prostretch',
                barcodeNo: 8880005,
                active: true,
            },
            {
                key: 6,
                category: 'Hydrotherapy',
                treatment: 'Balance Trainer',
                documentation: 'Balance Trainer',
                barcodeNo: 8880006,
                active: true,
            },
        ],
    },
    {
        key: 4,
        name: 'G040',
        active: false,
        details: [
            {
                key: 1,
                category: 'Acupuncture',
                treatment: 'APT 2',
                documentation: 'APT 2',
                barcodeNo: 8880001,
                active: false,
            },
            {
                key: 2,
                category: 'Chest Physiotherapy',
                treatment: 'Power Trainer',
                documentation: 'Power Trainer',
                barcodeNo: 8880002,
                active: false,
            },
            {
                key: 3,
                category: 'Electrotherapy / Traction',
                treatment: 'Shoulder Board',
                documentation: 'Shoulder Board',
                barcodeNo: 8880003,
                active: false,
            },
            {
                key: 4,
                category: 'Functional Capacity Evaluation',
                treatment: 'Cycle',
                documentation: 'Cycle',
                barcodeNo: 8880004,
                active: false,
            },
            {
                key: 5,
                category: 'Functional Training',
                treatment: 'Double Prostretch',
                documentation: 'Double Prostretch',
                barcodeNo: 8880005,
                active: false,
            },
            {
                key: 6,
                category: 'Hydrotherapy',
                treatment: 'Balance Trainer',
                documentation: 'Balance Trainer',
                barcodeNo: 8880006,
                active: false,
            },
        ],
    },
    {
        key: 5,
        name: 'Extra Rehab Setting',
        active: true,
        details: [
            {
                key: 1,
                category: 'Acupuncture',
                treatment: 'APT 2',
                documentation: 'APT 2',
                barcodeNo: 8880001,
                active: true,
            },
            {
                key: 2,
                category: 'Chest Physiotherapy',
                treatment: 'Power Trainer',
                documentation: 'Power Trainer',
                barcodeNo: 8880002,
                active: true,
            },
            {
                key: 3,
                category: 'Electrotherapy / Traction',
                treatment: 'Shoulder Board',
                documentation: 'Shoulder Board',
                barcodeNo: 8880003,
                active: true,
            },
            {
                key: 4,
                category: 'Functional Capacity Evaluation',
                treatment: 'Cycle',
                documentation: 'Cycle',
                barcodeNo: 8880004,
                active: true,
            },
            {
                key: 5,
                category: 'Functional Training',
                treatment: 'Double Prostretch',
                documentation: 'Double Prostretch',
                barcodeNo: 8880005,
                active: true,
            },
            {
                key: 6,
                category: 'Hydrotherapy',
                treatment: 'Balance Trainer',
                documentation: 'Balance Trainer',
                barcodeNo: 8880006,
                active: true,
            },
        ],
    },
    {
        key: 6,
        name: 'Extra Rehab Setting',
        active: true,
        details: [
            {
                key: 1,
                category: 'Acupuncture',
                treatment: 'APT 2',
                documentation: 'APT 2',
                barcodeNo: 8880001,
                active: true,
            },
            {
                key: 2,
                category: 'Chest Physiotherapy',
                treatment: 'Power Trainer',
                documentation: 'Power Trainer',
                barcodeNo: 8880002,
                active: true,
            },
            {
                key: 3,
                category: 'Electrotherapy / Traction',
                treatment: 'Shoulder Board',
                documentation: 'Shoulder Board',
                barcodeNo: 8880003,
                active: true,
            },
            {
                key: 4,
                category: 'Functional Capacity Evaluation',
                treatment: 'Cycle',
                documentation: 'Cycle',
                barcodeNo: 8880004,
                active: true,
            },
            {
                key: 5,
                category: 'Functional Training',
                treatment: 'Double Prostretch',
                documentation: 'Double Prostretch',
                barcodeNo: 8880005,
                active: true,
            },
            {
                key: 6,
                category: 'Hydrotherapy',
                treatment: 'Balance Trainer',
                documentation: 'Balance Trainer',
                barcodeNo: 8880006,
                active: true,
            },
        ],
    },
    {
        key: 7,
        name: 'Extra Rehab Setting',
        active: true,
        details: [
            {
                key: 1,
                category: 'Acupuncture',
                treatment: 'APT 2',
                documentation: 'APT 2',
                barcodeNo: 8880001,
                active: true,
            },
            {
                key: 2,
                category: 'Chest Physiotherapy',
                treatment: 'Power Trainer',
                documentation: 'Power Trainer',
                barcodeNo: 8880002,
                active: true,
            },
            {
                key: 3,
                category: 'Electrotherapy / Traction',
                treatment: 'Shoulder Board',
                documentation: 'Shoulder Board',
                barcodeNo: 8880003,
                active: true,
            },
            {
                key: 4,
                category: 'Functional Capacity Evaluation',
                treatment: 'Cycle',
                documentation: 'Cycle',
                barcodeNo: 8880004,
                active: true,
            },
            {
                key: 5,
                category: 'Functional Training',
                treatment: 'Double Prostretch',
                documentation: 'Double Prostretch',
                barcodeNo: 8880005,
                active: true,
            },
            {
                key: 6,
                category: 'Hydrotherapy',
                treatment: 'Balance Trainer',
                documentation: 'Balance Trainer',
                barcodeNo: 8880006,
                active: true,
            },
        ],
    },
    {
        key: 8,
        name: 'Extra Rehab Setting',
        active: true,
        details: [
            {
                key: 1,
                category: 'Acupuncture',
                treatment: 'APT 2',
                documentation: 'APT 2',
                barcodeNo: 8880001,
                active: true,
            },
            {
                key: 2,
                category: 'Chest Physiotherapy',
                treatment: 'Power Trainer',
                documentation: 'Power Trainer',
                barcodeNo: 8880002,
                active: true,
            },
            {
                key: 3,
                category: 'Electrotherapy / Traction',
                treatment: 'Shoulder Board',
                documentation: 'Shoulder Board',
                barcodeNo: 8880003,
                active: true,
            },
            {
                key: 4,
                category: 'Functional Capacity Evaluation',
                treatment: 'Cycle',
                documentation: 'Cycle',
                barcodeNo: 8880004,
                active: true,
            },
            {
                key: 5,
                category: 'Functional Training',
                treatment: 'Double Prostretch',
                documentation: 'Double Prostretch',
                barcodeNo: 8880005,
                active: true,
            },
            {
                key: 6,
                category: 'Hydrotherapy',
                treatment: 'Balance Trainer',
                documentation: 'Balance Trainer',
                barcodeNo: 8880006,
                active: true,
            },
        ],
    },
    {
        key: 9,
        name: 'Extra Rehab Setting',
        active: true,
        details: [
            {
                key: 1,
                category: 'Acupuncture',
                treatment: 'APT 2',
                documentation: 'APT 2',
                barcodeNo: 8880001,
                active: true,
            },
            {
                key: 2,
                category: 'Chest Physiotherapy',
                treatment: 'Power Trainer',
                documentation: 'Power Trainer',
                barcodeNo: 8880002,
                active: true,
            },
            {
                key: 3,
                category: 'Electrotherapy / Traction',
                treatment: 'Shoulder Board',
                documentation: 'Shoulder Board',
                barcodeNo: 8880003,
                active: true,
            },
            {
                key: 4,
                category: 'Functional Capacity Evaluation',
                treatment: 'Cycle',
                documentation: 'Cycle',
                barcodeNo: 8880004,
                active: true,
            },
            {
                key: 5,
                category: 'Functional Training',
                treatment: 'Double Prostretch',
                documentation: 'Double Prostretch',
                barcodeNo: 8880005,
                active: true,
            },
            {
                key: 6,
                category: 'Hydrotherapy',
                treatment: 'Balance Trainer',
                documentation: 'Balance Trainer',
                barcodeNo: 8880006,
                active: true,
            },
        ],
    },
    {
        key: 10,
        name: 'Extra Rehab Setting',
        active: true,
        details: [
            {
                key: 1,
                category: 'Acupuncture',
                treatment: 'APT 2',
                documentation: 'APT 2',
                barcodeNo: 8880001,
                active: true,
            },
            {
                key: 2,
                category: 'Chest Physiotherapy',
                treatment: 'Power Trainer',
                documentation: 'Power Trainer',
                barcodeNo: 8880002,
                active: true,
            },
            {
                key: 3,
                category: 'Electrotherapy / Traction',
                treatment: 'Shoulder Board',
                documentation: 'Shoulder Board',
                barcodeNo: 8880003,
                active: true,
            },
            {
                key: 4,
                category: 'Functional Capacity Evaluation',
                treatment: 'Cycle',
                documentation: 'Cycle',
                barcodeNo: 8880004,
                active: true,
            },
            {
                key: 5,
                category: 'Functional Training',
                treatment: 'Double Prostretch',
                documentation: 'Double Prostretch',
                barcodeNo: 8880005,
                active: true,
            },
            {
                key: 6,
                category: 'Hydrotherapy',
                treatment: 'Balance Trainer',
                documentation: 'Balance Trainer',
                barcodeNo: 8880006,
                active: true,
            },
        ],
    },
    {
        key:11,
        name: 'Extra Rehab Setting',
        active: true,
        details: [
            {
                key: 1,
                category: 'Acupuncture',
                treatment: 'APT 2',
                documentation: 'APT 2',
                barcodeNo: 8880001,
                active: true,
            },
            {
                key: 2,
                category: 'Chest Physiotherapy',
                treatment: 'Power Trainer',
                documentation: 'Power Trainer',
                barcodeNo: 8880002,
                active: true,
            },
            {
                key: 3,
                category: 'Electrotherapy / Traction',
                treatment: 'Shoulder Board',
                documentation: 'Shoulder Board',
                barcodeNo: 8880003,
                active: true,
            },
            {
                key: 4,
                category: 'Functional Capacity Evaluation',
                treatment: 'Cycle',
                documentation: 'Cycle',
                barcodeNo: 8880004,
                active: true,
            },
            {
                key: 5,
                category: 'Functional Training',
                treatment: 'Double Prostretch',
                documentation: 'Double Prostretch',
                barcodeNo: 8880005,
                active: true,
            },
            {
                key: 6,
                category: 'Hydrotherapy',
                treatment: 'Balance Trainer',
                documentation: 'Balance Trainer',
                barcodeNo: 8880006,
                active: true,
            },
        ],
    },
    {
        key: 12,
        name: 'Extra Rehab Setting',
        active: true,
        details: [
            {
                key: 1,
                category: 'Acupuncture',
                treatment: 'APT 2',
                documentation: 'APT 2',
                barcodeNo: 8880001,
                active: true,
            },
            {
                key: 2,
                category: 'Chest Physiotherapy',
                treatment: 'Power Trainer',
                documentation: 'Power Trainer',
                barcodeNo: 8880002,
                active: true,
            },
            {
                key: 3,
                category: 'Electrotherapy / Traction',
                treatment: 'Shoulder Board',
                documentation: 'Shoulder Board',
                barcodeNo: 8880003,
                active: true,
            },
            {
                key: 4,
                category: 'Functional Capacity Evaluation',
                treatment: 'Cycle',
                documentation: 'Cycle',
                barcodeNo: 8880004,
                active: true,
            },
            {
                key: 5,
                category: 'Functional Training',
                treatment: 'Double Prostretch',
                documentation: 'Double Prostretch',
                barcodeNo: 8880005,
                active: true,
            },
            {
                key: 6,
                category: 'Hydrotherapy',
                treatment: 'Balance Trainer',
                documentation: 'Balance Trainer',
                barcodeNo: 8880006,
                active: true,
            },
        ],
    },
    {
        key: 13,
        name: 'Extra Rehab Setting',
        active: true,
        details: [
            {
                key: 1,
                category: 'Acupuncture',
                treatment: 'APT 2',
                documentation: 'APT 2',
                barcodeNo: 8880001,
                active: true,
            },
            {
                key: 2,
                category: 'Chest Physiotherapy',
                treatment: 'Power Trainer',
                documentation: 'Power Trainer',
                barcodeNo: 8880002,
                active: true,
            },
            {
                key: 3,
                category: 'Electrotherapy / Traction',
                treatment: 'Shoulder Board',
                documentation: 'Shoulder Board',
                barcodeNo: 8880003,
                active: true,
            },
            {
                key: 4,
                category: 'Functional Capacity Evaluation',
                treatment: 'Cycle',
                documentation: 'Cycle',
                barcodeNo: 8880004,
                active: true,
            },
            {
                key: 5,
                category: 'Functional Training',
                treatment: 'Double Prostretch',
                documentation: 'Double Prostretch',
                barcodeNo: 8880005,
                active: true,
            },
            {
                key: 6,
                category: 'Hydrotherapy',
                treatment: 'Balance Trainer',
                documentation: 'Balance Trainer',
                barcodeNo: 8880006,
                active: true,
            },
        ],
    },
    {
        key: 14,
        name: 'Extra Rehab Setting',
        active: true,
        details: [
            {
                key: 1,
                category: 'Acupuncture',
                treatment: 'APT 2',
                documentation: 'APT 2',
                barcodeNo: 8880001,
                active: true,
            },
            {
                key: 2,
                category: 'Chest Physiotherapy',
                treatment: 'Power Trainer',
                documentation: 'Power Trainer',
                barcodeNo: 8880002,
                active: true,
            },
            {
                key: 3,
                category: 'Electrotherapy / Traction',
                treatment: 'Shoulder Board',
                documentation: 'Shoulder Board',
                barcodeNo: 8880003,
                active: true,
            },
            {
                key: 4,
                category: 'Functional Capacity Evaluation',
                treatment: 'Cycle',
                documentation: 'Cycle',
                barcodeNo: 8880004,
                active: true,
            },
            {
                key: 5,
                category: 'Functional Training',
                treatment: 'Double Prostretch',
                documentation: 'Double Prostretch',
                barcodeNo: 8880005,
                active: true,
            },
            {
                key: 6,
                category: 'Hydrotherapy',
                treatment: 'Balance Trainer',
                documentation: 'Balance Trainer',
                barcodeNo: 8880006,
                active: true,
            },
        ],
    },
    {
        key: 15,
        name: 'Extra Rehab Setting',
        active: true,
        details: [
            {
                key: 1,
                category: 'Acupuncture',
                treatment: 'APT 2',
                documentation: 'APT 2',
                barcodeNo: 8880001,
                active: true,
            },
            {
                key: 2,
                category: 'Chest Physiotherapy',
                treatment: 'Power Trainer',
                documentation: 'Power Trainer',
                barcodeNo: 8880002,
                active: true,
            },
            {
                key: 3,
                category: 'Electrotherapy / Traction',
                treatment: 'Shoulder Board',
                documentation: 'Shoulder Board',
                barcodeNo: 8880003,
                active: true,
            },
            {
                key: 4,
                category: 'Functional Capacity Evaluation',
                treatment: 'Cycle',
                documentation: 'Cycle',
                barcodeNo: 8880004,
                active: true,
            },
            {
                key: 5,
                category: 'Functional Training',
                treatment: 'Double Prostretch',
                documentation: 'Double Prostretch',
                barcodeNo: 8880005,
                active: true,
            },
            {
                key: 6,
                category: 'Hydrotherapy',
                treatment: 'Balance Trainer',
                documentation: 'Balance Trainer',
                barcodeNo: 8880006,
                active: true,
            },
        ],
    },
    {
        key: 16,
        name: 'Extra Rehab Setting',
        active: true,
        details: [
            {
                key: 1,
                category: 'Acupuncture',
                treatment: 'APT 2',
                documentation: 'APT 2',
                barcodeNo: 8880001,
                active: true,
            },
            {
                key: 2,
                category: 'Chest Physiotherapy',
                treatment: 'Power Trainer',
                documentation: 'Power Trainer',
                barcodeNo: 8880002,
                active: true,
            },
            {
                key: 3,
                category: 'Electrotherapy / Traction',
                treatment: 'Shoulder Board',
                documentation: 'Shoulder Board',
                barcodeNo: 8880003,
                active: true,
            },
            {
                key: 4,
                category: 'Functional Capacity Evaluation',
                treatment: 'Cycle',
                documentation: 'Cycle',
                barcodeNo: 8880004,
                active: true,
            },
            {
                key: 5,
                category: 'Functional Training',
                treatment: 'Double Prostretch',
                documentation: 'Double Prostretch',
                barcodeNo: 8880005,
                active: true,
            },
            {
                key: 6,
                category: 'Hydrotherapy',
                treatment: 'Balance Trainer',
                documentation: 'Balance Trainer',
                barcodeNo: 8880006,
                active: true,
            },
        ],
    },
    {
        key: 17,
        name: 'Extra Rehab Setting',
        active: true,
        details: [
            {
                key: 1,
                category: 'Acupuncture',
                treatment: 'APT 2',
                documentation: 'APT 2',
                barcodeNo: 8880001,
                active: true,
            },
            {
                key: 2,
                category: 'Chest Physiotherapy',
                treatment: 'Power Trainer',
                documentation: 'Power Trainer',
                barcodeNo: 8880002,
                active: true,
            },
            {
                key: 3,
                category: 'Electrotherapy / Traction',
                treatment: 'Shoulder Board',
                documentation: 'Shoulder Board',
                barcodeNo: 8880003,
                active: true,
            },
            {
                key: 4,
                category: 'Functional Capacity Evaluation',
                treatment: 'Cycle',
                documentation: 'Cycle',
                barcodeNo: 8880004,
                active: true,
            },
            {
                key: 5,
                category: 'Functional Training',
                treatment: 'Double Prostretch',
                documentation: 'Double Prostretch',
                barcodeNo: 8880005,
                active: true,
            },
            {
                key: 6,
                category: 'Hydrotherapy',
                treatment: 'Balance Trainer',
                documentation: 'Balance Trainer',
                barcodeNo: 8880006,
                active: true,
            },
        ],
    },
    {
        key: 18,
        name: 'Extra Rehab Setting',
        active: true,
        details: [
            {
                key: 1,
                category: 'Acupuncture',
                treatment: 'APT 2',
                documentation: 'APT 2',
                barcodeNo: 8880001,
                active: true,
            },
            {
                key: 2,
                category: 'Chest Physiotherapy',
                treatment: 'Power Trainer',
                documentation: 'Power Trainer',
                barcodeNo: 8880002,
                active: true,
            },
            {
                key: 3,
                category: 'Electrotherapy / Traction',
                treatment: 'Shoulder Board',
                documentation: 'Shoulder Board',
                barcodeNo: 8880003,
                active: true,
            },
            {
                key: 4,
                category: 'Functional Capacity Evaluation',
                treatment: 'Cycle',
                documentation: 'Cycle',
                barcodeNo: 8880004,
                active: true,
            },
            {
                key: 5,
                category: 'Functional Training',
                treatment: 'Double Prostretch',
                documentation: 'Double Prostretch',
                barcodeNo: 8880005,
                active: true,
            },
            {
                key: 6,
                category: 'Hydrotherapy',
                treatment: 'Balance Trainer',
                documentation: 'Balance Trainer',
                barcodeNo: 8880006,
                active: true,
            },
        ],
    },
    {
        key: 19,
        name: 'Extra Rehab Setting',
        active: true,
        details: [
            {
                key: 1,
                category: 'Acupuncture',
                treatment: 'APT 2',
                documentation: 'APT 2',
                barcodeNo: 8880001,
                active: true,
            },
            {
                key: 2,
                category: 'Chest Physiotherapy',
                treatment: 'Power Trainer',
                documentation: 'Power Trainer',
                barcodeNo: 8880002,
                active: true,
            },
            {
                key: 3,
                category: 'Electrotherapy / Traction',
                treatment: 'Shoulder Board',
                documentation: 'Shoulder Board',
                barcodeNo: 8880003,
                active: true,
            },
            {
                key: 4,
                category: 'Functional Capacity Evaluation',
                treatment: 'Cycle',
                documentation: 'Cycle',
                barcodeNo: 8880004,
                active: true,
            },
            {
                key: 5,
                category: 'Functional Training',
                treatment: 'Double Prostretch',
                documentation: 'Double Prostretch',
                barcodeNo: 8880005,
                active: true,
            },
            {
                key: 6,
                category: 'Hydrotherapy',
                treatment: 'Balance Trainer',
                documentation: 'Balance Trainer',
                barcodeNo: 8880006,
                active: true,
            },
        ],
    },
    {
        key: 20,
        name: 'Extra Rehab Setting',
        active: true,
        details: [
            {
                key: 1,
                category: 'Acupuncture',
                treatment: 'APT 2',
                documentation: 'APT 2',
                barcodeNo: 8880001,
                active: true,
            },
            {
                key: 2,
                category: 'Chest Physiotherapy',
                treatment: 'Power Trainer',
                documentation: 'Power Trainer',
                barcodeNo: 8880002,
                active: true,
            },
            {
                key: 3,
                category: 'Electrotherapy / Traction',
                treatment: 'Shoulder Board',
                documentation: 'Shoulder Board',
                barcodeNo: 8880003,
                active: true,
            },
            {
                key: 4,
                category: 'Functional Capacity Evaluation',
                treatment: 'Cycle',
                documentation: 'Cycle',
                barcodeNo: 8880004,
                active: true,
            },
            {
                key: 5,
                category: 'Functional Training',
                treatment: 'Double Prostretch',
                documentation: 'Double Prostretch',
                barcodeNo: 8880005,
                active: true,
            },
            {
                key: 6,
                category: 'Hydrotherapy',
                treatment: 'Balance Trainer',
                documentation: 'Balance Trainer',
                barcodeNo: 8880006,
                active: true,
            },
        ],
    },
];

const categorySelectItem = [
    {
        category_name: 'Acupuncture',
        category_value: 'Acupuncture',
    },
    {
        category_name: 'Chest Physiotherapy',
        category_value: 'Chest Physiotherapy',
    },
    {
        category_name: 'Electrotherapy / Traction',
        category_value: 'Electrotherapy / Traction',
    },
    {
        category_name: 'Functional Capacity Evaluation',
        category_value: 'Functional Capacity Evaluation',
    },
    {
        category_name: 'Functional Training',
        category_value: 'Functional Training',
    },
    {
        category_name: 'Hydrotherapy',
        category_value: 'Hydrotherapy',
    },
];

export {mockDate,categorySelectItem}
