const PREFFIX = 'ECS_INTERFACE';
export const REFRESH_STATUS = `${PREFFIX}_REFRESH_STATUS`;
export const SET_STATUS = `${PREFFIX}_SET_STATUS`;

export const CHECK_ECS = `${PREFFIX}_CHECK_ECS`;
export const CHECK_OCSSS = `${PREFFIX}_CHECK_OCSSS`;
export const CHECK_MWECS = `${PREFFIX}_CHECK_MWECS`;

export const SET_ECS_PATIENT_STATUS = `${PREFFIX}_SET_ECS_PATIENT_STATUS`;
export const SET_OCSSS_PATIENT_STATUS = `${PREFFIX}_SET_OCSSS_PATIENT_STATUS`;
export const SET_MWECS_PATIENT_STATUS = `${PREFFIX}_SET_MWECS_PATIENT_STATUS`;

export const SET_PATIENT_SUMMARY_ECS_PATIENT_STATUS = `${PREFFIX}_SET_PATIENT_SUMMARY_ECS_PATIENT_STATUS`;
export const SET_PATIENT_SUMMARY_OCSSS_PATIENT_STATUS = `${PREFFIX}_SET_PATIENT_SUMMARY_OCSSS_PATIENT_STATUS`;
export const SET_PATIENT_SUMMARY_MWECS_PATIENT_STATUS = `${PREFFIX}_SET_PATIENT_SUMMARY_MWECS_PATIENT_STATUS`;

export const SET_REG_ECS_PATIENT_STATUS = `${PREFFIX}_SET_REG_ECS_PATIENT_STATUS`;
export const SET_REG_OCSSS_PATIENT_STATUS = `${PREFFIX}_SET_REG_OCSSS_PATIENT_STATUS`;
export const SET_REG_MWECS_PATIENT_STATUS = `${PREFFIX}_SET_REG_MWECS_PATIENT_STATUS`;

export const RESET_ECS_PATIENT_STATUS = `${PREFFIX}_RESET_ECS_PATIENT_STATUS`;
export const RESET_OCSSS_PATIENT_STATUS = `${PREFFIX}_RESET_OCSSS_PATIENT_STATUS`;
export const RESET_MWECS_PATIENT_STATUS = `${PREFFIX}_RESET_MWECS_PATIENT_STATUS`;

export const SET_ECS_OPEN_DIALOG = `${PREFFIX}_SET_ECS_OPEN_DIALOG`;
export const SET_ECS_ACTIVE = `${PREFFIX}_SET_ECS_ACTIVE`;
export const SET_MWECS_OPEN_DIALOG = `${PREFFIX}_SET_MWECS_OPEN_DIALOG`;
export const SET_MWECS_ACTIVE = `${PREFFIX}_SET_MWECS_ACTIVE`;


export const OPEN_ECS_DIALOG = `${PREFFIX}_OPEN_ECS_DIALOG`;
export const CLOSE_ECS_DIALOG = `${PREFFIX}_CLOSE_ECS_DIALOG`;

export const OPEN_OCSSS_DIALOG = `${PREFFIX}_OPEN_OCSSS_DIALOG`;

export const OPEN_MWECS_DIALOG = `${PREFFIX}_OPEN_MWECS_DIALOG`;
export const CLOSE_MWECS_DIALOG = `${PREFFIX}_CLOSE_MWECS_DIALOG`;


export const PUT_GET_CODE_LIST = `${PREFFIX}_PUT_GET_CODE_LIST`;

export const SET_REG_PAGE_RESET_FLAG = `${PREFFIX}_SET_REG_PAGE_RESET_FLAG`;

export const SET_MWECS_INPUT = `${PREFFIX}_SET_MWECS_INPUT`;
export const SET_OCSSS_INPUT = `${PREFFIX}_SET_OCSSS_INPUT`;
export const SET_ECS_INPUT = `${PREFFIX}_SET_ECS_INPUT`;

export const REG_PAGE_KEY_FIELD_ON_BLUR = `${PREFFIX}_REG_PAGE_KEY_FIELD_ON_BLUR`;

export const SET_ECS_RESULT=`${PREFFIX}_SET_ECS_RESULT`;

export const SELECT_TWINS_RECORD=`${PREFFIX}_SELECT_TWINS_RECORD`;
