const PRE='ApptEnquiry';

export const RESET_ALL=`${PRE}_RESET_ALL`;
export const UPDATE_FIELD=`${PRE}_UPDATE_FIELD`;
export const FETCH_ENQUIRY_RESULT=`${PRE}_FETCH_ENQUIRY_RESULT`;
export const LOAD_ENQUIRY_RESULT=`${PRE}_LOAD_ENQUIRY_RESULT`;
export const PRINT_APPT_REPORT=`${PRE}_PRINT_APPT_REPORT`;