const PREFFIX = 'ALS_LOG';
export const ALS_LOG_FRONT_END_ACTION = `${PREFFIX}_FRONT_END_ACTION`;
export const ALS_LOG=`${PREFFIX}`;
export const ALS_LOG_AUDIT_ACTION = `${PREFFIX}_AUDIT_ACTION`;
export const ALS_LOG_CLEAR_HISTORY = `${PREFFIX}_CLEAR_HISTORY`;
export const ALS_LOG_AUDIT_ERROR = `${PREFFIX}_AUDIT_ERROR`;

