const PRE = 'EHS_SPA_CONTROL';

export const RESET = `${PRE}_RESET`;

export const UPDATE_STATE = `${PRE}_UPDATE_STATE`;

export const SEARCH_PATIENTS = `${PRE}_SEARCH_PATIENTS`;

export const CLOSE_EHS_PMI_SEARCH_DIALOG = `${PRE}_CLOSE_EHS_PMI_SEARCH_DIALOG`;

export const OPEN_EHS_PRINT_APPT_LIST_DIALOG = `${PRE}_OPEN_EHS_PRINT_APPT_LIST_DIALOG`;
export const CLOSE_EHS_PRINT_APPT_LIST_DIALOG = `${PRE}_CLOSE_EHS_PRINT_APPT_LIST_DIALOG`;
