const PRE = 'DTS_PATIENT';

export const INITI_PAGE = `${PRE}_INITI_PAGE`;
export const PUT_DEFAULT_ROOM = `${PRE}_PUT_DEFAULT_ROOM`;
export const DELETE_DEFAULT_ROOM = `${PRE}_DELETE_DEFAULT_ROOM`;
export const PUT_DEFAULT_ROOM_LIST = `${PRE}_PUT_DEFAULT_ROOM_LIST`;
export const GET_DEFAULT_ROOM = `${PRE}_GET_DEFAULT_ROOM`;
export const GET_DEFAULT_ROOM_LIST = `${PRE}_GET_DEFAULT_ROOM_LIST`;
export const GET_DEFAULT_ROOM_LOG_LIST = `${PRE}_GET_DEFAULT_ROOM_LOG_LIST`;
export const GET_GD_DEFAULT_ROOM = `${PRE}_GET_GD_DEFAULT_ROOM`;
export const RESET_ALL = `${PRE}_RESET_ALL`;
export const UPDATE_STATE = `${PRE}_UPDATE_STATE`;
export const RESET_DIALOGINFO = `${PRE}_RESET_DIALOGINFO`;
// export const DELETE_SUCCESS = `${PRE}_DELETE_SUCCESS`;
// export const SAVE_SUCCESS = `${PRE}_SAVE_SUCCESS`;
