const PREFFIX = 'DTS_PATIENT_SUMMARY';

export const SET_REDIRECT = `${PREFFIX}_SET_REDIRECT`;
export const GET_CHANGE_FORM = `${PREFFIX}_GET_CHANGE_FORM`;
export const GET_PMI_LABEL = `${PREFFIX}_GET_PMI_LABEL`;
export const UPDATE_STATE = `${PREFFIX}_UPDATE_STATE`;
export const RESET_ALL = `${PREFFIX}_RESET_ALL`;
export const GET_DH65_LABEL = `${PREFFIX}_GET_DH65_LABEL`;
export const GET_APPOINTMENT_LABEL = `${PREFFIX}_GET_APPOINTMENT_LABEL`;
export const GET_APPOINTMENT_SLIP = `${PREFFIX}_GET_APPOINTMENT_SLIP`;

export const OPEN_PREVIEW_WINDOW = `${PREFFIX}_OPEN_PREVIEW_WINDOW`;
export const SEARCH_PATIENT = `${PREFFIX}_SEARCH_PATIENT`;
export const GET_ENCOUNTER_HISTORY = `${PREFFIX}_GET_ENCOUNTER_HISTORY`;

//SET
export const SET_ADDRESS_LABEL = `${PREFFIX}_SET_ADDRESS_LABEL`;
export const SET_ADDRESS_LABEL_LIST = `${PREFFIX}_SET_ADDRESS_LABEL_LIST`;

//SAGA
export const SEARCH_PATIENT_SAGA = `${PREFFIX}_SEARCH_PATIENT_SAGA`;