const PREFFIX = 'DTS_PATIENT_SEARCH';

export const SET_SEARCH_PARAMS = `${PREFFIX}_SET_SEARCH_PARAMS`;
export const RESET_BY_ID = `${PREFFIX}_RESET_BY_ID`;
export const SEARCH_PATIENT = `${PREFFIX}_SEARCH_PATIENT`;
export const SEARCH_PATIENT_SAGA = `${PREFFIX}_SEARCH_PATIENT_SAGA`;
export const SET_SELECTED_PATIENT = `${PREFFIX}_SET_SELECTED_PATIENT`;
export const SET_PUC_PARAMS = `${PREFFIX}_SET_PUC_PARAMS`;