export const PAGESTATUS = {
    CERT_VIEWING: 'CERT_VIEWING',
    CERT_ADDING: 'CERT_ADDING',
    CERT_EDITING: 'CERT_EDITING',
    CERT_SELECTED: 'CERT_SELECTED',
    CERT_PRINTING: 'CERT_PRINTING'
};

export const EFORM_RESULT_STATUS = {
    COMPLETED: 'C',
    INCOMPLETED: 'I',
    DELETED: 'D',
    REPLACED: 'R'
};
