export const PAGESTATUS = {
    SCANNER_CERT_VIEWING: 'SCANNER_CERT_VIEWING',
    CANNER_CERT_ADDING: 'CANNER_CERT_ADDING',
    CANNER_CERT_SELECTED: 'CANNER_CERT_SELECTED'
};

export const SCANNER_RESULT_STATUS = {
    COMPLETED: 'C',
    INCOMPLETED: 'I',
    DELETED: 'D',
    REPLACED: 'R'
};