import {
    cardiovascularRiskFactorsFollowUpRecord,
    pureToneAudiometryReferralForm,
    recordOfHealthScreening,
    hivAidsReportForm,
    tuberculosisNotification,
    reportToDhOnPoisoningOrCommunicableDiseases,
    mapPmi,
    mapAssessmentPmi
} from './eFormFunctionFCS';

import {
    defaulterTracingLetter,
    confinementLetter,
    antenatalReferralLetter,
    certificateOfAttendance,
    sickLeaveLetter,
    InformingHBsAg,
    InformingRubella,
    smokingCessationHotline,
    referralToIFSC
} from './eFormFunctionANT';

import {
    referralMemo,
    requestFormLabReport,
    consentFormContraceptive,
    dhHIV,
    consulationRequestReply,
    appointmentMemo,
    referralPWHLKS,
    referralTCO,
    referralGumClinic,
    referralContraceptiveClinic,
    referralPsychiatric,
    medicalReportAppFormCH,
    medicalReportAppFormEN,
    requestFormPhotocopyCN,
    requestFormPhotocopyEN,
    requestFormTDM,
    replyMemoTemplate,
    aELabResultRequestForm,
    iVUQuestionnaire,
    tPCReferralHBV,
    tpcAeReminder,
    patientPartcular,
    aeReply,
    neatsRequestForm,
    clinicalAdmissionForm,
    consentFormEN,
    consentFormCN,
    patientNote,
    patientInstructionCN,
    patientInstructionEN
} from './eFormFunctionSPP';

import {
    partnerNotificationRecord,
    consentFormChinese,
    consentFormEnglish,
    examConsent,
    referralConsultationRequest,
    bodyChartGeneral
} from './eFormFunctionSHS';

import {
    cgsReplyLetter,
    cgsReferralLetter,
    cgsLetterResultNormal,
    CGSConsentFormChinese,
    CGSConsentFormEnglish,
    cgsReportOfGeneticCounselling
} from './eFormFunctionCGS';

export const eFormFunction = {
    recordOfHealthScreening: recordOfHealthScreening,
    diabetesMellitusAnnualAssessmentForm: mapAssessmentPmi,
    hypertensionInitialAssessmentForm: mapAssessmentPmi,
    cardiovascularRiskFactorsFollowUpRecord: cardiovascularRiskFactorsFollowUpRecord,
    pureToneAudiometryReferralForm: pureToneAudiometryReferralForm,
    retinalPhotoReferralForm: mapPmi,
    hivAidsReportForm: hivAidsReportForm,
    tuberculosisNotification: tuberculosisNotification,
    notificationOfInfectiousDiseasesOtherThanTuberculosis: mapPmi,
    notificationOfOccupationalDiseases: mapPmi,
    reportToDhOnPoisoningOrCommunicableDiseases: reportToDhOnPoisoningOrCommunicableDiseases,
    smokingCessationRecordNrt: mapAssessmentPmi,
    smokingCessationRecordVarenicline: mapAssessmentPmi,
    defaulterTracingLetter: defaulterTracingLetter,
    confinementLetter: confinementLetter,
    antenatalReferralLetter: antenatalReferralLetter,
    certificateOfAttendance: certificateOfAttendance,
    sickLeaveLetter: sickLeaveLetter,
    referralMemo: referralMemo,
    partnerNotificationRecord: partnerNotificationRecord,
    consentFormChinese: consentFormChinese,
    consentFormEnglish: consentFormEnglish,
    examConsent: examConsent,
    referralConsultationRequest: referralConsultationRequest,
    bodyChartGeneral: bodyChartGeneral,
    scpTelFollowUp: mapAssessmentPmi,
    InformingHBsAg: InformingHBsAg,
    InformingRubella: InformingRubella,
    smokingCessationHotline:smokingCessationHotline,
    referralToIFSC:referralToIFSC,
    cgsReplyLetter:cgsReplyLetter,
    cgsReferralLetter:cgsReferralLetter,
    cgsLetterResultNormal:cgsLetterResultNormal,
    CGSConsentFormChinese: CGSConsentFormChinese,
    CGSConsentFormEnglish: CGSConsentFormEnglish,
    tpcAeReminder:tpcAeReminder,
    patientPartcular:patientPartcular,
    aeReply:aeReply,
    neatsRequestForm:neatsRequestForm,
    medicalReportAppFormCH:medicalReportAppFormCH,
    medicalReportAppFormEN:medicalReportAppFormEN,
    dhHIV:dhHIV,
    consulationRequestReply:consulationRequestReply,
    requestFormLabReport:requestFormLabReport,
    consentFormContraceptive: consentFormContraceptive,
    appointmentMemo:appointmentMemo,
    referralTCO: referralTCO,
    referralPWHLKS: referralPWHLKS,
    referralGumClinic: referralGumClinic,
    referralContraceptiveClinic: referralContraceptiveClinic,
    referralPsychiatric: referralPsychiatric,
    requestFormPhotocopyCN:requestFormPhotocopyCN,
    requestFormPhotocopyEN:requestFormPhotocopyEN,
    requestFormTDM:requestFormTDM,
    replyMemoTemplate: replyMemoTemplate,
    aELabResultRequestForm: aELabResultRequestForm,
    tPCReferralHBV:tPCReferralHBV,
    iVUQuestionnaire:iVUQuestionnaire,
    clinicalAdmissionForm: clinicalAdmissionForm,
    consentFormEN: consentFormEN,
    consentFormCN: consentFormCN,
    patientNote: patientNote,
    patientInstructionCN: patientInstructionCN,
    patientInstructionEN: patientInstructionEN,
    cgsReportOfGeneticCounselling: cgsReportOfGeneticCounselling
};
