const REDIRECT_ACTION_TYPE = {
    //PRINT_DH65_LABEL: 'Print DH65 label'
};

const CLINIC_CONFIGNAME = {
    APPOINTMENT_LIST_PRINT_QUEUE: 'PMI_APPOINTMENT_LABEL_PRINT_QUEUE',
    APPOINTMENT_LIST_PRINT_ORIENTATION: 'APPOINTMENT_LIST_PRINT_ORIENTATION',
    APPOINTMENT_LIST_PRINT_TRAY: 'APPOINTMENT_LIST_PRINT_TRAY',
    APPOINTMENT_LIST_PRINT_PAPER_SIZE: 'APPOINTMENT_LIST_PRINT_PAPER_SIZE'
};

export { REDIRECT_ACTION_TYPE, CLINIC_CONFIGNAME };
