const PREFFIX = 'DTS_ATTENDANCE_VIEW';

//GET
export const GET_CALENDAR_DETAIL_DATE = `${PREFFIX}_GET_CALENDAR_DETAIL_DATE`;
export const GET_ROOM_LIST = `${PREFFIX}_GET_ROOM_LIST`;
export const GET_DAILY_NOTE = `${PREFFIX}_GET_DAILY_NOTE`;
export const GET_DAILY_NOTE_SAGA = `${PREFFIX}_GET_DAILY_NOTE_SAGA`;
export const GET_ROOM_OFFICER = `${PREFFIX}_GET_ROOM_OFFICER`;
export const GET_DAILY_VIEW = `${PREFFIX}_GET_DAILY_VIEW`;
export const GET_PATIENT_BY_HKID = `${PREFFIX}_GET_PATIENT_BY_HKID`;
export const GET_PATIENT_BY_IDS = `${PREFFIX}_GET_PATIENT_BY_IDS`;
export const GET_APPOINTMENT_TASK = `${PREFFIX}_GET_APPOINTMENT_TASK`;
export const GET_SERVE_ROOM = `${PREFFIX}_GET_SERVE_ROOM`;
export const GET_ANA_CODE = `${PREFFIX}_GET_ANA_CODE`;
export const GET_ATTENDANCE = `${PREFFIX}_GET_ATTENDANCE`;

//SET
export const SET_CALENDAR_DETAIL_DATE = `${PREFFIX}_SET_CALENDAR_DETAIL_DATE`;
export const SET_SELECTED_CLINIC = `${PREFFIX}_SET_SELECTED_CLINIC`;
export const SET_SELECTED_ROOM = `${PREFFIX}_SET_SELECTED_ROOM`;

export const SET_SELECTED_FILTER_CLINICAL_STATUS = `${PREFFIX}_SET_SELECTED_FILTER_CLINICAL_STATUS`;
export const SET_SELECTED_FILTER_ENCOUNTER_TYPE_CODE = `${PREFFIX}_SET_SELECTED_FILTER_ENCOUNTER_TYPE_CODE`;
export const SET_SELECTED_FILTER_ATTENDANCE_STATUS = `${PREFFIX}_SET_SELECTED_FILTER_ATTENDANCE_STATUS`;
export const SET_SELECTED_FILTER_INFECTION_CONTROL_DISPLAY = `${PREFFIX}_SET_SELECTED_FILTER_INFECTION_CONTROL_DISPLAY`;
export const SET_SELECTED_APPOINTMENT_TASK = `${PREFFIX}_SET_SELECTED_APPOINTMENT_TASK`;
export const SET_PATIENT_KEY = `${PREFFIX}_SET_PATIENT_KEY`;
export const SET_PATIENT_KEY_N_APPOINTMENT = `${PREFFIX}_SET_PATIENT_KEY_N_APPOINTMENT`;
export const SET_SELECTED_PATIENT_ECS_RESULT = `${PREFFIX}_SET_SELECTED_PATIENT_ECS_RESULT`;

export const SET_ATTENDANCE_ALERT_SETTINGS = `${PREFFIX}_ATTENDANCE_ALERT_SETTINGS`;


//UPDATE
export const UPDATE_DAILY_NOTE = `${PREFFIX}_UPDATE_DAILY_NOTE`;
export const UPDATE_ARRIVAL_TIME = `${PREFFIX}_UPDATE_ARRIVAL_TIME`;
export const REVOKE_ATTENDANCE = `${PREFFIX}_REVOKE_ATTENDANCE`;

//INSERT
export const CONFIRM_ATTENDANCE = `${PREFFIX}_CONFIRM_ATTENDANCE`;

//Saga
export const GET_ROOM_LIST_SAGA = `${PREFFIX}_GET_ROOM_LIST_SAGA`;
export const GET_ROOM_OFFICER_SAGA = `${PREFFIX}_GET_ROOM_OFFICER_SAGA`;
export const GET_DAILY_VIEW_SAGA = `${PREFFIX}_GET_DAILY_VIEW_SAGA`;
export const GET_PATIENT_BY_HKID_SAGA = `${PREFFIX}_GET_PATIENT_BY_HKID_SAGA`;
export const GET_PATIENT_BY_IDS_SAGA = `${PREFFIX}_GET_PATIENT_BY_IDS_SAGA`;
export const GET_APPOINTMENT_TASK_SAGA = `${PREFFIX}_GET_APPOINTMENT_TASK_SAGA`;
export const CONFIRM_ATTENDANCE_SAGA = `${PREFFIX}_CONFIRM_ATTENDANCE_SAGA`;
export const GET_SERVE_ROOM_SAGA = `${PREFFIX}_GET_SERVE_ROOM_SAGA`;
//export const GET_ANA_CODE_SAGA = `${PREFFIX}_GET_ANA_CODE_SAGA`;
export const GET_ECS_PERMIT_REASON_LIST_SAGA = `${PREFFIX}_GET_ECS_PERMIT_REASON_LIST_SAGA`;
export const GET_ATTENDANCE_SAGA = `${PREFFIX}_GET_ATTENDANCE_SAGA`;

//reset
export const RESET_LOCATION_ENCOUNTER = `${PREFFIX}_RESET_LOCATION_ENCOUNTER`;
export const RESET_ALL = `${PREFFIX}_RESET_ALL`;
export const RESET_ATTENDANCE_FILTER = `${PREFFIX}_RESET_ATTENDANCE_FILTER`;
export const RESET_DAILY_NOTE = `${PREFFIX}_RESET_DAILY_NOTE`;
