const PREFFIX = 'DTS_APPOINTMENT_BOOKING';

//get
export const GET_DAILY_VIEW = `${PREFFIX}_GET_DAILY_VIEW`;
export const GET_MULTIPLE_DAILY_VIEW_FOR_EXPRESS = `${PREFFIX}_GET_MULTIPLE_DAILY_VIEW_FOR_EXPRESS`;
export const GET_AVAILABLE_CALENDAR_TIME_SLOT = `${PREFFIX}_GET_AVAILABLE_CALENDAR_TIME_SLOT`;
export const GET_AVAILABLE_CALENDAR_TIME_SLOT_EXPRESS = `${PREFFIX}_GET_AVAILABLE_CALENDAR_TIME_SLOT_EXPRESS`;
export const GET_ROOM_LIST = `${PREFFIX}_GET_ROOM_LIST`;
export const GET_ENCOUNTER_TYPE_LIST = `${PREFFIX}_GET_ENCOUNTER_TYPE_LIST`;
export const GET_SESSION_LIST = `${PREFFIX}_GET_SESSION_LIST`;
export const GET_DAILY_NOTE = `${PREFFIX}_GET_DAILY_NOTE`;
export const GET_CALENDAR_DETAIL_DATE = `${PREFFIX}_GET_CALENDAR_DETAIL_DATE`;
export const GET_FILTER_MODE = `${PREFFIX}_GET_FILTER_MODE`;
export const GET_PATIENT_APPOINTMENT = `${PREFFIX}_GET_PATIENT_APPOINTMENT`;
export const GET_AVAILABLE_TIME_SLOT_LIST = `${PREFFIX}_GET_AVAILABLE_TIME_SLOT_LIST`;
export const GET_CALENDAR_DETAIL_MTH = `${PREFFIX}_GET_CALENDAR_DETAIL_MTH`;
export const GET_URGENT_ROOM_LIST = `${PREFFIX}_GET_URGENT_ROOM_LIST`;
export const GET_GP_URGENT_ROOM_LIST = `${PREFFIX}_GET_GP_URGENT_ROOM_LIST`;
export const GET_UNAVAILABLE_REASONS = `${PREFFIX}_GET_UNAVAILABLE_REASONS`;
export const GET_DELETE_REASONS = `${PREFFIX}_GET_DELETE_REASONS`;
export const GET_BOOKING_ALERT = `${PREFFIX}_GET_BOOKING_ALERT`;
export const GET_APPOINTMENT_LABEL = `${PREFFIX}_GET_APPOINTMENT_LABEL`;
export const GET_APPOINTMENT_LOG = `${PREFFIX}_GET_APPOINTMENT_LOG`;
export const GET_TIMESLOT_LOG = `${PREFFIX}_GET_TIMESLOT_LOG`;
export const GET_SERVE_ROOM = `${PREFFIX}_GET_SERVE_ROOM`;
export const GET_DISCIPLINES = `${PREFFIX}_GET_DISCIPLINES`;
export const GET_REFERRAL_LIST = `${PREFFIX}_GET_REFERRAL_LIST`;
export const GET_REFERRAL_DEFAULT_ROOM = `${PREFFIX}_GET_REFERRAL_DEFAULT_ROOM`;

//set
export const SET_CALENDAR_DETAIL_MTH = `${PREFFIX}_SET_CALENDAR_DETAIL_MTH`;
export const SET_APPOINTMENT_SEARCH_PANEL_TAB_VAL = `${PREFFIX}_SET_APPOINTMENT_SEARCH_PANEL_TAB_VAL`;
export const SET_SELECTED_CLINIC = `${PREFFIX}_SET_SELECTED_CLINIC`;
export const SET_SELECTED_ROOM = `${PREFFIX}_SET_SELECTED_ROOM`;
export const SET_SELECTED_ENCOUNTER_TYPE = `${PREFFIX}SET_SELECTED_ENCOUNTER_TYPE`;
export const SET_DURATION = `${PREFFIX}SET_DURATION`;
export const SET_CALENDAR_DETAIL_DATE = `${PREFFIX}_SET_CALENDAR_DETAIL_DATE`;
export const SET_FILTER_MODE = `${PREFFIX}_SET_FILTER_MODE`;
export const SET_SELECTED_DAILY_VIEW_TIMESLOT_LIST = `${PREFFIX}_SET_SELECTED_DAILY_VIEW_TIMESLOT_LIST`;
export const SET_SQUEEZE_IN_MODE = `${PREFFIX}_SET_SQUEEZE_IN_MODE`;
export const SET_PAGE_STATUS = `${PREFFIX}_SET_PAGE_STATUS`;
export const SET_SELECTED_RESCHEDULE_APPOINTMENT = `${PREFFIX}_SET_SELECTED_RESCHEDULE_APPOINTMENT`;
export const SET_SELECTED_DAY_TIMESLOT_LIST = `${PREFFIX}_SET_SELECTED_DAY_TIMESLOT_LIST`;
export const SET_MULTIPLE_BOOKING_MODE = `${PREFFIX}_SET_MULTIPLE_BOOKING_MODE`;
export const SET_EXPRESS_BOOKING_MODE = `${PREFFIX}_SET_EXPRESS_BOOKING_MODE`;
// export const SET_BOOKING_MODE = `${PREFFIX}_SET_BOOKING_MODE`;
export const SET_EXPRESS_EDIT_MODE = `${PREFFIX}_SET_EXPRESS_EDIT_MODE`;
export const SET_EXPRESS_DATE_LIST = `${PREFFIX}_SET_EXPRESS_DATE_LIST`;
export const SET_SELECTED_DELETE_APPOINTMENT = `${PREFFIX}_SET_SELECTED_DELETE_APPOINTMENT`;
export const SET_EMPTY_TIMESLOT_DATE_LIST = `${PREFFIX}_SET_EMPTY_TIMESLOT_DATE_LIST`;
export const SET_SELECTED_CLOSE_TIMESLOT = `${PREFFIX}_SET_SELECTED_CLOSE_TIMESLOT`;
export const SET_DAILY_VIEW_NAVIGATION_HISTORY = `${PREFFIX}_SET_DAILY_VIEW_NAVIGATION_HISTORY`;
export const SET_APPOINTMENT_LOG = `${PREFFIX}_SET_APPOINTMENT_LOG`;
export const SET_TIMESLOT_LOG = `${PREFFIX}_SET_TIMESLOT_LOG`;
export const SET_UTILIZATION_MODE = `${PREFFIX}_SET_UTILIZATION_MODE`;
export const SET_UNAVAILABLE_GP_URGENT_ROOM_LIST = `${PREFFIX}_SET_UNAVAILABLE_GP_URGENT_ROOM_LIST`;
export const SET_APPOINTMENT_MESSAGE_OBJ = `${PREFFIX}_SET_APPOINTMENT_MESSAGE_OBJ`;
export const SET_IS_UPDATED = `${PREFFIX}_SET_IS_UPDATED`;
export const SET_DISCIPLINES = `${PREFFIX}_SET_DISCIPLINES`;
export const SET_REFERRAL_LIST = `${PREFFIX}_SET_REFERRAL_LIST`;
export const SET_REFERRAL_SHOW_APPOINTMENT_ID = `${PREFFIX}_SET_REFERRAL_SHOW_APPOINTMENT_ID`;

//reset
export const RESET_CALENDAR_LIST = `${PREFFIX}_RESET_CALENDAR_LIST`;
export const RESET_LOCATION_ENCOUNTER = `${PREFFIX}_RESET_LOCATION_ENCOUNTER`;
export const RESET_SELECTED_DAILY_VIEW_TIMESLOT_LIST = `${PREFFIX}_RESET_SELECTED_DAILY_VIEW_TIMESLOT_LIST`;
export const RESET_ALL = `${PREFFIX}_RESET_ALL`;
export const RESET_DAILY_NOTE = `${PREFFIX}_RESET_DAILY_NOTE`;
export const RESET_CALENDAR_DETAIL_DATE = `${PREFFIX}_RESET_CALENDAR_DETAIL_DATE`;
export const RESET_AVAILABLE_TIME_SLOT_LIST = `${PREFFIX}_RESET_AVAILABLE_TIME_SLOT_LIST`;
export const RESET_URGENT_ROOM_LIST = `${PREFFIX}_RESET_URGENT_ROOM_LIST`;
export const RESET_GP_URGENT_ROOM_LIST = `${PREFFIX}_RESET_GP_URGENT_ROOM_LIST`;
export const RESET_SELECTED_RESCHEDULE_APPOINTMENT = `${PREFFIX}_RESET_SELECTED_RESCHEDULE_APPOINTMENT`;
export const RESET_SELECTED_CLOSE_TIMESLOT = `${PREFFIX}_RESET_SELECTED_CLOSE_TIMESLOT`;
//insert
export const INSERT_APPOINTMENT = `${PREFFIX}_INSERT_APPOINTMENT`;
export const INSERT_URGENT_APPOINTMENT = `${PREFFIX}_INSERT_URGENT_APPOINTMENT`;
export const INSERT_GP_URGENT_APPOINTMENT = `${PREFFIX}_INSERT_GP_URGENT_APPOINTMENT`;
export const INSERT_UNAVAILABLE_TIMESLOT = `${PREFFIX}_INSERT_UNAVAILABLE_TIMESLOT`;
//reschedule
export const RESCHEDULE_APPOINTMENT = `${PREFFIX}_RESCHEDULE_APPOINTMENT`;

//Delete
export const DELETE_UNAVAILABLE_PERIOD = `${PREFFIX}_DELETE_UNAVAILABLE_PERIOD`;
export const DELETE_APPOINTMENT = `${PREFFIX}_DELETE_APPOINTMENT`;

//get saga
export const GET_DAILY_VIEW_SAGA = `${PREFFIX}_GET_DAILY_VIEW_SAGA`;
export const GET_MULTIPLE_DAILY_VIEW_FOR_EXPRESS_SAGA = `${PREFFIX}_GET_MULTIPLE_DAILY_VIEW_FOR_EXPRESS_SAGA`;
export const GET_PATIENT_APPOINTMENT_SAGA = `${PREFFIX}_GET_PATIENT_APPOINTMENT_SAGA`;
export const GET_ROOM_LIST_SAGA = `${PREFFIX}_GET_ROOM_LIST_SAGA`;
export const GET_ENCOUNTER_TYPE_LIST_SAGA = `${PREFFIX}_GET_ENCOUNTER_TYPE_LIST_SAGA`;
export const GET_SESSION_LIST_SAGA = `${PREFFIX}_GET_SESSION_LIST_SAGA`;
export const GET_DAILY_NOTE_SAGA = `${PREFFIX}_GET_DAILY_NOTE_SAGA`;
export const GET_AVAILABLE_CALENDAR_TIME_SLOT_SAGA = `${PREFFIX}_GET_AVAILABLE_CALENDAR_TIME_SLOT_SAGA`;
export const GET_AVAILABLE_CALENDAR_TIME_SLOT_EXPRESS_SAGA = `${PREFFIX}_GET_AVAILABLE_CALENDAR_TIME_SLOT_EXPRESS_SAGA`;
export const GET_AVAILABLE_TIME_SLOT_LIST_SAGA = `${PREFFIX}_GET_AVAILABLE_TIME_SLOT_LIST_SAGA`;
export const GET_URGENT_ROOM_LIST_SAGA = `${PREFFIX}_GET_URGENT_ROOM_LIST_SAGA`;
export const GET_GP_URGENT_ROOM_LIST_SAGA = `${PREFFIX}_GET_GP_URGENT_ROOM_LIST_SAGA`;
export const GET_UNAVAILABLE_REASONS_SAGA = `${PREFFIX}_GET_UNAVAILABLE_REASONS_SAGA`;
export const GET_DELETE_REASONS_SAGA = `${PREFFIX}_GET_DELETE_REASONS_SAGA`;
export const GET_BOOKING_ALERT_SAGA = `${PREFFIX}_GET_BOOKING_ALERT_SAGA`;
export const GET_APPOINTMENT_LABEL_SAGA = `${PREFFIX}_GET_APPOINTMENT_LABEL_SAGA`;
export const GET_SERVE_ROOM_SAGA = `${PREFFIX}_GET_SERVE_ROOM_SAGA`;

//insert saga
export const INSERT_APPOINTMENT_SAGA = `${PREFFIX}_INSERT_APPOINTMENT_SAGA`;
export const INSERT_URGENT_APPOINTMENT_SAGA = `${PREFFIX}_INSERT_URGENT_APPOINTMENT_SAGA`;
export const INSERT_UNAVAILABLE_TIMESLOT_SAGA = `${PREFFIX}_INSERT_UNAVAILABLE_TIMESLOT_SAGA`;


//put saga
export const PUT_UNAVAILABLE_REASONS = `${PREFFIX}_PUT_UNAVAILABLE_REASONS`;
export const REASSIGN_URGENT_APPOINTMENT = `${PREFFIX}_REASSIGN_URGENT_APPOINTMENT`;
export const REASSIGN_GP_URGENT_APPOINTMENT = `${PREFFIX}_REASSIGN_GP_URGENT_APPOINTMENT`;

//UPDATE
export const UPDATE_DAILY_NOTE = `${PREFFIX}_UPDATE_DAILY_NOTE`;
export const UPDATE_APPOINTMENT = `${PREFFIX}_UPDATE_APPOINTMENT`;

//Reserve List
export const SAVE_TO_RESERVE_LIST = `${PREFFIX}_SAVE_TO_RESERVE_LIST`;
export const REMOVE_FROM_RESERVE_LIST = `${PREFFIX}_REMOVE_FROM_RESERVE_LIST`;
export const RESERVE_LIST_UPDATED = `${PREFFIX}_RESERVE_LIST_UPDATED`;