const PREFFIX = 'DTS_EMPTY_TIMESLOT_VIEW';

export const UPDATE_STATE = `${PREFFIX}_UPDATE_STATE`;

//GET
export const GET_EMPTY_TIMESLOT_LIST = `${PREFFIX}_GET_EMPTY_TIMESLOT_LIST`;
export const GET_ROOM_LIST = `${PREFFIX}_GET_ROOM_LIST`;
export const GET_UNAVAILABLE_APPOINTMENTS = `${PREFFIX}_GET_UNAVAILABLE_APPOINTMENTS`;
export const GET_RESERVE_LIST = `${PREFFIX}_GET_RESERVE_LIST`;
export const GET_RESERVE_LIST_REPORT = `${PREFFIX}_GET_RESERVE_LIST_REPORT`;

//SET
export const SET_CALENDAR_DETAIL_DATE1 = `${PREFFIX}_SET_CALENDAR_DETAIL_DATE1`;
export const SET_CALENDAR_DETAIL_DATE2 = `${PREFFIX}_SET_CALENDAR_DETAIL_DATE2`;
export const SET_SELECTED_CLINIC = `${PREFFIX}_SET_SELECTED_CLINIC`;
export const SET_SELECTED_ROOM_LIST = `${PREFFIX}_SET_SELECTED_ROOM_LIST`;
export const SET_SELECTED_EMPTY_TIMESLOT_LIST = `${PREFFIX}_SET_SELECTED_EMPTY_TIMESLOT_LIST`;
export const SET_SELECTED_EMPTY_TIMESLOT = `${PREFFIX}_SET_SELECTED_EMPTY_TIMESLOT`;
export const SET_SELECTED_APPOINTMENT = `${PREFFIX}_SET_SELECTED_APPOINTMENT`;
export const SET_REDIRECT = `${PREFFIX}_SET_REDIRECT`;


//SAGA
export const GET_EMPTY_TIMESLOT_LIST_SAGA = `${PREFFIX}_GET_EMPTY_TIMESLOT_LIST_SAGA`;
export const GET_ROOM_LIST_SAGA = `${PREFFIX}_GET_ROOM_LIST_SAGA`;
export const GET_UNAVAILABLE_APPOINTMENTS_SUCCESS = `${PREFFIX}_GET_UNAVAILABLE_APPOINTMENTS_SUCCESS`;
export const GET_RESERVE_LIST_SUCCESS = `${PREFFIX}_GET_RESERVE_LIST_SUCCESS`;
export const GET_RESERVE_LIST_REPORT_SAGA = `${PREFFIX}_GET_RESERVE_LIST_REPORT_SAGA`;

//RESET
export const RESET_ALL = `${PREFFIX}_RESET_ALL`;
export const RESET_RESERVE_LIST_REPORT = `${PREFFIX}_RESET_RESERVE_LIST_REPORT`;