const PREFFIX = 'DTS_REMIND_APPOINTMENT_VIEW';

//GET
export const GET_CALENDAR_DETAIL_DATE1 = `${PREFFIX}_GET_CALENDAR_DETAIL_DATE1`;
export const GET_CALENDAR_DETAIL_DATE2 = `${PREFFIX}_GET_CALENDAR_DETAIL_DATE2`;
export const GET_ROOM_LIST = `${PREFFIX}_GET_ROOM_LIST`;
export const GET_ROOM_OFFICER = `${PREFFIX}_GET_ROOM_OFFICER`;
export const GET_ONLY_NEED_REMINDER = `${PREFFIX}_GET_ONLY_NEED_REMINDER`;
export const GET_REMIND_APPOINTMENT_LIST = `${PREFFIX}_GET_REMIND_APPOINTMENT_LIST`;
export const GET_SERVE_ROOM = `${PREFFIX}_GET_SERVE_ROOM`;
export const GET_CONTACT_HISTORY_LIST = `${PREFFIX}_GET_CONTACT_HISTORY_LIST`;
export const GET_REMINDER_TEMPLATE = `${PREFFIX}_GET_REMINDER_TEMPLATE`;
export const GET_REMIND_APPOINTMENT_LIST_REPORT = `${PREFFIX}_GET_REMIND_APPOINTMENT_LIST_REPORT`;

//SET
export const SET_CALENDAR_DETAIL_DATE1 = `${PREFFIX}_SET_CALENDAR_DETAIL_DATE1`;
export const SET_CALENDAR_DETAIL_DATE2 = `${PREFFIX}_SET_CALENDAR_DETAIL_DATE2`;
export const SET_SELECTED_CLINIC = `${PREFFIX}_SET_SELECTED_CLINIC`;
export const SET_SELECTED_ROOM_LIST = `${PREFFIX}_SET_SELECTED_ROOM_LIST`;
export const SET_ONLY_NEED_REMINDER = `${PREFFIX}_SET_ONLY_NEED_REMINDER`;
export const SET_SELECTED_ROOMS = `${PREFFIX}_SET_SELECTED_ROOMS`;
export const SET_SELECTED_DATE_START = `${PREFFIX}_SET_SELECTED_DATE_START`;
export const SET_SELECTED_DATE_END = `${PREFFIX}_SET_SELECTED_DATE_END`;

export const SET_SELECTED_APPOINTMENT_TASK = `${PREFFIX}_SET_SELECTED_APPOINTMENT_TASK`;
export const SET_REMIND_APPOINTMENT_LIST_REPORT = `${PREFFIX}_SET_REMIND_APPOINTMENT_LIST_REPORT`;

//Saga
export const GET_ROOM_LIST_SAGA = `${PREFFIX}_GET_ROOM_LIST_SAGA`;
export const GET_REMIND_APPOINTMENT_LIST_SAGA = `${PREFFIX}_GET_REMIND_APPOINTMENT_LIST_SAGA`;
export const GET_SERVE_ROOM_SAGA = `${PREFFIX}_GET_SERVE_ROOM_SAGA`;
export const GET_CONTACT_HISTORY_LIST_SAGA = `${PREFFIX}_GET_CONTACT_HISTORY_LIST_SAGA`;
export const GET_REMINDER_TEMPLATE_SAGA = `${PREFFIX}_GET_REMINDER_TEMPLATE_SAGA`;

//reset
export const RESET_LOCATION_ENCOUNTER = `${PREFFIX}_RESET_LOCATION_ENCOUNTER`;
export const RESET_ALL = `${PREFFIX}_RESET_ALL`;
export const RESET_REMIND_APPOINTMENT_LIST_REPORT = `${PREFFIX}_RESET_REMIND_APPOINTMENT_LIST_REPORT`;


/*
    Contact History Dialog
*/

//get
//export const GET_CALENDAR_DETAIL_MTH = `${PREFFIX}_GET_CALENDAR_DETAIL_MTH`;

//set
//export const SET_CALENDAR_DETAIL_MTH = `${PREFFIX}_SET_CALENDAR_DETAIL_MTH`;

//reset
//export const RESET_LOCATION_ENCOUNTER = `${PREFFIX}_RESET_LOCATION_ENCOUNTER`;
//export const RESET_ALL = `${PREFFIX}_RESET_ALL`;

export const INSERT_CONTACT_HISTORY = `${PREFFIX}_INSERT_CONTACT_HISTORY`;
export const INSERT_CONTACT_HISTORIES = `${PREFFIX}_INSERT_CONTACT_HISTORIES`;
export const UPDATE_CONTACT_HISTORY = `${PREFFIX}_UPDATE_CONTACT_HISTORY`;
export const GET_CONTACT_HISTORY = `${PREFFIX}_GET_CONTACT_HISTORY`;
// export const GET_TEL_NOTES_CODE = `${PREFFIX}_GET_TEL_NOTES_CODE`;

//insert saga
export const INSERT_CONTACT_HISTORY_SAGA = `${PREFFIX}_INSERT_CONTACT_HISTORY_SAGA`;
export const UPDATE_CONTACT_HISTORY_SAGA = `${PREFFIX}_UPDATE_CONTACT_HISTORY_SAGA`;
export const DELETE_CONTACT_HISTORY = `${PREFFIX}_DELETE_CONTACT_HISTORY`;

export const GET_TEL_NOTES_CODE_SAGA = `${PREFFIX}_GET_TEL_NOTES_CODE_SAGA`;
export const GET_MAIL_NOTES_CODE_SAGA = `${PREFFIX}_GET_MAIL_NOTES_CODE_SAGA`;


//reset
export const RESET_CONTACT_HISTORY_DIALOG = `${PREFFIX}_RESET_CONTACT_HISTORY_DIALOG`;
