const PREFFIX = 'DTS_WAITING_LIST_VIEW';

//GET
export const GET_WAITING_LIST = `${PREFFIX}_GET_WAITING_LIST`;
export const GET_ROOM_LIST = `${PREFFIX}_GET_ROOM_LIST`;

//SET
export const UPDATE_WAITING_LIST = `${PREFFIX}_UPDATE_WAITING_LIST`;

//INSERT
export const INSERT_WAITING_LIST = `${PREFFIX}_INSERT_WAITING_LIST`;

//SAGA
export const GET_WAITING_LIST_SAGA = `${PREFFIX}_GET_WAITING_LIST_SAGA`;
export const INSERT_WAITING_LIST_SAGA = `${PREFFIX}_INSERT_WAITING_LIST_SAGA`;
export const GET_ROOM_LIST_SAGA = `${PREFFIX}_GET_ROOM_LIST_SAGA`;

//RESET
export const RESET_ALL = `${PREFFIX}_RESET_ALL`;