const PREFFIX = 'EHR';

export const PUT_EHR_EPMI = `${PREFFIX}_PUT_EHR_EPMI`;
export const GET_EHR_EPMI = `${PREFFIX}_GET_EHR_EPMI`;

export const CLOSE_EHR_IDENTITY_DIALOG = `${PREFFIX}_CLOSE_EHR_IDENTITY_DIALOG`;
export const OPEN_EHR_IDENTITY_DIALOG = `${PREFFIX}_OPEN_EHR_IDENTITY_DIALOG`;

export const RESET_ALL = `${PREFFIX}_RESET_ALL`;
export const KEEP_EHR_STATE = `${PREFFIX}_KEEP_EHR_STATE`;

export const UPDATE_PATIENT = `${PREFFIX}_UPDATE_PATIENT`;

export const PUT_PATINET_BY_ID = `${PREFFIX}_PUT_PATINET_BY_ID`;
export const GET_PATINET_BY_ID = `${PREFFIX}_GET_PATINET_BY_ID`;

export const GET_FROM_EHR_DATE = `${PREFFIX}_GET_FROM_EHR_DATE`;
export const UPDATE_FROM_EHR_DATE = `${PREFFIX}_UPDATE_FROM_EHR_DATE`;

export const UPDATE_EHR_PATIENT_STATUS = `${PREFFIX}_UPDATE_EHR_PATIENT_STATUS`;
