const PRE = 'OFFICERINCHARGE';

export const GET_OFFICER_DOCTOR_DROPDOWN_LIST = `${PRE}_GET_OFFICER_DOCTOR_DROPDOWN_LIST`;

export const SAVE_OFFICER_DOCTOR_LIST = `${PRE}_SAVE_OFFICER_DOCTOR_LIST`;

