const PRE = 'YELLOW_FEVER_EXEMPTION_LETTER';

export const RESET_ALL = `${PRE}_RESET_ALL`;
export const UPDATE_FIELD = `${PRE}_UPDATE_FIELD`;
//export const GET_SICK_LEAVE_CERT=`${PRE}_GET_SICK_LEAVE_CERT`;
export const SAVE_AND_PRINT_LETTER = `${PRE}_SAVE_AND_PRINT_LETTER`;

export const UPDATE_YELLOWFEVER_EXEMPT_CERTIFICATE = `${PRE}_UPDATE_YELLOWFEVER_EXEMPT_CERTIFICATE`;

export const DELETE_YELLOWFEVER_EXEMPT_CERTIFICATE=`${PRE}_DELETE_YELLOWFEVER_EXEMPT_CERTIFICATE`;

export const LIST_YELLOWFEVER_EXEMPT_CERTIFICATES = `${PRE}_LIST_YELLOWFEVER_EXEMPT_CERTIFICATES`;
export const PUT_LIST_YELLOWFEVER_EXEMPT_CERTIFICATES = `${PRE}_PUT_LIST_YELLOWFEVER_EXEMPT_CERTIFICATES`;