const PRE = 'YELLOW_FEVER_CERT';

export const RESET_ALL = `${PRE}_RESET_ALL`;
export const UPDATE_FIELD = `${PRE}_UPDATE_FIELD`;
//export const GET_SICK_LEAVE_CERT=`${PRE}_GET_SICK_LEAVE_CERT`;
export const SAVE_AND_PRINT_CERT = `${PRE}_SAVE_AND_PRINT_CERT`;

export const UPDATE_VACCINE_CERT = `${PRE}_UPDATE_VACCINE_CERT`;

export const LIST_VACCINE_CERT = `${PRE}_LIST_VACCINE_CERT`;
export const PUT_LIST_VACCINE_CERT = `${PRE}_PUT_LIST_VACCINE_CERT`;