const PREFFIX = 'ADMINISTRATION';
export const RESET_ALL=`${PREFFIX}_RESET_ALL`;
export const CANCEL_EDIT=`${PREFFIX}_CANCEL_EDIT`;
export const INSERT_USER_PROFILE=`${PREFFIX}_INSERT_USER_PROFILE`;
export const UPDATE_USER_PROFILE=`${PREFFIX}_UPDATE_USER_PROFILE`;
export const ADD_USER_PROFILE=`${PREFFIX}_ADD_USER_PROFILE`;
export const EDIT_USER_PROFILE=`${PREFFIX}_EDIT_USER_PROFILE`;
export const SEARCH_USER=`${PREFFIX}_SEARCH`;
export const SEARCH_USER_PROFILE=`${PREFFIX}_SEARCH_USER`;
export const GET_USER_BY_ID=`${PREFFIX}_GET_USER_BY_ID`;
export const UPDATE_FIELD=`${PREFFIX}_UPDATE_FIELD`;
export const UPDATE_STATE=`${PREFFIX}_UPDATE_STATE`;

//saga put
export const PUT_USER_LIST=`${PREFFIX}_PUT_USER_LIST`;
export const PUT_USER_DATA=`${PREFFIX}_PUT_USER_DATA`;
export const PUT_SAVE_USER_PROFILE_SUCCESS=`${PREFFIX}_PUT_SAVE_USER_PROFILE_SUCCESS`;
export const PUT_CODE_LIST=`${PREFFIX}_PUT_CODE_LIST`;

//user related role
export const CLEAR_USER_RELATED_ROLE=`${PREFFIX}_CLEAR_USER_RELATED_ROLE`;