const PREFFIX = 'USER_ACCOUNT';
export const RESET_ALL = `${PREFFIX}_RESET_ALL`;
export const UPDATE_STATE = `${PREFFIX}_UPDATE_STATE`;
export const UPDATE_UAMINFO = `${PREFFIX}_UPDATE_UAMINFO`;

export const GET_UAMINFO = `${PREFFIX}_GET_UAMINFO`;
export const INIT_USER_INFO = `${PREFFIX}_INIT_USER_INFO`;

export const GET_SUPERVISOR_LIST = `${PREFFIX}_GET_SUPERVISOR_LIST`;
export const INIT_SUPERVISOR_LIST = `${PREFFIX}_INIT_SUPERVISOR_LIST`;

export const GET_SUGGEST_LOGIN_NAME = `${PREFFIX}_GET_SUGGEST_LOGIN_NAME`;
export const INIT_SUGGEST_LOGIN_NAME = `${PREFFIX}_INIT_SUGGEST_LOGIN_NAME`;

export const INSERT_USER = `${PREFFIX}_INSERT_USER`;
export const UPDATE_USER = `${PREFFIX}_UPDATE_USER`;
//user role
export const LIST_ALL_USER_ROLE=`${PREFFIX}_LIST_ALL_USER_ROLE`;
export const LOAD_ALL_USER_ROLE=`${PREFFIX}_LOAD_ALL_USER_ROLE`;
export const RESET_ALL_USER_ROLE=`${PREFFIX}_RESET_ALL_USER_ROLE`;

export const GET_USERLIST = `${PREFFIX}_GET_USERLIST`;
export const PUT_USERLIST = `${PREFFIX}_PUT_USERLIST`;
export const DELETE_USER = `${PREFFIX}_DELETE_USER`;

export const SAVE_SUCCESS = `${PREFFIX}_SAVE_SUCCESS`;

export const CHANGE_PASSCODE = `${PREFFIX}_CHANGE_PASSCODE`;
export const GET_USERPASSCODE = `${PREFFIX}_GET_USERPASSCODE`;

export const USER_ACCOUNT_RESET_PASSWORD = `${PREFFIX}_RESET_PASSWORD`;

export const GEN_ACCOUNT_STAFF_ID=`${PREFFIX}_GEN_ACCOUNT_STAFF_ID`;

