const PREFFIX = 'JOS_CLINICALNOTE_VIEW';

export const GET_TEMPLATE_DATA_LIST=`${PREFFIX}_GET_TEMPLATE_DATA_LIST`;

export const GET_COPY_DATA=`${PREFFIX}_GET_COPY_DATA`;

//New
export const GET_NOTE_HISTORY_LIST=`${PREFFIX}_GET_NOTE_HISTORY_LIST`;
export const GET_NOTE_BY_ENCOUNTER=`${PREFFIX}_GET_NOTE_BY_ENCOUNTER`;
export const PUT_CURRENT_NOTE_INFO=`${PREFFIX}_PUT_CURRENT_NOTE_INFO`;
export const PUT_PAST_NOTE_INFO=`${PREFFIX}_PUT_PAST_NOTE_INFO`;
export const GET_NOTE_LOG_BY_CLINICAL_NOTE_ID=`${PREFFIX}_GET_NOTE_LOG_BY_CLINICAL_NOTE_ID`;
export const SAVE_CLINICAL_NOTE=`${PREFFIX}_SAVE_CLINICAL_NOTE`;
export const SAVE_AGAIN_CLINICAL_NOTE=`${PREFFIX}_SAVE_AGAIN_CLINICAL_NOTE`;

export const INSERT_CLINICAL_NOTE_LOG=`${PREFFIX}_INSERT_CLINICAL_NOTE_LOG`;
export const ACCESS_CHECK_IN=`${PREFFIX}_ACCESS_CHECK_IN`;
export const CURRENT_ACCESS_CHECK_OUT=`${PREFFIX}_CURRENT_ACCESS_CHECK_OUT`;
export const PAST_ACCESS_CHECK_OUT=`${PREFFIX}_PAST_ACCESS_CHECK_OUT`;
export const ACCESS_RESET_TIMEOUT=`${PREFFIX}_ACCESS_RESET_TIMEOUT`;
export const GET_NOTETYPE_LIST=`${PREFFIX}_GET_NOTETYPE_LIST`;
