const PREFFIX = 'CLINICAL_DOC';

export const UPLOAD_DOCUMENT = `${ PREFFIX }_UPLOAD_DOCUMENT`;

export const GET_DOCUMENT_LIST = `${ PREFFIX }_GET_DOCUMENT_LIST`;
export const SAVE_DOCUMENT_LIST = `${ PREFFIX }_SAVE_DOCUMENT_LIST`;

export const GET_ENCNTR_DOCUMENT_LIST = `${ PREFFIX }_GET_ENCNTR_DOCUMENT_LIST`;
export const SAVE_ENCNTR_DOCUMENT_LIST = `${ PREFFIX }_SAVE_ENCNTR_DOCUMENT_LIST`;

export const GET_SINGLE_DOCUMENT = `${ PREFFIX }_GET_SINGLE_DOCUMENT`;
export const SAVE_SINGLE_DOCUMENT = `${ PREFFIX }_SAVE_SINGLE_DOCUMENT`;

export const DELETE_SINGLE_DOCUMENT = `${ PREFFIX }_DELETE_SINGLE_DOCUMENT`;

export const GET_DOCUMENT_TYPE_LIST = `${ PREFFIX }_GET_DOCUMENT_TYPE_LIST`;
export const SAVE_DOCUMENT_TYPE_LIST = `${ PREFFIX }_SAVE_DOCUMENT_TYPE_LIST`;
