const PRE = 'SICK_LEAVE_CERTIFICATE';

export const RESET_ALL = `${PRE}_RESET_ALL`;
export const UPDATE_FIELD = `${PRE}_UPDATE_FIELD`;
export const GET_SICK_LEAVE_CERT = `${PRE}_GET_SICK_LEAVE_CERT`;

export const LIST_LEAVE_CERTIFICATES = `${PRE}_LIST_LEAVE_CERTIFICATES`;
export const PUT_LIST_LEAVE_CERTIFICATES = `${PRE}_PUT_LIST_LEAVE_CERTIFICATES`;

export const UPDATE_LEAVE_CERTIFICATE = `${PRE}_UPDATE_LEAVE_CERTIFICATE`;

export const DELETE_LEAVE_CERTIFICATES=`${PRE}_DELETE_LEAVE_CERTIFICATES`;