const PRE = 'IOE_TURNAROUND_TIME';

export const GET_IOE_FORM_DROP_LIST = `${PRE}_GET_IOE_FORM_DROP_LIST`;
export const GET_IOE_TURNAROUND_TIME_LIST = `${PRE}_GET_IOE_TURNAROUND_TIME_LIST`;
export const IOE_TURNAROUND_TIME_LIST = `${PRE}_IOE_TURNAROUND_TIME_LIST`;
export const UPDATE_IOE_TURNAROUND_TIME_LIST = `${PRE}_UPDATE_IOE_TURNAROUND_TIME_LIST`;
