const PREFFIX = 'CALENDAR_VIEW';
export const RESET_ALL=`${PREFFIX}_RESET_ALL`;
// export const DESTROY_PAGE=`${PREFFIX}_INITAL_PAGE`;
export const UPDATE_FIELD=`${PREFFIX}_UPDATE_FIELD`;
export const REQUEST_DATA=`${PREFFIX}_REQUEST_DATA`;
export const FILLING_DATA=`${PREFFIX}_FILLING_DATA`;
// export const RESET_INFO_ALL=`${PREFFIX}_RESET_INFO_ALL`;
export const GET_ENCOUNTER_TYPE_LIST=`${PREFFIX}_GET_ENCOUNTER_TYPE_LIST`;
// export const APPOINTMENT_BOOK=`${PREFFIX}_APPOINTMENT_BOOK`;
// export const LIST_TIMESLOT=`${PREFFIX}_LIST_TIMESLOT`;
// export const LIST_APPOINTMENT=`${PREFFIX}_LIST_APPOINTMENT`;
// export const LOAD_APPOINTMENT_BOOKING=`${PREFFIX}_LOAD_APPOINTMENT_BOOKING`;
export const GET_CLINIC_LIST=`${PREFFIX}_GET_CLINIC_LIST`;
// export const BOOK_CONFIRM=`${PREFFIX}_BOOK_CONFIRM`;
// export const BOOK_CONFIRM_WAITING=`${PREFFIX}_BOOK_CONFIRM_WAITING`;
// export const UPDATE_STATE=`${PREFFIX}_UPDATE_STATE`;
// export const GET_APPOINTMENT_REPORT=`${PREFFIX}_GET_APPOINTMENT_REPORT`;
// export const WALK_IN_ATTENDANCE=`${PREFFIX}_WALK_IN_ATTENDANCE`;
// export const BOOK_AND_ATTEND_SUCCEESS=`${{PREFFIX}}_BOOK_AND_ATTENN_SUCCESS`;
// export const CLOSE_PROMPT_DIALOG=`${PREFFIX}_CLOSE_PROMPT_DIALOG`;
// export const LIST_SEARCH_LOGIC=`${PREFFIX}_LIST_SEARCH_LOGIC`;

//saga put
export const PUT_ENCOUNTER_TYPE_LIST=`${PREFFIX}_PUT_ENCOUNTER_TYPE_LIST`;
// export const PUT_LIST_TIMESLOT_DATA=`${PREFFIX}_PUT_LIST_TIMESLOT_DATA`;
// export const PUT_TIMESLOT_DATA=`${PREFFIX}_PUT_TIMESLOT_DATA`;
// export const PUT_LIST_APPOINTMENT_DATA=`${PREFFIX}_PUT_LIST_APPOINTMENT_DATA`;
// export const PUT_BOOKING_DATA=`${PREFFIX}_PUT_BOOKING_DATA`;
// export const PUT_CLINIC_LIST=`${PREFFIX}_PUT_CLINIC_LIST`;
// export const PUT_BOOK_SUCCESS=`${PREFFIX}_PUT_BOOK_SUCCESS`;
// export const PUT_BOOK_FAIL=`${PREFFIX}_PUT_BOOK_FAIL`;
// export const PUT_USER_SEARCH_LOGIC=`${PREFFIX}_PUT_USER_SEARCH_LOGIC`;


//print appointment list
export const OPEN_PREVIEW_WINDOW=`${PREFFIX}_OPEN_PREVIEW_WINDOW`;
export const PUT_APP_LIST_REPORT_DATA=`${PREFFIX}_PUT_APP_LIST_REPORT_DATA`;


//Room utilization data
export const GET_ROOM_UTILIZATION = `${PREFFIX}_GET_ROOM_UTILIZATION`;

export const GET_FILTER_LISTS = `${PREFFIX}_GET_FILTER_LISTS`;
export const PUT_FILTER_LISTS = `${PREFFIX}_PUT_FILTER_LISTS`;
