const PREFFIX = 'JOS_REDIOLOGY_RECORD_VIEW';

export const GET_REDIOLOGY_RECORD_LIST=`${PREFFIX}_GET_REDIOLOGY_RECORD_LIST`;

export const GET_SERVICE_LIST=`${PREFFIX}_GET_SERVICE_LIST`;

export const DELETE_REDIOLOGY_RECORD=`${PREFFIX}_DELETE_REDIOLOGY_RECORD`;

export const GET_MODALITY_LIST=`${PREFFIX}_GET_MODALITY_LIST`;
export const GET_RAD_EXAM_DATA=`${PREFFIX}_GET_RAD_EXAM_DATA`;
export const SAVE_RADORDER_BY_MODALITY_TYPES=`${PREFFIX}_SAVE_RADORDER_BY_MODALITY_TYPES`;
export const SAVE_RAD_EXAM_DATA=`${PREFFIX}_SAVE_RAD_EXAM_DATA`;