export const data = [
    {
        key: 1,
        name: 'G037',
        active: true,
        details: [
            {
                key: 1,
                category: 'Acupuncture',
                activity: 'APT 2',
                documentation: 'APT 2',
                barcodeNo: 8880001,
                active: true,
            },
            {
                key: 2,
                category: 'Chest Physiotherapy',
                activity: 'Power Trainer',
                documentation: 'Power Trainer',
                barcodeNo: 8880002,
                active: true,
            },
            {
                key: 3,
                category: 'Electrotherapy / Traction',
                activity: 'Shoulder Board',
                documentation: 'Shoulder Board',
                barcodeNo: 8880003,
                active: true,
            },
            {
                key: 4,
                category: 'Functional Capacity Evaluation',
                activity: 'Cycle',
                documentation: 'Cycle',
                barcodeNo: 8880004,
                active: true,
            },
            {
                key: 5,
                category: 'Functional Training',
                activity: 'Double Prostretch',
                documentation: 'Double Prostretch',
                barcodeNo: 8880005,
                active: true,
            },
            {
                key: 6,
                category: 'Hydrotherapy',
                activity: 'Balance Trainer',
                documentation: 'Balance Trainer',
                barcodeNo: 8880006,
                active: false,
            },
            {
                key: 7,
                category: 'Acupuncture',
                activity: 'APT 2',
                documentation: 'APT 2',
                barcodeNo: 8880001,
                active: true,
            },
            {
                key: 8,
                category: 'Chest Physiotherapy',
                activity: 'Power Trainer',
                documentation: 'Power Trainer',
                barcodeNo: 8880002,
                active: true,
            },
            {
                key: 9,
                category: 'Electrotherapy / Traction',
                activity: 'Shoulder Board',
                documentation: 'Shoulder Board',
                barcodeNo: 8880003,
                active: true,
            },
            {
                key: 10,
                category: 'Functional Capacity Evaluation',
                activity: 'Cycle',
                documentation: 'Cycle',
                barcodeNo: 8880004,
                active: true,
            },
            {
                key: 11,
                category: 'Functional Training',
                activity: 'Double Prostretch',
                documentation: 'Double Prostretch',
                barcodeNo: 8880005,
                active: true,
            },
            {
                key: 12,
                category: 'Hydrotherapy',
                activity: 'Balance Trainer',
                documentation: 'Balance Trainer',
                barcodeNo: 8880006,
                active: false,
            },
            {
                key: 13,
                category: 'Acupuncture',
                activity: 'APT 2',
                documentation: 'APT 2',
                barcodeNo: 8880001,
                active: true,
            },
            {
                key: 14,
                category: 'Chest Physiotherapy',
                activity: 'Power Trainer',
                documentation: 'Power Trainer',
                barcodeNo: 8880002,
                active: true,
            },
            {
                key: 15,
                category: 'Electrotherapy / Traction',
                activity: 'Shoulder Board',
                documentation: 'Shoulder Board',
                barcodeNo: 8880003,
                active: true,
            },
            {
                key: 16,
                category: 'Functional Capacity Evaluation',
                activity: 'Cycle',
                documentation: 'Cycle',
                barcodeNo: 8880004,
                active: true,
            },
            {
                key: 17,
                category: 'Functional Training',
                activity: 'Double Prostretch',
                documentation: 'Double Prostretch',
                barcodeNo: 8880005,
                active: true,
            },
            {
                key: 18,
                category: 'Hydrotherapy',
                activity: 'Balance Trainer',
                documentation: 'Balance Trainer',
                barcodeNo: 8880006,
                active: false,
            },
            {
                key: 19,
                category: 'Acupuncture',
                activity: 'APT 2',
                documentation: 'APT 2',
                barcodeNo: 8880001,
                active: true,
            },
            {
                key: 20,
                category: 'Chest Physiotherapy',
                activity: 'Power Trainer',
                documentation: 'Power Trainer',
                barcodeNo: 8880002,
                active: true,
            },
            {
                key: 21,
                category: 'Electrotherapy / Traction',
                activity: 'Shoulder Board',
                documentation: 'Shoulder Board',
                barcodeNo: 8880003,
                active: true,
            },
            {
                key: 22,
                category: 'Functional Capacity Evaluation',
                activity: 'Cycle',
                documentation: 'Cycle',
                barcodeNo: 8880004,
                active: true,
            },
            {
                key: 23,
                category: 'Functional Training',
                activity: 'Double Prostretch',
                documentation: 'Double Prostretch',
                barcodeNo: 8880005,
                active: true,
            },
            {
                key: 24,
                category: 'Hydrotherapy',
                activity: 'Balance Trainer',
                documentation: 'Balance Trainer',
                barcodeNo: 8880006,
                active: false,
            },
            {
                key: 25,
                category: 'Acupuncture',
                activity: 'APT 2',
                documentation: 'APT 2',
                barcodeNo: 8880001,
                active: true,
            },
            {
                key: 26,
                category: 'Chest Physiotherapy',
                activity: 'Power Trainer',
                documentation: 'Power Trainer',
                barcodeNo: 8880002,
                active: true,
            },
            {
                key: 27,
                category: 'Electrotherapy / Traction',
                activity: 'Shoulder Board',
                documentation: 'Shoulder Board',
                barcodeNo: 8880003,
                active: true,
            },
            {
                key: 28,
                category: 'Functional Capacity Evaluation',
                activity: 'Cycle',
                documentation: 'Cycle',
                barcodeNo: 8880004,
                active: true,
            },
            {
                key: 29,
                category: 'Functional Training',
                activity: 'Double Prostretch',
                documentation: 'Double Prostretch',
                barcodeNo: 8880005,
                active: true,
            },
            {
                key: 30,
                category: 'Hydrotherapy',
                activity: 'Balance Trainer',
                documentation: 'Balance Trainer',
                barcodeNo: 8880006,
                active: false,
            },
        ],
    },

    {
        key: 2,
        name: 'G038',
        active: true,
        details: [
            {
                key: 1,
                category: 'Acupuncture',
                activity: 'APT 2',
                documentation: 'APT 2',
                barcodeNo: 8880001,
                active: true,
            },
            {
                key: 2,
                category: 'Chest Physiotherapy',
                activity: 'Power Trainer',
                documentation: 'Power Trainer',
                barcodeNo: 8880002,
                active: false,
            },
            {
                key: 3,
                category: 'Electrotherapy / Traction',
                activity: 'Shoulder Board',
                documentation: 'Shoulder Board',
                barcodeNo: 8880003,
                active: false,
            },
            {
                key: 4,
                category: 'Functional Capacity Evaluation',
                activity: 'Cycle',
                documentation: 'Cycle',
                barcodeNo: 8880004,
                active: false,
            },
            {
                key: 5,
                category: 'Functional Training',
                activity: 'Double Prostretch',
                documentation: 'Double Prostretch',
                barcodeNo: 8880005,
                active: false,
            },
            {
                key: 6,
                category: 'Hydrotherapy',
                activity: 'Balance Trainer',
                documentation: 'Balance Trainer',
                barcodeNo: 8880006,
                active: false,
            },
        ],
    },
    {
        key: 3,
        name: 'G039',
        active: true,
        details: [
            {
                key: 1,
                category: 'Acupuncture',
                activity: 'APT 2',
                documentation: 'APT 2',
                barcodeNo: 8880001,
                active: true,
            },
            {
                key: 2,
                category: 'Chest Physiotherapy',
                activity: 'Power Trainer',
                documentation: 'Power Trainer',
                barcodeNo: 8880002,
                active: true,
            },
            {
                key: 3,
                category: 'Electrotherapy / Traction',
                activity: 'Shoulder Board',
                documentation: 'Shoulder Board',
                barcodeNo: 8880003,
                active: true,
            },
            {
                key: 4,
                category: 'Functional Capacity Evaluation',
                activity: 'Cycle',
                documentation: 'Cycle',
                barcodeNo: 8880004,
                active: true,
            },
            {
                key: 5,
                category: 'Functional Training',
                activity: 'Double Prostretch',
                documentation: 'Double Prostretch',
                barcodeNo: 8880005,
                active: true,
            },
            {
                key: 6,
                category: 'Hydrotherapy',
                activity: 'Balance Trainer',
                documentation: 'Balance Trainer',
                barcodeNo: 8880006,
                active: true,
            },
        ],
    },
    {
        key: 4,
        name: 'G040',
        active: true,
        details: [
            {
                key: 1,
                category: 'Acupuncture',
                activity: 'APT 2',
                documentation: 'APT 2',
                barcodeNo: 8880001,
                active: true,
            },
            {
                key: 2,
                category: 'Chest Physiotherapy',
                activity: 'Power Trainer',
                documentation: 'Power Trainer',
                barcodeNo: 8880002,
                active: false,
            },
            {
                key: 3,
                category: 'Electrotherapy / Traction',
                activity: 'Shoulder Board',
                documentation: 'Shoulder Board',
                barcodeNo: 8880003,
                active: false,
            },
            {
                key: 4,
                category: 'Functional Capacity Evaluation',
                activity: 'Cycle',
                documentation: 'Cycle',
                barcodeNo: 8880004,
                active: false,
            },
            {
                key: 5,
                category: 'Functional Training',
                activity: 'Double Prostretch',
                documentation: 'Double Prostretch',
                barcodeNo: 8880005,
                active: false,
            },
            {
                key: 6,
                category: 'Hydrotherapy',
                activity: 'Balance Trainer',
                documentation: 'Balance Trainer',
                barcodeNo: 8880006,
                active: false,
            },
        ],
    },
    {
        key: 5,
        name: 'Extra Rehab Setting',
        active: false,
        details: [
            {
                key: 1,
                category: 'Acupuncture',
                activity: 'APT 2',
                documentation: 'APT 2',
                barcodeNo: 8880001,
                active: false,
            },
            {
                key: 2,
                category: 'Chest Physiotherapy',
                activity: 'Power Trainer',
                documentation: 'Power Trainer',
                barcodeNo: 8880002,
                active: false,
            },
            {
                key: 3,
                category: 'Electrotherapy / Traction',
                activity: 'Shoulder Board',
                documentation: 'Shoulder Board',
                barcodeNo: 8880003,
                active: false,
            },
            {
                key: 4,
                category: 'Functional Capacity Evaluation',
                activity: 'Cycle',
                documentation: 'Cycle',
                barcodeNo: 8880004,
                active: false,
            },
            {
                key: 5,
                category: 'Functional Training',
                activity: 'Double Prostretch',
                documentation: 'Double Prostretch',
                barcodeNo: 8880005,
                active: false,
            },
            {
                key: 6,
                category: 'Hydrotherapy',
                activity: 'Balance Trainer',
                documentation: 'Balance Trainer',
                barcodeNo: 8880006,
                active: false,
            },
            {
                key: 7,
                category: 'Hydrotherapy',
                activity: 'Balance Trainer',
                documentation: 'Balance Trainer',
                barcodeNo: 8880007,
                active: false,
            },
            {
                key: 8,
                category: 'Hydrotherapy',
                activity: 'Double Prostretch',
                documentation: 'Balance Trainer',
                barcodeNo: 8880008,
                active: false,
            },
        ],
    },
    {
        key: 6,
        name: 'G041',
        active: false,
        details: [],
    },
    {
        key: 7,
        name: 'G042',
        active: false,
        details: [],
    },
    {
        key: 8,
        name: 'G043',
        active: false,
        details: [],
    },
    {
        key: 9,
        name: 'G044',
        active: false,
        details: [],
    },
    {
        key: 10,
        name: 'G045',
        active: false,
        details: [],
    },
    {
        key: 11,
        name: 'G046',
        active: false,
        details: [],
    },
    {
        key: 12,
        name: 'G047',
        active: false,
        details: [],
    },
    {
        key: 13,
        name: 'G048',
        active: false,
        details: [],
    },
    {
        key: 14,
        name: 'G049',
        active: false,
        details: [],
    },
];

export const categorySelectItem = [
    {
        category_name: 'Acupuncture',
        category_value: 'Acupuncture',
    },
    {
        category_name: 'Chest Physiotherapy',
        category_value: 'Chest Physiotherapy',
    },
    {
        category_name: 'Electrotherapy / Traction',
        category_value: 'Electrotherapy / Traction',
    },
    {
        category_name: 'Functional Capacity Evaluation',
        category_value: 'Functional Capacity Evaluation',
    },
    {
        category_name: 'Functional Training',
        category_value: 'Functional Training',
    },
    {
        category_name: 'Hydrotherapy',
        category_value: 'Hydrotherapy',
    },
];
