const PRE = 'MATERNITY_CERTIFICATE';

export const RESET_ALL = `${PRE}_RESET_ALL`;
export const UPDATE_FIELD = `${PRE}_UPDATE_FIELD`;
export const GET_MATERNITY_CERT = `${PRE}_GET_MATERNITY_CERT`;

export const LIST_MATERNITY_CERT = `${PRE}_LIST_MATERNITY_CERT`;
export const PUT_LIST_MATERNITY_CERT = `${PRE}_PUT_LIST_MATERNITY_CERT`;

export const DELETE_MATERNITY_CERT = `${PRE}_DELETE_MATERNITY_CERTT`;

export const UPDATE_MATERNITY_CERT = `${PRE}_UPDATE_MATERNITY_CERT`;