const PRE='APPT_SLIP_REMARKS';

export const RESET_ALL=`${PRE}_RESET_ALL`;


export const LIST_APPTSLIPREMARKS=`${PRE}_LIST_APPTSLIPREMARKS`;
export const PUT_APPTSLIPREMARKS_LIST=`${PRE}_PUT_APPTSLIPREMARKS_LIST`;

export const UPDATE_FIELD=`${PRE}_UPDATE_FIELD`;

export const SUBMIT_APPTSLIPREMARKS=`${PRE}_SUBMIT_APPTSLIPREMARKS`;

export const DELETE_APPTSLIPREMARKS=`${PRE}_DELETE_APPTSLIPREMARKS`;

export const PRINT_APPTSLIPREMARKS=`${PRE}_PRINT_APPTSLIPREMARKS`;

export const GET_APPTSLIP_REPORT=`${PRE}_GET_APPTSLIP_REPORT`;

export const PUT_APPTSLIP_REPORT=`${PRE}_PUT_APPTSLIP_REPORT`;

export const GET_ENCOUNTER_TYPE_LIST_BY_SITE=`${PRE}_GET_ENCOUNTER_TYPE_LIST_BY_SITE`;

export const PUT_ENCOUNTER_TYPE_LIST_BY_SITE=`${PRE}_PUT_ENCOUNTER_TYPE_LIST_BY_SITE`;
