const PRE = 'COMMON_MESSAGE';
export const GET_MESSAGE_LIST_BY_APP_ID = `${PRE}_GET_MESSAGE_LIST_BY_APP_ID`;
export const OPEN_COMMON_MESSAGE = `${PRE}_OPEN_COMMON_MESSAGE`;
export const CLOSE_COMMON_MESSAGE = `${PRE}_CLOSE_COMMON_MESSAGE`;
export const COMMON_MESSAGE_LIST = `${PRE}_COMMON_MESSAGE_LIST`;
export const CLEAN_COMMON_MESSAGE_DETAIL = `${PRE}_CLEAN_COMMON_MESSAGE_DETAIL`;
export const CLEAN_COMMON_MESSAGE_SNACKBAR_DETAIL = `${PRE}_CLEAN_COMMON_MESSAGE_SNACKBAR_DETAIL`;
export const STR_COMMON_MESSAGE = `${PRE}_STR_COMMON_MESSAGE`;