const PRE = 'PATIENT_BANNER';

export const GET_GRAVIDA_AND_PARITY = `${PRE}_GET_GRAVIDA_AND_PARITY`;
export const PUT_GRAVIDA_AND_PARITY = `${PRE}_PUT_GRAVIDA_AND_PARITY`;

export const GET_ANT_SVC_ID_INFO_LOG = `${PRE}_GET_ANT_SVC_ID_INFO_LOG`;
export const PUT_ANT_SVC_ID_INFO_LOG = `${PRE}_PUT_ANT_SVC_ID_INFO_LOG`;