const PRE = 'PATIENT';
export const GET_PATINET_BY_ID = `${PRE}_GET_PATINET_BY_ID`;
export const LOAD_PATIENT = `${PRE}_LOAD_PATIENT`;
export const RESET_ALL = `${PRE}_RESET_ALL`;
export const UPDATE_STATE = `${PRE}_UPDATE_STATE`;
export const GET_LANGUAGE_LIST = `${PRE}_GET_LANGUAGE_LIST`;
export const REFRESH_PATIENT = `${PRE}_REFRESH_PATIENT`;

//sagas put
export const PUT_PATIENT_INFO = `${PRE}_PUT_PATIENT_INFO`;
export const PUT_LANGUAGE_LIST = `${PRE}_PUT_LANGUAGE_LIST`;
export const PUT_EHR_URL = `${PRE}_PUT_EHR_URL`;

//list Nationality And List Country
export const LIST_NATIONALITY_AND_LIST_COUNTRY = `${PRE}_LIST_NATIONALITY_AND_LIST_COUNTRY`;
export const LOAD_NATIONALITY_LIST_AND_COUNTRY_LIST = `${PRE}_LOAD_NATIONALITY_LIST_AND_COUNTRY_LIST`;

//update patient appointment
export const GET_PATIENT_APPOINTMENT = `${PRE}_GET_PATIENT_APPOINTMENT`;
export const GET_REDESIGN_PATIENT_APPOINTMENT = `${PRE}_GET_REDESIGN_PATIENT_APPOINTMENT`;
export const UPDATE_PATIENT_APPOINTMENT = `${PRE}_UPDATE_PATIENT_APPOINTMENT`;

//load patient encounter info
export const GET_PATIENT_ENCOUNTER = `${PRE}_GET_PATIENT_ENCOUNTER`;
export const GET_PATIENT_ENCOUNTER_BY_ID = `${PRE}_GET_PATIENT_ENCOUNTER_BY_ID`;
export const LOAD_PATIENT_ENCOUNTER_INFO = `${PRE}_LOAD_PATIENT_ENCOUNTER_INFO`;

//update patient caseNo
export const GET_PATIENT_CASENO = `${PRE}_GET_PATIENT_CASENO`;
export const UPDATE_PATIENT_CASENO = `${PRE}_UPDATE_PATIENT_CASENO`;

//get eHR url
export const GET_EHR_URL = `${PRE}_GET_EHR_URL`;
export const RESET_EHR_URL = `${PRE}_RESET_EHR_URL`;
export const PUT_EHR_PATIENT_STATUS = `${PRE}_PUT_EHR_PATIENT_STATUS`;

//list majorkey change history
export const LIST_MAJORKEY_CHANGE_HISTORY = `${PRE}_LIST_MAJORKEY_CHANGE_HISTORY`;
export const PUT_MAJORKEY_CHANGE_HISTORY = `${PRE}_PUT_MAJORKEY_CHANGE_HISTORY`;

//get patient gum label
export const GET_PATIENT_GUM_LABEL=`${PRE}_GET_PATIENT_GUM_LABEL`;
//get patient spp gum label
export const GET_PATIENT_SPP_GUM_LABEL=`${PRE}_GET_PATIENT_SPP_GUM_LABEL`;
//get patient ehs gum label
export const GET_PATIENT_EHS_GUM_LABEL= `${PRE}_GET_PATIENT_EHS_GUM_LABEL`;

//get patient specimen label
export const GET_PATIENT_SPECIMEN_LABEL=`${PRE}_GET_PATIENT_SPECIMEN_LABEL`;

//list appt. history
export const LIST_APPOINTMENT_HISTORY=`${PRE}_LIST_APPOINTMENT_HISTORY`;
export const PUT_LIST_APPOINTMENT_HISTORY=`${PRE}_PUT_LIST_APPOINTMENT_HISTORY`;

export const GET_PATIENT_BANNER=`${PRE}_GET_PATIENT_BANNER`;
export const PUT_PATIENT_BANNER=`${PRE}_PUT_PATIENT_BANNER`;
export const CLEAR_PATIENT_BANNER=`${PRE}_CLEAR_PATIENT_BANNER`;

//View log list
export const GET_VIEW_LOG_LIST = `${PRE}_GET_VIEW_LOG_LIST`;

//CGS Family encounter search list
export const GET_FAMILY_ENCOUNTER_SEARCH_LIST = `${PRE}_GET_FAMILY_ENCOUNTER_SEARCH_LIST`;
export const UPDATE_FAMILY_ENCOUNTER_SEARCH_LIST = `${PRE}_UPDATE_FAMILY_ENCOUNTER_SEARCH_LIST`;
export const TOGGLE_FAMILY_ENCOUNTER_SEARCH_DIALOG = `${PRE}TOGGLE_FAMILY_ENCOUNTER_SEARCH_DIALOG`;
export const UPDATE_FAMILY_ENCOUNTER_SEARCH_DIALOG = `${PRE}UPDATE_FAMILY_ENCOUNTER_SEARCH_DIALOG`;

//Reset patient panel like appointmentInfo etc..
export const RESET_PATIENT_PANEL = `${PRE}_RESET_PATIENT_PANEL`;

//list ths destination
export const LIST_THS_DESTINATION = `${PRE}_LIST_THS_DESTINATION`;
export const LOAD_THS_DESTINATION = `${PRE}_LOAD_THS_DESTINATION`;

export const GET_PATIENT_PUC = `${PRE}_GET_PATIENT_PUC`;
export const PUT_PATIENT_PUC = `${PRE}_PUT_PATIENT_PUC`;

// ANT Service Info
export const REFRESH_AN_SERVICE_ID_INFO=`${PRE}_UPDATE_AN_SERVICE_ID_INFO`;

export const GET_PATIENT_BANNER_DATA = `${PRE}_GET_PATIENT_BANNER_DATA`;
export const PUT_PATIENT_BANNER_DATA = `${PRE}_PUT_PATIENT_BANNER_DATA`;
export const CLEAR_PATIENT_BANNER_DATA = `${PRE}_CLEAR_PATIENT_BANNER_DATA`;

// pso info
export const PUT_PATIENT_PSORIASIS_INFO = `${PRE}_PUT_PATIENT_PSORIASIS_INFO`;

// SHS Psoriasis Annual Reminder
export const GET_PSO_INFO = `${PRE}_GET_PSO_INFO`;
export const PUT_PSO_INFO = `${PRE}_PUT_PSO_INFO`;
export const ADD_PSO_INFO = `${PRE}_ADD_PSO_INFO`;

//SHS Encounter Info Case
export const GET_LATEST_PATIENT_ENCOUNTER_CASE = `${PRE}_GET_LATEST_PATIENT_ENCOUNTER_CASE`;
export const PUT_LATEST_PATIENT_ENCOUNTER_CASE = `${PRE}_PUT_LATEST_PATIENT_ENCOUNTER_CASE`;
export const UPDATE_PATIENT_ENCOUNTER_CASE = `${PRE}_UPDATE_PATIENT_ENCOUNTER_CASE`;

//Patient does not have today attended appointment but have encounter within 1 month
export const GET_HAVE_ENCOUNTER_WITHIN_ONE_MONTH = `${PRE}_GET_HAVE_ENCOUNTER_WITHIN_ONE_MONTH`;

// CGS GeneticScreening
export const PUT_GENETIC_SCREENING_INFO = `${PRE}_PUT_GENETIC_SCREENING_INFO`;

//EHS update ehs last check date
export const UPDATE_LAST_CHECKDATE = `${PRE}_UPDATE_LAST_CHECKDATE`;