const PREFFIX = 'MOE';
export const LOGIN = `${PREFFIX}_LOGIN`;
export const LOGOUT = `${PREFFIX}_LOGOUT`;
export const LOGIN_SUCCESS = `${PREFFIX}_LOGIN_SUCCESS`;
export const LOGIN_ERROR = `${PREFFIX}_LOGIN_ERROR`;
export const RELOGIN_SUCCESS = `${PREFFIX}_RELOGIN_SUCCESS`;

export const SEARCH_DRUG = `${PREFFIX}_SEARCH_DRUG`;
export const SEARCH_DRUG_LIST = `${PREFFIX}_SEARCH_DRUG_LIST`;
export const SEARCH_ITEM_COLLAPSE = `${PREFFIX}_SEARCH_ITEM_COLLAPSE`;
export const GET_DRUG = `${PREFFIX}_GET_DRUG`;
export const GRUG_RESPONSE = `${PREFFIX}_GRUG_RESPONSE`;
export const GET_CODE_LIST = `${PREFFIX}_GET_CODE_LIST`;
export const CODE_LIST = `${PREFFIX}_CODE_LIST`;
export const DELETE_DRUG = `${PREFFIX}_DELETE_DRUG`;
export const RESET_DRUG_LIST = `${PREFFIX}_RESET_DRUG_LIST`;

export const UPDATE_FIELD = `${PREFFIX}_UPDATE_FIELD`;

export const SAVE_DRUG = `${PREFFIX}_SAVE_DRUG`;
export const CONFIRM_DUPLICATE_DRUG = `${PREFFIX}_CONFIRM_DUPLICATE_DRUG`;

export const SAVE_DRUG_SUCCESS = `${PREFFIX}_SAVE_DRUG_SUCCESS`;
export const CANCEL_ORDER = `${PREFFIX}_CANCEL_ORDER`;
export const DELETE_ORDER = `${PREFFIX}_DELETE_ORDER`;
export const DELETE_ORDER_SUCCESS = `${PREFFIX}_DELETE_ORDER_SUCCESS`;
export const GET_ORDER_DRUG_LIST = `${PREFFIX}_GET_ORDER_DRUG_LIST`;
export const GET_MDS_ENQUIRY = `${PREFFIX}_GET_MDS_ENQUIRY`;
export const UPDATE_MDS_ENQUIRY = `${PREFFIX}_UPDATE_MDS_ENQUIRY`;
export const GET_HLAB1502_VTM = `${PREFFIX}_GET_HLAB1502_VTM`;
export const UPDATE_HLAB1502_VTM = `${PREFFIX}_UPDATE_HLAB1502_VTM`;
export const SAVE_HLAB1502_NEGATIVE = `${PREFFIX}_SAVE_HLAB1502_NEGATIVE`;
export const DELETE_HLAB1502_NEGATIVE = `${PREFFIX}_DELETE_HLAB1502_NEGATIVE`;
export const ADD_NO_KNOWN_ALLERGY = `${PREFFIX}_ADD_NO_KNOWN_ALLERGY`;
export const RECONFIRM_ALLERGY = `${PREFFIX}_RECONFIRM_ALLERGY`;
export const UPDATE_PATIENT_ALLERGY_CONNECTED_FLAG = `${PREFFIX}_UPDATE_PATIENT_ALLERGY_CONNECTED_FLAG`;


//myFavourite
export const UPDATE_MY_FAVOURITE_FIELD = `${PREFFIX}_UPDATE_MY_FAVOURITE_FIELD`;
export const DELETE_FAVOURITE = `${PREFFIX}_DELETE_FAVOURITE`;
export const ADD_TO_MY_FAVOURITE = `${PREFFIX}_ADD_TO_MY_FAVOURITE`;
export const FILTER_MY_FAVOURITE = `${PREFFIX}_FILTER_MY_FAVOURITE`;
export const UPDATE_FAV_SCHINPUTVAL = `${PREFFIX}_UPDATE_FAV_SCHINPUTVAL`;
export const REORDER_MY_FAV = `${PREFFIX}_REORDER_MY_FAV`;
export const UPDATE_MY_FAV=`${PREFFIX}_UPDATE_MY_FAV`;

//print
export const PRINT_PREVIEW = `${PREFFIX}_PRINT_PREVIEW`;
export const PRINT_PRINT_LOG = `${PREFFIX}_PRINT_PRINT_LOG`;
export const PRINT_PRINT = `${PREFFIX}_PRINT_PRINT`;

//special interval
export const GET_SPECIAL_INTERVAL_TEXT = `${PREFFIX}_GET_SPECIAL_INTERVAL_TEXT`;
export const SPECIAL_INTERVAL_TEXT = `${PREFFIX}_SPECIAL_INTERVAL_TEXT`;

//drug history
export const UPDATE_DRUG_HISTORY_FIELD = `${PREFFIX}_UPDATE_DRUG_HISTORY_FIELD`;
export const FILTER_DRUG_HISTORY_PARAMS = `${PREFFIX}_FILTER_DRUG_HISTORY_PARAMS`;

export const CONVERT_DRUG = `${PREFFIX}_CONVERT_DRUG`;

//dangerous drug
export const GET_TOTAL_DANGER_DRUG = `${PREFFIX}_GET_TOTAL_DANGER_DRUG`;
export const TOTAL_DANGER_DRUG = `${PREFFIX}_TOTAL_DANGER_DRUG`;

//allergy checing
export const GET_ALLERGY_CHECKING = `${PREFFIX}_GET_ALLERGY_CHECKING`;
export const ALLERGY_CHECKING = `${PREFFIX}_ALLERGY_CHECKING`;
export const UPDATE_PATIENT_ALLERGY_INF = `${PREFFIX}_UPDATE_PATIENT_ALLERGY_INF`;

//department favourite
export const UPDATE_DEPT_FAVOURITE_FIELD = `${PREFFIX}_UPDATE_DEPT_FAVOURITE_FIELD`;
export const GET_DEPT_FAVOURITE_LIST = `${PREFFIX}_GET_DEPT_FAVOURITE_LIST`;
