const MRAM_DIETASSESSMENT_DASM_PREFIX = 'dasm';
const MRAM_DIETASSESSMENT_DASM_EXAMINATION_ID = {
    QUESTION_1:'164',
    QUESTION_2:'165',
    QUESTION_3:'166',
    QUESTION_4:'167',
    QUESTION_5:'168',
    QUESTION_6:'169',
    QUESTION_7:'170',
    ASSESSED_BY:'171',
    ASSESSMETN_DATE:'172'
  };
const ACTION_TYPE = {
    INSERT: 'I',
    UPDATE: 'U',
    DELETE: 'D'
};

const MRAM_DIETASSESSMENT_ID_MAP = new Map([
    [MRAM_DIETASSESSMENT_DASM_PREFIX,MRAM_DIETASSESSMENT_DASM_EXAMINATION_ID]
  ]);

export {
ACTION_TYPE,
MRAM_DIETASSESSMENT_ID_MAP,
MRAM_DIETASSESSMENT_DASM_EXAMINATION_ID,
MRAM_DIETASSESSMENT_DASM_PREFIX
};