const LOG_TYPE_MAP = new Map([
  ['I','New'],
  ['U','Edited'],
  ['D','Delete']
]);

const CHECK_BOX_STATUS = {
  CHECKED: 'Y',
  UNCHECKED: 'N'
};

const DELETED_STATUS = {
  YES: 'Y',
  NO: 'N'
};

const SOCIAL_CODE_ENCOUNTER_RFI = {
  SMOKING: '1',
  DRINKING: '2',
  SUBSTANCE_ABUSE:'3',
  PASSIVE: '4'
};

const SOCIAL_HISTORY_TYPE_ID = {
  SMOKING: '1',
  DRINKING: '2',
  SUBSTANCE_ABUSE:'3',
  PASSIVE: '4'
};


const PAST_MED_HISTORY_INDT = {
  ACCIDENT: 'A',
  INPUT_PROBLEM: 'B',
  PRE_SER_PROBLEM: 'C'
};

const TERMINOLOGY_SERVICE_TYPE = {
  PAST_MEDICAL_HISTORY:'PAST_MED_HISTORY_INDT',
  FAMILY_HISTORY:'FAMILY_HISTORY_INDT'
};

const MEDICAL_HISTORIES_TYPE = {
  OCCUPATIONAL_HISTORY:'OH',
  OCCUPATIONAL_OTHERS:'OO',
  SOCIAL_HISTORY_SMOKING:'SHS',
  SOCIAL_HISTORY_PASSIVE:'SHP',
  SOCIAL_HISTORY_DRINKING:'SHD',
  SOCIAL_HISTORY_SUBSTANCE_ABUSE:'SHSA',
  SOCIAL_HISTORY_OTHERS:'SHO',
  PAST_MEDICAL_HISTORY:'PMH',
  PAST_MEDICAL_HISTORY_DETAILS:'PMHD',
  FAMILY_HISTORY_RELATIONSHIP:'FHR',
  FAMILY_HISTORY_RELATIONSHIP_PROBLEM:'FHRP',
  FAMILY_HISTORY_RELATIONSHIP_PROBLEM_DETAIL:'FHRPD',
  FAMILY_HISTORY_OTHERS:'FHO'
};

const CASCADE_TYPE_SMOKING_MAP = new Map([['N', 4]]); // Never
const CASCADE_TYPE_DRINKING_MAP = new Map([['N', 215]]); // Never
const CASCADE_TYPE_SUBSTANCE_ABUSE_MAP = new Map([['N', 321]]); // Never
const CASCADE_TYPE_MAP = new Map([
  [MEDICAL_HISTORIES_TYPE.SOCIAL_HISTORY_SMOKING,CASCADE_TYPE_SMOKING_MAP],
  [MEDICAL_HISTORIES_TYPE.SOCIAL_HISTORY_DRINKING,CASCADE_TYPE_DRINKING_MAP],
  [MEDICAL_HISTORIES_TYPE.SOCIAL_HISTORY_SUBSTANCE_ABUSE,CASCADE_TYPE_SUBSTANCE_ABUSE_MAP]
]);

const OBS_RICK_FACTOR_OPTION = [{ label: 'OBS Rick Factor', value: 'Y' }];

const DEFAULT_FAMILY_HISTORY_RELATIONSHIP_LIST = ['Father', 'Mother', 'Husband'];

export {
  CASCADE_TYPE_MAP,
  MEDICAL_HISTORIES_TYPE,
  DELETED_STATUS,
  PAST_MED_HISTORY_INDT,
  TERMINOLOGY_SERVICE_TYPE,
  SOCIAL_CODE_ENCOUNTER_RFI,
  SOCIAL_HISTORY_TYPE_ID,
  CHECK_BOX_STATUS,
  LOG_TYPE_MAP,
  OBS_RICK_FACTOR_OPTION,
  DEFAULT_FAMILY_HISTORY_RELATIONSHIP_LIST
};
