const PREFFIX = 'JOS_MRAM_MRAMHISTORY_VIEW';
export const SAVE_MRAM_HISTORY_DATA=`${PREFFIX}_SAVE_MRAM_HISTORY_DATA`;
export const SAVE_MRAM_HISTORY_RESULT=`${PREFFIX}_SAVE_MRAM_HISTORY_RESULT`;

export const DELETE_MRAM_HISTORY_DATA=`${PREFFIX}_DELETE_MRAM_HISTORY_DATA`;
export const DELETE_MRAM_HISTORY_RESULT=`${PREFFIX}_DELETE_MRAM_HISTORY_RESULT`;