const PREFFIX = 'ANA_ATND';
export const ANA_ATND_UPDATE_FIELD = `${PREFFIX}_UPDATE_FIELD`;
export const ANA_ATND_RESET_ALL = `${PREFFIX}_RESET_ALL`;

//appointment remark type for display
export const ANA_ATND_PUT_ANA_REMARK = `${PREFFIX}_PUT_ANA_REMARK`;

//patient status
export const ANA_ATND_PUT_PATIENT_STATUS_LIST = `${PREFFIX}_PUT_PATIENT_STATUS_LIST`;

export const ANA_ATND_MARK_ATTENDANCE = `${PREFFIX}_MARK_ATTENDANCE`;
export const ANA_ATND_MARK_ATTENDANCE_SUCCESS = `${PREFFIX}_MARK_ATTENDANCE_SUCCESS`;
export const ANA_ATND_DESTROY_MARK_ATTENDANCE = `${PREFFIX}_DESTROY_MARK_ATTENDANCE`;
export const ANA_ATND_GET_APPOINTMENT_FOR_TAKE_ATTENDANCE = `${PREFFIX}_GET_APPOINTMENT_FOR_TAKE_ATTENDANCE`;
export const ANA_ATND_APPOINTMENT_FOR_ATTENDANCE_SUCCESS = `${PREFFIX}_APPOINTMENT_FOR_ATTENDANCE_SUCCESS`;

//list Appt.
export const ANA_ATND_LIST_APPOINTMENT = `${PREFFIX}_LIST_APPOINTMENT`;
export const ANA_ATND_PUT_APPOINTMENT_LIST = `${PREFFIX}_PUT_APPOINTMENT_LIST`;
export const ANA_ATND_GET_PATIENT_QUEUE = `${PREFFIX}_GET_PATIENT_QUEUE`;
export const ANA_ATND_PUT_PATIENT_QUEUE = `${PREFFIX}_PUT_PATIENT_QUEUE`;

//get code list via saga
export const ANA_ATND_GET_CODE_LIST = `${PREFFIX}_GET_CODE_LIST`;
//sagas put
export const ANA_ATND_PUT_GET_CODE_LIST = `${PREFFIX}_PUT_GET_CODE_LIST`;

//mark arrival
export const ANA_ATND_MARK_ARRIVAL = `${PREFFIX}_MARK_ARRIVAL`;

//edit attendnace
export const ANA_ATND_EDIT_ATTENDANCE = `${PREFFIX}_EDIT_ATTENDANCE`;

//patient summary attend
export const ANA_ATND_MARK_ATTENDANCE_PATIENT_SUMMARY = `${PREFFIX}_ANA_ATND_MARK_ATTENDANCE_PATIENT_SUMMARY`;