const PREFFIX = 'FAMILY';

export const RESET_DATA = `${PREFFIX}_RESET_DATA`;

export const GET_DATA = `${PREFFIX}_GET_DATA`;

export const GET_BASE64_EXCEL_DATA = `${PREFFIX}_GET_BASE64_EXCEL_DATA`;

export const UPDATE_STATE = `${PREFFIX}_UPDATE_STATE`;

export const DIALOG_TOGGLE = `${PREFFIX}_DIALOG_TOGGLE`;

export const SEARCH_DIALOG_TOGGLE = `${PREFFIX}_SEARCH_DIALOG_TOGGLE`;