export const SET_GLOBAL = 'SET_GLOBAL';

export const MESSAGE_CLEAN = 'MESSAGE/CLEAN';
export const MESSAGE_OPEN_MSG = 'MESSAGE/OPEN_MSG';


export const SET_PATIENT_DETAIL = 'PATIENT_DETAIL/SET_PATIENT_DETAIL';

export const SET_PATIENT_DETAILS_PT = 'PATIENT_DETAIL/SET_PATIENT_DETAILS_PT';
export const SET_PATIENT_DETAILS_OT = 'PATIENT_DETAIL/SET_PATIENT_DETAILS_OT';
export const SWITCH_PATIENT_DETAILS_TYPE = 'PATIENT_DETAIL/SWITCH_PATIENT_DETAILS_TYPE';

export const SET_RELOADPATH = 'TAB_ROUTER/SET_RELOADPATH';
export const SET_CURTABS = 'TAB_ROUTER/SET_CURTAB';

export const SET_LOGIN_HOSP = 'LOGIN_INFO/SET_LOGIN_HOSP';
export const SET_LOGIN_ROOM = 'LOGIN_INFO/SET_LOGIN_ROOM';

export const FETCH_PATIENT_DETAILS_MASTER_LIST = 'DETAIL/FETCH_PATIENT_DETAILS_MASTER_LIST'

export const SET_DETAIL = 'DETAIL/SET_DETAIL'
export const FETCH_PATIENT_PRECAUTION_ICON_LIST = 'DETAIL/FETCH_PATIENT_PRECAUTION_ICON_LIST';
export const FETCH_TREATMENT_RECORD = 'DETAIL/FETCH_TREATMENT_RECORD';
export const FETCH_SET_TREATMENT = 'DETAIL/FETCH_SET_TREATMENT';
export const FETCH_UPDATE_TREATMENT_REMARKS = 'DETAIL/FETCH_UPDATE_TREATMENT_REMARKS';
export const FETCH_PATIENT_DETAIL = 'DETAIL/FETCH_PATIENT_DETAIL';
export const FETCH_CURRENT_TREATMENT = 'DETAIL/FETCH_CURRENT_TREATMENT';
export const FETCH_E_VITAL_LIST = 'DETAIL/FETCH_E_VITAL_LIST'
export const SET_E_VITAL_LIST = 'DETAIL/SET_E_VITAL_LIST'

export const FETCH_LOGININFO_HOSPLIST = 'LOGIN_INFO/FETCH_LOGININFO_HOSPLIST';
export const FETCH_LOGININFO_ROOMLIST = 'LOGIN_INFO/FETCH_LOGININFO_ROOMLIST';
export const SHOW_ERROR_TIPS = 'LOGIN_INFO/SHOW_ERROR_TIPS';



export const SET_GROUP = 'GROUP/SET_GROUP'
export const SET_GROUP_DETAIL = 'GROUP/SET_GROUP_DETAIL'
export const FETCH_GROUP_LIST = 'GROUP/FETCH_GROUP_LIST'
export const FETCH_GROUP_DETAIL = 'GROUP/FETCH_GROUP_DETAIL'
export const HANDLE_PATIENT_IN_GROUP = 'GROUP/HANDLE_PATIENT_IN_GROUP'

export const FETCH_SCENE_DATA = 'SCENE/FETCH_SCENE_DATA';
export const SET_SCENE_DATA = 'SCENE/SET_SCENE_DATA'


export const SET_ACTIVITY = 'DETAIL/SET_ACTIVITY'


export const SET_ROOM = 'ROOM/SET_ROOM'
export const SET_ROOM_DATA = 'ROOM/SET_ROOM_DATA'
export const FETCH_ROOM_IN_OUT = 'ROOM/FETCH_ROOM_IN_OUT'
export const SHOW_SCAN = 'GLOBAL/SHOW_SCAN'
export const FETCH_ROOM_TREATMENT_RECORD = 'ROOM/FETCH_ROOM_TREATMENT_RECORD'