const PRE = 'GENERALLETTER';

export const RESET_ALL = `${PRE}_RESET_ALL`;
export const UPDATE_FIELD = `${PRE}_UPDATE_FIELD`;
export const GET_GENERALLETTER_CERT = `${PRE}_GET_GENERALLETTER_CERT`;

export const LIST_GENERALLETTER_CERT = `${PRE}_LIST_GENERALLETTER_CERT`;
export const PUT_LIST_GENERALLETTER_CERT = `${PRE}_PUT_LIST_GENERALLETTER_CERT`;

export const DELETE_GENERALLETTER_CERT = `${PRE}_DELETE_GENERALLETTER_CERTT`;

export const UPDATE_GENERALLETTER_CERT=`${PRE}_UPDATE_GENERALLETTER_CERT`;