export const SET_GLOBAL = 'SET_GLOBAL';

export const MESSAGE_CLEAN = 'MESSAGE/CLEAN';
export const MESSAGE_OPEN_MSG = 'MESSAGE/OPEN_MSG';

export const SET_PATIENT_DETAIL = 'PATIENT_DETAIL/SET_PATIENT_DETAIL';

export const SET_PATIENT_DETAILS_BASIC = 'PATIENT_DETAIL/SET_PATIENT_DETAILS_BASIC';
export const SWITCH_PATIENT_DETAILS_TYPE = 'PATIENT_DETAIL/SWITCH_PATIENT_DETAILS_TYPE';
export const SET_SELECTED_PRECAUTION = 'SET_SELECTED_PRECAUTION';

export const SET_RELOADPATH = 'TAB_ROUTER/SET_RELOADPATH';
export const SET_CURTABS = 'TAB_ROUTER/SET_CURTAB';

// patient detailGet Patient Details Master List

export const FETCH_PATIENT_PRESCRIPTION = 'PATIENT_DETAIL/FETCH_PATIENT_PRESCRIPTION';
export const FETCH_ROOT_LIST = 'PATIENT_DETAIL/FETCH_ROOT_LIST';
export const FETCH_PATIENT_DETAIL_MASTER_LIST = 'PATIENT_DETAIL/FETCH_PATIENT_DETAIL_MASTER_LIST';
export const FETCH_MASTER_LIST_STATIC = 'PATIENT_DETAIL/FETCH_MASTER_LIST_STATIC';
export const FETCH_PROTOCOL_LIST = 'PATIENT_DETAIL/FETCH_PROTOCOL_LIST';
export const FETCH_SAVE_PRECAUTIONS = 'PATIENT_DETAIL/FETCH_SAVE_PRECAUTIONS';
export const FETCH_THERAPEUTIC_GROUP_CALENDAR_LIST = 'PATIENT_DETAIL/FETCH_THERAPEUTIC_GROUP_CALENDAR_LIST';
export const FETCH_THERAPEUTIC_GROUP_PATIENT_LIST = 'PATIENT_DETAIL/FETCH_THERAPEUTIC_GROUP_PATIENT_LIST';
//
export const SET_SUMMARY = 'SET_SUMMARY';
export const FETCH_PATIENT_SUMMARY_LIST = 'PATIENT_DETAIL/FETCH_PATIENT_SUMMARY_LIST';
export const FETCH_THERAPEUTIC_GROUP_PATIENT_DATA = 'PATIENT_DETAIL/FETCH_THERAPEUTIC_GROUP_PATIENT_DATA';

//dashboard
export const SET_DASHBOARD_LIST = 'DASHBOARD/SET_DASHBOARD_LIST';
export const FETCH_DASHBOARD_LIST = 'DASHBOARD/FETCH_DASHBOARD_LIST';
export const FETCH_HOTITEMS_LIST = 'DASHBOARD/FETCH_HOTITEMS_LIST';

export const SET_CALENDAR_LIST = 'CALENDAR/SET_CALENDAR_LIST';
export const SET_CATEGORY_LIST = 'CALENDAR/SET_CATEGORY_LIST';
export const SET_NAME_LIST = 'CALENDAR/SET_NAME_LIST';
export const SET_PATIENT_LIST_INFO = 'CALENDAR/SET_PATIENT_LIST_INFO';
export const UPDATE_PATIENT_INFO = 'CALENDAR/UPDATE_PATIENT_INFO';

export const FETCH_CALENDAR_LIST = 'CALENDAR/FETCH_CALENDAR_LIST';
export const FETCH_CATEGORY_LIST = 'CALENDAR/FETCH_CATEGORY_LIST';
export const FETCH_NAME_LIST = 'CALENDAR/FETCH_NAME_LIST';
export const FETCH_PATIENT_INFO = 'CALENDAR/FETCH_PATIENT_INFO';

//adminMode
export const SET_ADMINMODE_DATA = 'ADMINMODE/SET_ADMINMODE_DATA';
export const SAVE_TREATMENT_PROPERTIES = 'ADMINMODE/SAVE_TREATMENT_PROPERTIES'

//batchMode
export const FETCH_BATCHMODE_PATIENT_LIST = 'BATCHMODE/FETCH_BATCHMODE_PATIENT_LIST'
export const FETCH_BATCHMODE_ROOM_LIST = 'BATCHMODE/FETCH_BATCHMODE_ROOM_LIST'
export const SET_BATCHMODE_DATA = 'BATCHMODE/SET_BATCHMODE_DATA'
export const SAVE_BATCHMODE_PATIENT_LIST = 'BATCHMODE/SAVE_BATCHMODE_DATA'
export const FETCH_BATCHMODE_THERAPIST_LIST = 'BATCHMODE/FETCH_BATCHMODE_THERAPIST_LIST'


//hotlist
export const FETCH_HOTLIST_DATA = 'ADMINMODE/FETCH_HOTLIST_DATA';
export const UPDATE_HOTLIST_DATA = 'ADMINMODE/UPDATE_HOTLIST_DATA';

//groupList
export const SET_GROUPLIST_DATA = 'ADMINMODE/SET_GROUPLIST_DATA';
export const FETCH_GROUPLIST_DATA = 'ADMINMODE/FETCH_GROUPLIST_DATA';
export const UPDATE_GROUPLIST_DATA = 'ADMINMODE/UPDATE_GROUPLIST_DATA';
export const FETCH_CATEGORY_GROUPLIST_DATA = 'ADMINMODE/FETCH_CATEGORY_GROUPLIST_DATA';
export const SAVE_CATEGORY_GROUPLIST_DATA = 'ADMINMODE/SAVE_CATEGORY_GROUPLIST_DATA';


//vitalSignType
export const SET_VITALSIGNTYPELIST_DATA = 'ADMINMODE/SET_VITALSIGNTYPELIST_DATA';
export const FETCH_VITALSIGNTYPELIST_DATA = 'ADMINMODE/FETCH_VITALSIGNTYPELIST_DATA';
export const UPDATE_VITALSIGNTYPELIST_DATA = 'ADMINMODE/UPDATE_VITALSIGNTYPELIST_DATA';

//side
export const SET_SIDELIST_DATA = 'ADMINMODE/SET_SIDELIST_DATA';
export const FETCH_SIDELIST_DATA = 'ADMINMODE/FETCH_SIDELIST_DATA';
export const UPDATE_SIDELIST_DATA = 'ADMINMODE/UPDATE_SIDELIST_DATA';

//protocol
export const FETCH_PROTOCOL_DATA = 'ADMINMODE/FETCH_PROTOCOL_DATA';
export const UPDATE_PROTOCOL_DATA = 'ADMINMODE/UPDATE_PROTOCOL_DATA';

//activity
export const FETCH_ACTIVITY_LIST_BY_ROOM = 'ADMINMODE/FETCH_ACTIVITY_LIST_BY_ROOM';
export const UPDATE_ACTIVITY_LIST = 'ADMINMODE/UPDATE_ACTIVITY_LIST';
export const FETCH_ROOM_LIST_IN_ACTIVITY = 'ADMINMODE/FETCH_ROOM_LIST_IN_ACTIVITY';

//weight bearing status 1
export const FETCH_WEIGHT_BEARING_Status_1 = 'ADMINMODE/FETCH_WEIGHT_BEARING_STATUS_1'

// categoryList
export const FETCH_ADMIN_CATEGORY_LIST = 'ADMINMODE/FETCH_ADMIN_CATEGORY_LIST'
export const SAVE_ADMIN_CATEGORY_LIST = 'ADMINMODE/SAVE_ADMIN_CATEGORY_LIST';

//position list
export const FETCH_POSITION_LIST = 'ADMINMODE/FETCH_POSITION_LIST'

//durationList
export const FETCH_DURATION_LIST = 'ADMINMODE/FETCH_DURATION_LIST'

//set list
export const FETCH_SET_LIST = 'ADMINMODE/FETCH_SET_LIST'

//repetition list
export const FETCH_REPETITION_LIST = 'ADMINMODE/FETCH_REPETITION_LIST'

//resistance list
export const FETCH_RESISTANCE_LIST = 'ADMINMODE/FETCH_RESISTANCE_LIST'
export const FETCH_RESISTANCE_UNIT_LIST = 'ADMINMODE/FETCH_RESISTANCE_UNIT_LIST'

//walking aids
export const FETCH_WALKING_AIDS_LIST = 'ADMINMODE/FETCH_WALKING_AIDS_LIST'

//assistive device list
export const FETCH_ASSISTIVE_DEVICE_1_LIST = 'ADMINMODE/FETCH_ASSISTIVE_DEVICE_1_LIST'
export const FETCH_ASSISTIVE_DEVICE_2_LIST = 'ADMINMODE/FETCH_ASSISTIVE_DEVICE_2_LIST'

//assistant list
export const FETCH_ASSISTANCE_LIST = 'ADMINMODE/FETCH_ASSISTANCE_LIST'

//weight bearing status 2
export const FETCH_WEIGHT_BEARING_STATUS_2 = 'ADMINMODE/FETCH_WEIGHT_BEARING_STATUS_2'

//region list
export const FETCH_REGION_LIST = 'ADMINMODE/FETCH_REGION_LIST'

//treatment list
export const FETCH_TREATMENT_LIST = 'ADMINMODE/FETCH_TREATMENT_LIST'

//global
export const SHOW_ERROR_TIPS = 'LOGIN_INFO/SHOW_ERROR_TIPS';
export const FETCH_BASIC_INFO = 'LOGIN_INFO/FETCH_BASIC_INFO';
export const GET_BASIC_INFO = 'LOGIN_INFO/GET_BASIC_INFO';


