const DTS_APPT_TEL_CNTCT_HX_NOTES = 'DTS APPT TEL CNTCT HX NOTES';
const DTS_APPT_MAIL_CNTCT_HX_NOTES = 'DTS APPT MAIL CNTCT HX NOTES';

export {
    DTS_APPT_TEL_CNTCT_HX_NOTES,
    DTS_APPT_MAIL_CNTCT_HX_NOTES
};
