const CREATE_MODE = 'CREATE MODE';
const VIEW_MODE = 'VIEW MODE';
const UPDATE_MODE = 'UPDATE MODE';
const DISCONTINUE_MODE = 'DISCONTINUE MODE';

export {
    CREATE_MODE,
    VIEW_MODE,
    UPDATE_MODE,
    DISCONTINUE_MODE
};
