const PRE = 'PATIENT_SPEC_FUNC';
export const UPDATE_PATIENT_LIST_FIELD = `${PRE}_UPDATE_PATIENT_LIST_FIELD`;
export const GET_PATIENT_LIST = `${PRE}_GET_PATIENT_LIST`;
export const RESET_PATIENT_LIST_FIELD = `${PRE}_RESET_PATIENT_LIST_FIELD`;
export const UPDATE_PATIENT_LIST_ATTENDANCEINFO = `${PRE}_UPDATE_PATIENT_LIST_ATTENDANCEINFO`;

//link patient
export const PUT_CODE_LIST = `${PRE}_PUT_CODE_LIST`;
export const RESET_LINK_PATIENT = `${PRE}_RESET_LINK_PATIENT`;

export const SEARCH_PATIENT_PRECISELY = `${PRE}_SEARCH_PATIENT_PRECISELY`;
export const PUT_PATIENT_PRECISELY = `${PRE}_PUT_PATIENT_PRECISELY`;

export const CONFIRM_ANONYMOUS_PATIENT = `${PRE}_CONFIRM_ANONYMOUS_PATIENT`;
export const PUT_CONFIRM_ANONYMOUS_PATIENT = `${PRE}_PUT_CONFIRM_ANONYMOUS_PATIENT`;

export const RESET_CONDITION = `${PRE}_RESET_CONDITION`;

//reset Attendance
export const RESET_ATTENDANCE = `${PRE}_RESET_ATTENDANCE`;
export const RESET_ATTENDANCE_SUCCESS = `${PRE}_RESET_ATTENDANCE_SUCCESS`;

//patient list search bar
export const SEARCH_IN_PATIENT_QUEUE = `${PRE}_SEARCH_IN_PATIENT_QUEUE`;
export const PUT_SEARCH_IN_PATIENT_QUEUE = `${PRE}_PUT_SEARCH_IN_PATIENT_QUEUE`;

export const SEARCH_BY_APPOINTMENT_ID = `${PRE}_SEARCH_BY_APPOINTMENT_ID`;

//search patient list
export const SEARCH_PATIENT_LIST = `${PRE}_SEARCH_PATIENT_LIST`;
export const PUT_SEARCH_PATIENT_LIST = `${PRE}_PUT_SEARCH_PATIENT_LIST`;

export const PUC_REASON_LOG = `${PRE}_PUC_REASON_LOG`;
export const PUC_REASON_LOGS = `${PRE}_PUC_REASON_LOGS`;

export const CHECK_PATIENT_UNDER_CARE = `${PRE}_CHECK_PATIENT_UNDER_CARE`;

export const CHECK_PATIENT_NAME = `${PRE}_CHECK_PATIENT_NAME`;

//print patient list
export const PRINT_PATIENT_LIST = `${PRE}_PRINT_PATIENT_LIST`;