const PRE = 'MEDICAL';

export const GET_MEDICAL_DROP_LIST = `${PRE}_GET_MEDICAL_DROP_LIST`;
export const MEDICAL_DROP_LIST = `${PRE}_MEDICAL_DROP_LIST`;
export const GET_MEDICAL_SUMMARY_VAL = `${PRE}_GET_MEDICAL_SUMMARY_VAL`;
export const MEDICAL_SUMMARY_VAL = `${PRE}_MEDICAL_SUMMARY_VAL`;
export const UPDATE_MEDICAL_SUMMARY = `${PRE}_UPDATE_MEDICAL_SUMMARY`;